### ISSUE TITLE
Can not pass screenshot function and get  502.3 error

### ISSUE THREAD

**Issue by heherockit** [hardkoded/puppeteer-sharp#1022]
I write a function which capture a MVC page. It works well on my local host. But when I deploy project to my test server (windows server 2012), code stops at Screenshot function and I get 502.3 error. The MVC page still works properly. Here is my code:

        public async Task<string> CaptureAsync(string path, int width = 800, int height = 600)
        {
            using (var browser = await Puppeteer.LaunchAsync(new LaunchOptions { Headless = true }))
            {
                using (var page = await browser.NewPageAsync())
                {
                    await page.SetViewportAsync(new ViewPortOptions { Width = width + 30, Height = height + 50 });
                    await page.GoToAsync(path);
                    await Task.Delay(1000);

                    var clipOption = new ScreenshotOptions()
                    {
                        Clip = new PuppeteerSharp.Media.Clip
                        {
                            X = 17,
                            Y = 52,
                            Width = width,
                            Height = height
                        }
                    };
                    // It always stopped here (I logged this step)
                    return await page.ScreenshotBase64Async(clipOption);
                }
            }
        }

I tried all other screenshot function, with parameters or not. I guess it is an environment issue but can not figure it out.

**Comment by kblok** [comment]
Two questions:
 * Is this .NET Core or Full Framework?
 * Is it inside the very same server? Are you sure that your server can navigate that page?

**Comment by heherockit** [comment]
It seem I can reproduce this on my local host now.
I clone the code, build it, and ref the dll in my project replace for nuget package. The request is loading state until I press Ctrl + C in the web process command line (where I execute dotnet run). But it only happens sometimes.

**Comment by heherockit** [comment]
It failed when I hosted on IIS. I'm debugging

**Comment by heherockit** [comment]
I try to debug and see that CDPSession SendAsync message successfully, but no OnMessage occurred.

**Comment by heherockit** [comment]
> Two questions:
> 
> * Is this .NET Core or Full Framework?
> * Is it inside the very same server? Are you sure that your server can navigate that page?

1. It's .Net Core
2. It's same server, same application too. I can navigate the page, evaluate a script, but got nothing when taking screenshot - always waiting for result. It works well when I run kestrel over cmd, but failed when host on IIS.

**Comment by kblok** [comment]
It sounds like a deadlock.

**Comment by Abrissirba** [comment]
I'm having the same issue. It is working fine when I debug or run from cmd but when I host it in IIS it hangs when taking a screenshot.

**Comment by kblok** [comment]
I was able to reproduce it @heherockit, @Abrissirba

**Comment by kblok** [comment]
Maybe related to this https://github.com/GoogleChrome/puppeteer/issues/4290 ?
