### ISSUE TITLE
Tests: Implement the Chrome bit as Puppeteer does

### ISSUE THREAD

**Issue by kblok** [hardkoded/puppeteer-sharp#1048]
Puppeteer's tests have some `if (CHROME)` is some tests. Let's implement those (with true now) so we are ready for it when we implement firefox

**Comment by fgiuliani** [comment]
can I work on this?

**Comment by kblok** [comment]
Yes @fgiuliani!

**Comment by fgiuliani** [comment]
This issue is done, right?

Covered here: https://github.com/hardkoded/puppeteer-sharp/pull/1518
