### ISSUE TITLE
Screenshot in Windows Service

### ISSUE THREAD

**Issue by AzeExMachina** [hardkoded/puppeteer-sharp#1068]
### Description

Taking a screenshot of a page only works while debugging inside Visual Studio, if I build my windows service I get stuck on this method.

### Complete minimal example reproducing the issue

```csharp
public async System.Threading.Tasks.Task Async(string url, string outPath)
{
    await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
    var browser = await Puppeteer.LaunchAsync(new LaunchOptions
    {
        Headless = true
    });
    var page = await browser.NewPageAsync();
    await page.GoToAsync(url);
    await page.SetViewportAsync(new ViewPortOptions
    {
        Width = 1366,
        Height = 768
    });
    await page.ScreenshotAsync(outPath);//The process hangs here
    await page.CloseAsync();
    await browser.CloseAsync();
}
```

### Expected behavior:

I can take the screenshot

### Actual behavior:

The process hangs in the ScreenshotAsync method

### Versions

* Puppeteer-Sharp v 1.13.0, I know 1.14.0 is out but I can't update because I get this when trying to update:
"Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to add reference. The package 'Mono.Posix.NETStandard' tried to add a framework reference to 'Mono.Posix' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Error HRESULT E_FAIL has been returned from a call to a COM component."
* Targeting .NET Framework 4.7.2

**Comment by kblok** [comment]
Could you try adding `ConfigureAwait(false)` on all your awaited tasks?

**Comment by AzeExMachina** [comment]
Done that but it's still not working, tried calling with a simple google url. I find no differences from before. I can see the Chromium process being created in my task manager, as I could before, but the task is still hanging

**Comment by kblok** [comment]
How do you know that it hangs there if you are not being able to debug it? (honest question)

**Comment by AzeExMachina** [comment]
I actually put a log to file after every await to see where it got stuck

`
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision).ConfigureAwait(false);
            Log.Debug("Fetched browser with configured await");

            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true
            }).ConfigureAwait(false);
            Log.Debug("Launched browser");
            var page = await browser.NewPageAsync().ConfigureAwait(false);
            Log.Debug("Page created");
            await page.GoToAsync(url).ConfigureAwait(false);
            Log.Debug("Url resolved");`

**Comment by kblok** [comment]
@AzeExMachina Can you connect a LoggerFactory on `LaunchAsync` so we can have a full dump of all Puppeteer`s messages?

**Comment by AzeExMachina** [comment]
Ok, I was able to add the trace to the launcher, these are the last lines I can see:

https://pastebin.com/jWBBCGDm

**Comment by scabana** [comment]
@AzeExMachina I would try this: 
```
Open the Services control panel. For example: Start > Control Panel > Administrative Tools > Services.
Select the {your service} service.
Right-click the service name, and select Properties. The Service Properties window is displayed.
Select the Log On tab.
Select Local System account and then select Allow service to interact with desktop.
Click OK.
Click Restart.
```

It might be that chrome still need a window(that's not shown) to actually take the screenshot.

**Comment by kblok** [comment]
@AzeExMachina I was able to reproduce #1022. Maybe they are related.

**Comment by AzeExMachina** [comment]
@scabana Thanks for your suggestion, however that didn't work, I've tried a couple of times but it still got stuck in the same place.
@kblok Thanks, hope so!

I've seen that this issue only happens when inside the service, I've tried building a console application and that actually works, sadly that's not an acceptable solution for my case

**Comment by kblok** [comment]
Maybe related to this https://github.com/GoogleChrome/puppeteer/issues/4290 ?

**Comment by AzeExMachina** [comment]
Yes, definitely related. I've tried downgrading to puppeteer-sharp 1.11.0 and it actually works there. I don''t know if the issue is related to puppetteer running headless, because it actually works if you run it as a fake console application, outputting to Windows Application and not console. However, for now I'm keeping puppeteer to 1.11 until they are able to solve this.

Thanks @kblok for the heads up!

**Comment by heherockit** [comment]
@AzeExMachina I downgrade to 1.11 but it still doesn't work. Do you deploy webapp with InProcess profile?

**Comment by luowenjia1996** [comment]
its about how to break session0 in windowsService
