### ISSUE TITLE
ScreenshotDataAsync method never returns if a Page object is being created on a separate thread.

### ISSUE THREAD

**Issue by rgelb** [hardkoded/puppeteer-sharp#1076]
### Description

`ScreenshotDataAsync` method never returns if the code creates a new browser page during that operation.  

The purpose for this is to create an auto-refillable ConcurrentQueue of pages that would provide the next available page to a client that asks for it.  The idea is to create 20 pages via `NewPageAsync` and hand them out to clients who ask for a page.  When the amount of available pages gets down to 3, create more pages.  

### Complete minimal example reproducing the issue

The code starts the browser, creates a page, goes to a new thread to create the screenshot.  Meanwhile, the main thread creates 20 more new pages.  

```csharp
void Main(string[] args) {
    var options = new LaunchOptions() {
        // replace with your own or downllad
        ExecutablePath = @"C:\Projects\net2\Tools\WidgetImages\chromium\chrome.exe",
        Headless = false
    };
    Browser browser = Puppeteer.LaunchAsync(options).Result;
    Page page = browser.NewPageAsync().Result;

    Task.Run(() => TakeScreenshot(page, "https://www.google.com"));

    // create a bunch of pages
    var pagesQueue = new ConcurrentQueue<Page>();
    for (int i = 0; i < 20; i++) {
        Debug.WriteLine(DateTime.Now.Ticks + $" CreatePage {i}");
        pagesQueue.Enqueue(browser.NewPageAsync().Result);
    }

    Console.ReadKey();
}

public static void TakeScreenshot(Page page, string url) {
    var viewportOptions = new ViewPortOptions {
        Width = 800,
        Height = 800
    };
    page.SetViewportAsync(viewportOptions).Wait();
    var webPage = page.GoToAsync(url).Result;

    // get the screenshot
    Debug.WriteLine("ScreenshotDataAsync start");
    var imageBytes = page.ScreenshotDataAsync().Result;
    Debug.WriteLine("ScreenshotDataAsync End");
    
    var ms = new MemoryStream(imageBytes);
    Image img = Image.FromStream(ms);

    string desktopDir = Environment.GetFolderPath(SpecialFolder.DesktopDirectory);
    string path = Path.Combine(desktopDir, "img1.png");
    img.Save(path);
}

```

### Expected behavior:

The `ScreenshotDataAsync` method generates a screenshot.

### Actual behavior:

The `ScreenshotDataAsync` method never returns.

### Versions

* PuppeteerSharp 1.14
* .NET Core 2.2.

**Comment by kblok** [comment]
You are getting deadlocks. You shouldn't use `.Result`.

Some reading http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by rgelb** [comment]
@kblok I rewrote it without .Result - I am getting the same exact problem.  There is definitely a deadlock somewhere 

```csharp
static async Task Main(string[] args) {
    var options = new LaunchOptions() {
        // replace with your own or download
        ExecutablePath = @"C:\Projects\net2\Tools\WidgetImages\chromium\chrome.exe",
        Headless = false
    };
    Browser browser = await Puppeteer.LaunchAsync(options);
    Page page = await browser.NewPageAsync();

    _ = Task.Run(async () => await TakeScreenshot(page, "https://www.google.com"));

    // create a bunch of pages
    var pagesQueue = new ConcurrentQueue<Page>();
    for (int i = 0; i < 20; i++) {
        Debug.WriteLine($"CreatePage {i}");
        pagesQueue.Enqueue(await browser.NewPageAsync());
    }

    Console.ReadKey();
}

public static async Task TakeScreenshot(Page page, string url) {
    var viewportOptions = new ViewPortOptions {
        Width = 800,
        Height = 800
    };
    await page.SetViewportAsync(viewportOptions);
    var webPage = await page.GoToAsync(url);

    // get the screenshot
    Debug.WriteLine("ScreenshotDataAsync start");
    var imageBytes = await page.ScreenshotDataAsync();
    Debug.WriteLine("ScreenshotDataAsync End");
    
    var ms = new MemoryStream(imageBytes);
    Image img = Image.FromStream(ms);

    string desktopDir = Environment.GetFolderPath(SpecialFolder.DesktopDirectory);
    string path = Path.Combine(desktopDir, "img1.png");
    img.Save(path);
}
```

I get the following output - it never gets past `await page.ScreenshotDataAsync()`

> CreatePage 0
> CreatePage 1
> CreatePage 2
> CreatePage 3
> CreatePage 4
> CreatePage 5
> CreatePage 6
> CreatePage 7
> CreatePage 8
> CreatePage 9
> CreatePage 10
> CreatePage 11
> CreatePage 12
> CreatePage 13
> ScreenshotDataAsync start
> CreatePage 14
> CreatePage 15
> CreatePage 16
> CreatePage 17
> CreatePage 18
> CreatePage 19

**Comment by kblok** [comment]
Cool @rgelb. That might be related to #1068

**Comment by rgelb** [comment]
@kblok I don't think it is.  I can't take a screenshot while debugging in Visual Studio either.  I also standalone console app.  Tried downgrading to 1.11.0 - nothing worked.  

I've hooked up a loggerFactory to it and recorded the [output](https://pastebin.com/9qek9A2M).  I had to reduce the number of pages created to 5 because it was generating too much data.

**Comment by kblok** [comment]
Cool, thanks for the report

**Comment by rgelb** [comment]
One more thing that I just found.  If Headless = true, it doesn't seem to block.

**Comment by marcelrienks** [comment]
I had a similar issue, while running headless = false, screenshots would block.
In my case it was due to the fact that I had multiple pages (tabs) and the page that was trying to take a screenshot was not the one that had focus.

There is a known focus issue when running multiple pages in headless = false.
Try test againa and insure that the page taking the screenshot is the one that has focus.

**Comment by mschutter** [comment]
Is there any idea when this is going to solved? @kblok

**Comment by mschutter** [comment]
Is there any idea when this is going to solved? @kblok

In run mode: 
When creating a screenshot after going to a url just after the page object has been created works. 

In the [afterstep] or [afterscenario] method a screenshot is not working because the page is probably created in a different thread.

In Debug mode i can create a screenshot  in [afterstep] or [afterscenario] method.

Doesn't matter when doing headless or not. 


console application .net core 3.1
Puppeteersharp 2.0.4
specflow xunit 3.4.14

**Comment by kblok** [comment]
@mschutter do you have any code for me to test?

**Comment by mschutter** [comment]
Just found out it was caused by something else. Screenshot is working fine. sorry for the trouble.

**Comment by mcopur** [comment]
> Just found out it was caused by something else. Screenshot is working fine. sorry for the trouble.

Hi, How did you solve it or what was the problem? I have the same problem, could you help me with that?
