### ISSUE TITLE
Cancelling async operations

### ISSUE THREAD

**Issue by iokill** [hardkoded/puppeteer-sharp#1149]
Hi!

I'm using PuppeteerSharp to generate PDFs for webpages. 

Is there a way to cancel any of the async methods like 

```csharp
await page.PdfAsync(outputFile, myCancellationToken);
// or
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision, myCancellationToken);
``` 
Since some of these operations can take quite some time, it would be nice to give the user the option to cancel it, if he accidentally triggered the PDF generation.

Thanks!

**Comment by kblok** [comment]
It would be great to implement this.
I think it might be easy to implement in places where we use native async methods, like `DownloadAsync`. It's quite tricky when we call chromium methods because we don't have a native method we can pass the token to because we are building TaskCompletionSources and fulfilling them when we get the right message from Chromium. 
But it's a nice to have for sure.

**Comment by madelson** [comment]
@kblok given that we are using `TaskCompletionSource`, when we initialize the TCS we could just do:

```
if (cancellationToken.CanBeCanceled)
{
    var registration = cancellationToken.Register(() => tcs.TrySetCanceled());
    tcs.ContinueWith(_ => registration.Dispose());
}
```

Then when the message does come back from Chromium, we'd call `tcs.TrySetResult()` and it would noop becuase the task was already in a terminal state.

**Comment by sksk571** [comment]
We are currently using cancellation token registration on the top level that disposes browser like this:
```
try
{
    using var _ = cancellationToken.Register(() => browser.Dispose());
    await using var page = await browser.NewPageAsync();
    await page.SetContentAsync(html);
    // ...
}
catch (PuppeteerException) when (cancellationToken.IsCancellationRequested)
{
    throw new OperationCanceledException();
}
```
This is not ideal and we would rather use built-in cancellation support, if it's made available.
Operations using WebSocketTransport.SendAsync can use native cancellation support provided by WebSocket on message sending and, as it was noted above, cancellation token registration can be used on message receiving. This would cover a big amount of methods, like NewPageAsync() or SetContentAsync() in the example above.
