### ISSUE TITLE
Cache is force disabled when intercept requests

### ISSUE THREAD

**Issue by EtherealAO** [hardkoded/puppeteer-sharp#1185]
### Description
if i use`await page.SetRequestInterceptionAsync(true);` , cache is force disabled(at least images is not caching). But I just want to intercept xhr requests not any request. Any method to enable caching while intercept requests?

**Comment by EtherealAO** [comment]
resolved.
change lib/PuppeteerSharp/NetworkManager.cs => 'CacheDisabled = _userCacheDisabled || _protocolRequestInterceptionEnabled' (line 125) to 'CacheDisabled = _userCacheDisabled'

**Comment by kblok** [comment]
Asking upstream here https://github.com/GoogleChrome/puppeteer/issues/4620

**Comment by Androbin** [comment]
Update: https://github.com/puppeteer/puppeteer/issues/4620#issuecomment-834717428

**Comment by Androbin** [comment]
See https://github.com/hardkoded/puppeteer-sharp/pull/1765
