### ISSUE TITLE
CancellationToken and annoying Crashes 

### ISSUE THREAD

**Issue by Gdocal** [hardkoded/puppeteer-sharp#1216]
Is there any reason why CancellationToken is not implemented? 

Currently, I have a very annoying issue and trying to find a way to solve it...
I have 5 long run sessions, they should work 24/7 but every day approximately every 24 hours, Chrome page get crashed, as result my puppeteer automation just stuck until I manually press Reload page in Chrome. After this everything continues to work as expected as nothing happened. 
I subscribed for all possible events for Page, but seems this issue is undetectable.  I think the root of a problem somewhere inside dev tools protocol.
I think Chrome just stop to send any response after the crash, but we wait for it in Connection.SendAsync, we wait for it without any timeout, and any other possibility to cancel it.

Currently, I added the logger to puppeteer, and hope to catch some data which will help me to catch Page crashing... but even if I caught it I am not sure there is a way to fix that broken state...

Is there any advice about what else I can do with this issue?

**Comment by d668** [comment]
I have a similar issue await page.GoToAsync(url, options); gets rejected by proxy authentication and stays with open credentials dialog indefinitely. I guess a workaround solution in this case to periodically check for old Chrome instances and kill them causing app exception that you can catch
