### ISSUE TITLE
Inspector.detached not catched

### ISSUE THREAD

**Issue by Gdocal** [hardkoded/puppeteer-sharp#1219]
Currently, I have a very annoying issue and trying to find a way to solve it...
I have 5 long run sessions, they should work 24/7 but every day approximately every 24 hours, Chrome page get crashed, as result my puppeteer automation just stuck until I manually press Reload page in Chrome. After this everything continues to work as expected as nothing happened.
I subscribed for all possible events for Page, but seems this issue is undetectable. I think the root of a problem somewhere inside dev tools protocol.
I think Chrome just stop to send any response after the crash, but we wait for it in Connection.SendAsync, we wait for it without any timeout, and any other possibility to cancel it.

I setup logger and log all raw messages from chrome and I found an issue: Just before the crash we receive **'Inspector.detached**' event, and seems currently we ignore it and continue to wait for the response from our previous request. 

After page manually restored I receive '**Inspector.targetReloadedAfterCrash**' event.

There are more logs :
[puppeteer_log_inspector.detached.txt](https://github.com/kblok/puppeteer-sharp/files/3400337/puppeteer_log_inspector.detached.txt)

Another question is how programmatically revert to normal state?

**Comment by Gdocal** [comment]
As I understand:
The issue is Chrome doesn't dispatch event  **Inspector.targetCrashed** in some cases...
 I tried to reproduce the issue by trying to kill the renderer process manually...every time I got **Inspector.targetCrashed**  and only one time from 20 attempts  I got Inspector.detached but didn't understand how.... after I manually Reload page I also got  **Inspector.targetReloadedAfterCrash** (the same event when I just only got only **Inspector.detached**

When puppeteer receives **Inspector.targetCrashed** all pending waiters failed with exceptions but this is not my case

**Comment by Gdocal** [comment]
_page.ReloadAsync() doesnt work when Inspector.targetCrashed recevied...
but _browser.NewPageAsync still works

**Comment by kblok** [comment]
We would need to find a way to create a test to replicate that.

**Comment by Gdocal** [comment]
I decided to dig deeply 
I found the source code in chromium which is responsible for this behavior
https://cs.chromium.org/chromium/src/content/browser/devtools/render_frame_devtools_agent_host.cc?sq=package:chromium&dr=C&g=0&l=572

There are two alternatives what will happen when something goes wrong with the render process:
The first case is when the renderer process terminated status is one of these statuses: 
TERMINATION_STATUS_ABNORMAL_TERMINATION
TERMINATION_STATUS_PROCESS_WAS_KILLED
TERMINATION_STATUS_PROCESS_CRASHED
TERMINATION_STATUS_LAUNCH_FAILED
in this case, we will receive Inspector.targetCrashed
[https://cs.chromium.org/chromium/src/out/Debug/gen/content/browser/devtools/protocol/inspector.cc?l=68&gsn=TargetCrashed](url)
another case is when the renderer process terminated status is one of these statuses: 
TERMINATION_STATUS_NORMAL_TERMINATION
TERMINATION_STATUS_STILL_RUNNING
TERMINATION_STATUS_MAX_ENUM
TERMINATION_STATUS_OOM
in this case, we will receive Inspector.detached with reason "Render process gone."
https://cs.chromium.org/chromium/src/content/browser/devtools/render_frame_devtools_agent_host.cc?sq=package:chromium&dr=C&g=0&l=572

I think my renderer processes get TERMINATION_STATUS_OOM status on my machines. 

Anyway, I would like to receive exception about this for all my stuck awaiters...and not just sitting around without the ability to return without restarting the whole program...

**Comment by Gdocal** [comment]
@kblok I am afraid your solution will not solve the issue. I can listen and send messages to Chrome right now just by creating new CDPSession.

The problem even after I catch Inspector.detached my active awaiters will be stuck without the ability to return...

**Comment by Gdocal** [comment]
@kblok My issue is not solve could you please reopen it?
