### ISSUE TITLE
Download pdf file on button click

### ISSUE THREAD

**Issue by vickyrathee** [hardkoded/puppeteer-sharp#1238]
How to implement the file download in puppeteer C#? I also read on main repo but not successful in implementing a solution for these 2 example below . 

From the original repo, which seems to work as per up-votes there. - https://github.com/GoogleChrome/puppeteer/issues/299

> await browser.on('targetcreated', async () =>{
>   const pageList = await browser.pages();
>   console.log(pageList.length);
>   pageList.forEach((page) => {
>     page._client.send('Page.setDownloadBehavior', {
>       behavior: 'allow',
>       downloadPath: './',
>     });
> });

**Example 1 :** When I have the access of pdf URL, I should be able to navigate and download the pdf.

```
            var page = await GetChrome();

            var client = await page.Target.CreateCDPSessionAsync();
            await client.SendAsync("Page.setDownloadBehavior",
                new
                {
                    behavior = "allow",
                    downloadPath = @"Y:\Temp\"
                }, false);

            await page.GoToAsync("https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf");
         
            await page.PdfAsync(@"Y:\Temp\example.pdf"); 
```
It throw error as `NavigationException: net::ERR_ABORTED at https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf`

**Example 2** - When there is are some javascript code creating the download link dynamically, I should be able to click on the download button to download the pdf.

```
            var page = await GetChrome();
            var client = await page.Target.CreateCDPSessionAsync();
            await client.SendAsync("Page.setDownloadBehavior",
                new
                {
                    behavior = "allow",
                    downloadPath = @"Y:\Temp\"
                }, false);

            await page.GoToAsync("https://agenty.github.io/Agenty.TestData/forum/file-download.html");
            await page.ClickAsync(".download-btn");
            Console.Write("Running download");
            await Task.Delay(5000);
```

I was successfully on example 2 when running the program without `headless:false`, but I am looking for some solution in headless mode.

Both example code has the public pages for testing. Any suggestion will be appreciated.

**Comment by kblok** [comment]
I went throw https://github.com/GoogleChrome/puppeteer/issues/299 @vickyrathee. It seems we need to wait for some change there.

**Comment by vickyrathee** [comment]
@kblok  I can't even use the `BufferAsync`  to download the pdf?  I tried and it just save an empty 1kb pdf with no content.

Here is code : 

### Go to pdf page

```
var page = await GetChrome();
page.Response += async (sender, e) =>
            {
               await Page_ResponseAsync(sender, e);
            };
            await page.GoToAsync("https://agenty.github.io/Agenty.TestData/textract/pdf-example.pdf", waitUntil: new[] { WaitUntilNavigation.Load, WaitUntilNavigation.DOMContentLoaded, WaitUntilNavigation.Networkidle0 });
            Console.WriteLine("Download completed");
```

### Handle response
```
        private static async Task Page_ResponseAsync(object sender, ResponseCreatedEventArgs e)
        {
            string contentType = null;

            if (e.Response.Headers.ContainsKey("content-type"))
                contentType = (string)e.Response.Headers["content-type"];

            if (e.Response.Headers.ContainsKey("Content-Type"))
                contentType = (string)e.Response.Headers["Content-Type"];

            //Console.WriteLine(contentType);
            if (contentType.Contains("application/pdf"))
            {
                string fileName = null;
                var lastSlashIndex = e.Response.Url.LastIndexOf('/');
                if (lastSlashIndex != -1)
                    fileName = e.Response.Url.Substring(lastSlashIndex + 1);
                else
                    fileName = e.Response.Url;
                Console.WriteLine("fileName : " + fileName);
                var buffer = await e.Response.BufferAsync();
                File.WriteAllBytes($@"Y:\temp\{fileName}", buffer);                
            }
        }
```

It saves an empty pdf to directory with no content.

![image](https://user-images.githubusercontent.com/6106479/63220636-bd3c7300-c1a9-11e9-98bc-b57251ba7b56.png)

**Comment by ebardier** [comment]
Hi @vickyrathee, Could you solve the problem? 
I'm in the same situation..
Thanks!

**Comment by vickyrathee** [comment]
@ebardier I was never able to solve it.

**Comment by konstantinLyang** [comment]
Why issue was closed?

**Comment by kblok** [comment]
@konstantinLyang You should be able to get this done by using `SetDownloadBehaviorAsync`. If not please create a ticket with your use-case :)

**Comment by StefH** [comment]
Example code:
``` c#
await using var browser = await Puppeteer.LaunchAsync(launchOptions);
await using var browserContext = await browser.CreateBrowserContextAsync(new BrowserContextOptions
{
    DownloadBehavior = new DownloadBehavior
    {
        Policy = DownloadPolicy.Allow,
        DownloadPath = Path.GetFullPath(DownloadFolder)
    }
});

await using var page = await browserContext.NewPageAsync(new CreatePageOptions { Type = CreatePageType.Tab });
// Other code ...
```
