### ISSUE TITLE
1px increments in MarginOptions are larger than 1px

### ISSUE THREAD

**Issue by nagilum** [hardkoded/puppeteer-sharp#1252]
### Versions

* Puppeteer version: 1.19
* ASP.NET Core version: 2.2
* Downloaded Chromium version: Win64-674921
* Running on Windows under Visual Studio 2019/IIS Express

### Description

I'm using the MarginOptions to set bottom margin of the page to render a custom footer. The height I set as CSS in the footer template does not match the MarginOptions Bottom, and the increment of px value I set for the Bottom MarginOptions does not match 1px.

### Code

```csharp
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
var browser = await Puppeteer.LaunchAsync(new LaunchOptions {Headless = true});
var page = await browser.NewPageAsync();
await page.GoToAsync("...");
var bytes = await page.PdfDataAsync(
    new PdfOptions {
        PrintBackground = true,
        DisplayHeaderFooter = true,
        FooterTemplate = @"
            <style>
                #footer { padding: 0 !important; }
                * { box-sizing: border-box; }
                div.footer { font-size: 10px; height: 50px; width: 100%; }
                div.footer div { display: inline-block; }
            </style>
            <div class='footer'>Page: <div class='pageNumber'></div> of <div class='totalPages'></div></div>
        ",
        MarginOptions = new MarginOptions {
            Top = "0px",
            Bottom = "66px"
        },
        Format = PaperFormat.A4
    });
```

First of, I had to set the MarginOptions Bottom to 66px to match the 50px height style of the footer. Which looks like this:

![MarginOptions-Bottom-66px](https://user-images.githubusercontent.com/728839/63950517-6b82cb00-ca7c-11e9-8ce4-fc7503b0688c.png)

But if I set the MarginOptions Bottom to 67px, I get this:

![MarginOptions-Bottom-67px](https://user-images.githubusercontent.com/728839/63950532-70e01580-ca7c-11e9-92bd-3708662cfa1a.png)

And finally, if I actually do set MarginOptions Bottom to 50px, I get this:

![MarginOptions-Bottom-50px](https://user-images.githubusercontent.com/728839/63950538-74739c80-ca7c-11e9-92be-717f3435ae49.png)

As can be seen, 1px increments of the margin is way larger than 1px. And the margin does not match actual size of footer template size.

**Comment by kblok** [comment]
What happens if you don't set a margin?
I think you don't need to set a margin to insert a footer.

**Comment by nagilum** [comment]
If I don't set any margin the footer isn't rendered, or at least not visible.

### Code
```csharp
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
var browser = await Puppeteer.LaunchAsync(new LaunchOptions {Headless = true});
var page = await browser.NewPageAsync();
await page.GoToAsync("...");
var bytes = await page.PdfDataAsync(
    new PdfOptions {
        PrintBackground = true,
        DisplayHeaderFooter = true,
        FooterTemplate = @"
            <style>
                #footer { padding: 0 !important; }
                * { box-sizing: border-box; }
                div.footer { font-size: 10px; height: 50px; width: 100%; }
                div.footer div { display: inline-block; }
            </style>
            <div class='footer'>Page: <div class='pageNumber'></div> of <div class='totalPages'></div></div>
        ",
        Format = PaperFormat.A4
    });
```

### How it looks
![image](https://user-images.githubusercontent.com/728839/64169652-8e332c00-ce4e-11e9-96df-cf2a64882164.png)

**Comment by kblok** [comment]
It seems there are some issues related to footer styling. And some of them were label as `chromium` issues. See https://github.com/GoogleChrome/puppeteer/issues/2388 and https://github.com/GoogleChrome/puppeteer/issues/1853

**Comment by KoalaBear84** [comment]
I think I've had the same. And that was also with default page number examples. When it was too narrow, it cut off the page numbers themselves but still did print "Page of" without the page numbers. So it looks like it does not print part that are intersecting with the body.
