### ISSUE TITLE
Use code style analyzers

### ISSUE THREAD

**Issue by Meir017** [hardkoded/puppeteer-sharp#130]
add [StyleCop.Analyzers](https://www.nuget.org/packages/StyleCop.Analyzers) to the solution

another option would be an `.editorconfig` file

not completely sure what our conventions are...

I suggest we use the conventions `cake-build` use in their project [`Settings.StyleCop`](https://github.com/cake-build/cake/blob/develop/src/Settings.StyleCop) & [`stylecop.json`](https://github.com/cake-build/cake/blob/develop/src/stylecop.json)

**Comment by kblok** [comment]
We are doing that now.
