### ISSUE TITLE
The remote party closed the WebSocket connection without completing the close handshake.

### ISSUE THREAD

**Issue by Priyanker** [hardkoded/puppeteer-sharp#1326]
`await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision); `
`var browserLaunchArgs = new[] { "--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage" };`

`var browser = await Puppeteer.LaunchAsync(new LaunchOptions { Headless = true, Args = browserLaunchArgs });`
`var pages = await browser.PagesAsync();`

The Puppeteer version I am using is 1.18.0
And the .Net Core version is 2.0

**The exception message I got was:** 

developerMessage: "
↵
↵Exception: 
↵
↵{"CloseReason":"The remote party closed the WebSocket connection without completing the close handshake.","Message":"Protocol error(Page.captureScreenshot): Target closed. (The remote party closed the WebSocket connection without completing the close handshake.)","Data":{},"InnerException":null,"StackTrace":"   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at PuppeteerSharp.CDPSession.<SendAsync>d__30.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at PuppeteerSharp.CDPSession.<SendAsync>d__29`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at PuppeteerSharp.Page.<PerformScreenshot>d__216.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at PuppeteerSharp.Helpers.TaskQueue.<Enqueue>d__2`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at PuppeteerSharp.ElementHandle.<ScreenshotBase64Async>d__13.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n

**Comment by kblok** [comment]
That's not your entire code, right?
It seems that Chromium is crashing when you try to take a screenshot.

**Comment by Priyanker** [comment]
Yes, it's not the entire code.
What are the possible reasons for this issue to occur?

**Comment by dasmeer** [comment]
> 
> 
> That's not your entire code, right?
> It seems that Chromium is crashing when you try to take a screenshot.

hi, can you please suggest some reasons why Chromium is crashing ?

**Comment by KyleC69** [comment]
It seems that this has not been resolved. I am getting this error consistently in headless mode. I have been looking around for months now for different solutions and can't seem to narrow down the problem. Using current version 9.10 just logging into a site and getting the cookies. This seems to happen while waiting for the response after pressing enter key (login/submit) have tried to incorporate various wait scenarios to alter results, nothing seems to help. Any help would be appreciated.
