### ISSUE TITLE
Getting 'Could not load type 'PuppeteerSharp.RevisionInfo' from assembly 'PuppeteerSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by albertkurland** [hardkoded/puppeteer-sharp#1330]
Just created a new Console .Net Framework 4.7.1 app with VS 2017. 
Ran Install-Package PuppeteerSharp -Version 1.20.0

Trying to run the first sample below in VS debugger and getting an error below. I see PuppeteerSharp.DLL in \bin\Debug directory.

Getting 'Could not load type 'PuppeteerSharp.RevisionInfo' from assembly 'PuppeteerSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

    class Program
    {
        static void Main(string[] args)
        {
            Test().Wait();
        }

        private static async Task Test()
        {
            await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true
            });
            var page = await browser.NewPageAsync();
            await page.GoToAsync("https://google.com");
            await page.ScreenshotAsync("test.png", new ScreenshotOptions { Type = ScreenshotType.Png });
        }
    }

**Comment by phan89** [comment]
@albertkurland @kblok 

Albert, could you check to see if you named your project PuppeteerSharp, which caused the namespace confusion?

I'm pretty certain it is the case and not because there's a bug in this project

Thanks
