### ISSUE TITLE
Proxy with credentials...

### ISSUE THREAD

**Issue by mikrodotnet** [hardkoded/puppeteer-sharp#1331]
Does anyone have a solution for using proxies that require credentials? If anyone's discovered a workaround I'd really appreciate it.

**Comment by kblok** [comment]
@mikrodotnet do we have some code example to check?

**Comment by mikrodotnet** [comment]
sure, here's just a basic sample in vb.net. I've tried setting Proxy-Authorization header as well, but still no luck. As for the proxy-server arg I've tried every kind of proxy format.



````
Imports PuppeteerSharp
....
Dim proxyUserName As String = "testing"
Dim proxyPassword As String = "testing"
Await New BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision)
Dim browser = Await Puppeteer.LaunchAsync(New LaunchOptions With {
					     .Headless = False,
					     .IgnoreHTTPSErrors = True,
					     .Args = New String() {"--proxy-server=http://1.2.3.4:5678",
										    "--no-sandbox",
										    "--disable-setuid-sandbox",
										    "--disable-infobars",
										    "--disable-extensions",
										    "--disable-web-security",
										    "--ignore-certificate-errors"}})

Dim page As Page = Await browser.NewPageAsync()
Await page.AuthenticateAsync(New PuppeteerSharp.Credentials() With {.Username = proxyUserName, .Password = proxyPassword})
Await page.GoToAsync("https://whatismyipaddress.com/")
````

**Comment by ahmadalli** [comment]
remove `http://` from the beginning of `--proxy-server` and try again

**Comment by mikrodotnet** [comment]
@ahmadalli I've tried that also but I keep getting the same or similar error when I'm testing with my own dedicated proxies that load the same url in Chrome, Firefox etc. I just can't get Puppeteer to work with proxies that require credentials. I don't know what else to try. I'm willing to try about anything at this point. 

P.S. - It does work with standard IP:port proxies that don't require credentials.

**Comment by ahmadalli** [comment]
@mikrodotnet My tries to achieve authenticated http proxy with chrome without getting help from other tools failed. I ended up moving my code to a docker container and create a docker compose environment with `polipo` as another service which supports `parentProxy` and `parentAuthCredentials`

here's part of my docker-compose file:

```yaml
version: '3.4'

services:
  myWebService:
#...
    environment:
      - APP_PROXY=http://polipo:8123
  polipo:
    image: vimagick/polipo:latest
    ports:
      - "8123"
    command: 
      parentProxy=proxy
      parentAuthCredentials=user:pass

```

you can also install polipo or [cow](https://github.com/cyfdecyf/cow) on your system and configure them to have a local http proxy without authentication

**Comment by mikrodotnet** [comment]
@ahmadalli ah ok, I'll look into using something like that. Thanks for helping me out, I appreciate it.

**Comment by Xeevis** [comment]
I've successfully authenticated with NordVPN with the following code, it works flawlessly, maybe it will help somebody.

```csharp
var browser = await Puppeteer.LaunchAsync(new LaunchOptions
{
    Headless = true,
    Args = new[] { "--proxy-server=ch168.nordvpn.com" }
});
using (var page = await browser.NewPageAsync())
{
    await page.AuthenticateAsync(new Credentials() { Username = "<NordVPN username>", Password = "<NordVPN password>" });
    await page.GoToAsync("https://www.whatismyip.com/");
    await page.ScreenshotAsync("whatismyip.png");
}
```
![image](https://user-images.githubusercontent.com/5835044/72690954-b2538900-3b21-11ea-99cd-d92c749f4ceb.png)

**Comment by Flaminel** [comment]
> 
> 
> I've successfully authenticated with NordVPN with the following code, it works flawlessly, maybe it will help somebody.
> 
> ```cs
> var browser = await Puppeteer.LaunchAsync(new LaunchOptions
> {
>     Headless = true,
>     Args = new[] { "--proxy-server=ch168.nordvpn.com" }
> });
> using (var page = await browser.NewPageAsync())
> {
>     await page.AuthenticateAsync(new Credentials() { Username = "<NordVPN username>", Password = "<NordVPN password>" });
>     await page.GoToAsync("https://www.whatismyip.com/");
>     await page.ScreenshotAsync("whatismyip.png");
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/5835044/72690954-b2538900-3b21-11ea-99cd-d92c749f4ceb.png)

Strangely enough, with your exact code I was not able to connect to a proxy server from nordvpn. Changing the server didn't do anything. I am always getting ```ERR_PROXY_CONNECTION_FAILED```.

**Comment by Xeevis** [comment]
@Flaminel It appears NordVPN has discontinued HTTP Proxy servers, have to use their native apps, browser extensions, socks5 or OpenVPN. Nothing that can be controlled inside the Puppeteer's code I'm afraid.

**Comment by Flaminel** [comment]
@Xeevis on that note I found [this](https://www.chromium.org/developers/design-documents/network-stack/socks-proxy), which I haven't managed to get working, but also this [ issue#1160](https://github.com/hardkoded/puppeteer-sharp/issues/1160), but I don't know what to make of this, because it doesn't work.
My code looks like this at the moment:
```
private int GetNextFreePort()
{
    TcpListener listener = new TcpListener(IPAddress.Loopback, 1080);
    listener.Start();
    int port = ((IPEndPoint)listener.LocalEndpoint).Port;
    listener.Stop();
    return port;
}

public async Task Run()
{
    IPEndPoint localEndpoint = new IPEndPoint(IPAddress.Parse("127.0.0.1"), GetNextFreePort());
    IPEndPoint remoteEndpoint = new IPEndPoint(IPAddress.Parse("109.202.99.40"), 1080);
    ISocksRelayServer relay = new SocksRelayServer.SocksRelayServer(localEndpoint, remoteEndpoint)
    {
        Username = "usr",
        Password = "pwd",
    };
    relay.Start();

    LaunchOptions launchOptions = new LaunchOptions
    {
        Headless = false,
        Args = new string[] { "--proxy-server=\"socks5://127.0.0.1:1080\" --no-first-run --ignore-certificate-errors --window-size=\"1450,850\"" }
    };

    using (Browser browser = await Puppeteer.LaunchAsync(launchOptions))
    {
        using (Page page = await browser.NewPageAsync())
        {
            _ = await page.GoToAsync("https://www.whatismyip.com/");
            await page.ScreenshotAsync("whatismyip.png");
        }
    }
}
```
```109.202.99.40``` is the IP of ```amsterdam.nl.socks.nordhold.net```, one of the servers from [this](https://support.nordvpn.com/Connectivity/Proxy/1047410732/Proxy-setup-on-uTorrent.htm) tutorial from NordVPN.

**Comment by Flaminel** [comment]
@Xeevis I've installed ```HttpToSocks5Proxy``` NuGet package and now my code looks like this:
```
bool isProxyOk = false;
HttpToSocks5Proxy proxy = null;
string responseIP = string.Empty;

while (!isProxyOk)
{
	proxy = new HttpToSocks5Proxy("amsterdam.nl.socks.nordhold.net", 1080, nordvpn_service_usr, nordvpn_service_pwd);

	HttpClientHandler handler = new HttpClientHandler { Proxy = proxy };
	HttpClient httpClient = new HttpClient(handler, true);
	HttpResponseMessage response = await httpClient.SendAsync(new HttpRequestMessage(HttpMethod.Get, "https://httpbin.org/ip"));

	responseIP = await response.Content.ReadAsStringAsync();
	if (!string.IsNullOrEmpty(responseIP))
	{
		isProxyOk = true;
	}
}

Console.WriteLine($"Response: {responseIP}");

LaunchOptions launchOptions = new LaunchOptions
{
	Headless = false,
	Args = new string[]
	{
		$"--proxy-server=127.0.0.1:{proxy.InternalServerPort}",
		"--no-first-run",
		"--ignore-certificate-errors",
	}
};

using (Browser browser = await Puppeteer.LaunchAsync(launchOptions))
{
	using (Page page = await browser.NewPageAsync())
	{
		_ = await page.GoToAsync("https://www.whatismyip.com/");
		await page.ScreenshotAsync("whatismyip.png");
	}
}
```

It works now, but it's inconsistent. I've had problems with proxy authentication (the ```HttpResponseMessage``` was unauthorized) and also sometimes the browser is still waiting for the proxy's response, even after the page was loaded, throwing an exception after 30 seconds. Please let me know if you experience the same problems.

**Comment by Xeevis** [comment]
@Flaminel This code seems to be working fine, I've used [Yove.Proxy](https://github.com/TheSuunny/Yove.Proxy) because it's newer and simpler with just 500 lines of code. Also tested with [Microsoft's Playwright](https://github.com/microsoft/playwright-sharp). Make sure to use NordVPN service credentials and not the NordAccount credentials.

![image](https://user-images.githubusercontent.com/5835044/106440121-c0e4b800-6478-11eb-8ef6-f0bd80657d6c.png)

Outputs:

```
HttpClient: {"ip":"213.152.176.252"}
Playwright: {"ip":"213.152.176.252"}
Puppeteer:  {"ip":"213.152.176.252"}
```

```csharp
using System;
using System.Net.Http;
using System.Threading.Tasks;
using PlaywrightSharp;
using PuppeteerSharp;
using Yove.Proxy;

namespace NordVPNSocks5ProxyTests
{
    class Program
    {
        async static Task Main()
        {
            using ProxyClient proxy = new(
                Proxy: "amsterdam.nl.socks.nordhold.net:1080",
                Username: "<NordVPN service username>",
                Password: "<NordVPN service password>",
                Type: ProxyType.Socks5
            )
            { ReadWriteTimeOut = 10000 };

            try
            {
                await TestHttpClientProxy(proxy);
                await TestPlaywrightProxy(proxy.GetProxy(null));
                await TestPuppeteerProxy(proxy.GetProxy(null));
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }

        private static async Task TestHttpClientProxy(ProxyClient proxy)
        {
            using var handler = new HttpClientHandler { Proxy = proxy };
            using var client = new HttpClient(handler);

            Console.WriteLine($"HttpClient: {await client.GetStringAsync("https://api.ipify.org/?format=json")}");
        }

        private static async Task TestPlaywrightProxy(Uri localProxyUrl)
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(proxy: new() { Server = localProxyUrl.Authority });

            var page = await browser.NewPageAsync();
            await page.GoToAsync("https://api.ipify.org/?format=json");
            Console.WriteLine($"Playwright: {await page.GetTextContentAsync("pre")}");
        }

        private static async Task TestPuppeteerProxy(Uri localProxyUrl)
        {
            var browser = await Puppeteer.LaunchAsync(new PuppeteerSharp.LaunchOptions
            {
                Headless = true,
                Args = new[] { $"--proxy-server={localProxyUrl.Authority}" }
            });

            using var page = await browser.NewPageAsync();
            await page.GoToAsync("https://api.ipify.org/?format=json");
            Console.WriteLine($"Puppeteer:  {await page.QuerySelectorAsync("pre").EvaluateFunctionAsync<string>("e => e.innerText")}");
        }
    }
}
```
