### ISSUE TITLE
Is it possible to disable the password bubble?

### ISSUE THREAD

**Issue by FutureTD** [hardkoded/puppeteer-sharp#1332]
I wanted to remove the info toolbar that says "Chrome is being controlled by automated test software" so I created:

```
                var options = new LaunchOptions
                              {
                                  IgnoredDefaultArgs = new[] { "--enable-automation" },
                                  Headless = false,
                                  Devtools = false,
                                  DefaultViewport = null,
                              };
```
Which worked however removing that flag enables the password bubble.

I was reading on other sites how to disable that and saw:

```
options.AddExcludedArgument("enable-automation");
options.AddAdditionalCapability("useAutomationExtension", false);
options.AddUserProfilePreference("credentials_enable_service", false);
```
Which doesn't not seem possible with puppeteer-sharp, So I was wondering how could I accomplish this?

**Comment by kblok** [comment]
What do you mean with "password bubble"?

**Comment by FutureTD** [comment]
The popup thats asks you if you want to save your password. 

Its seems when you remove the "--enable-automation" flag that gets re-enabled.
