### ISSUE TITLE
just confirm set proxy can not lanuching chrome?

### ISSUE THREAD

**Issue by PccCodesix** [hardkoded/puppeteer-sharp#1351]
### Description
When I set the proxy can not launch the browser. If I unset the proxy can launch the browser.
Whether it is answered as #1202 

### Expected behavior:

WebSocketException: Unable to connect to the remote server

### Versions

version of PuppeteerSharp 2.0.0

**Comment by kblok** [comment]
How are you setting the proxy?

**Comment by PccCodesix** [comment]
> How are you setting the proxy?

at first  set the proxy on the computer Directly but can not lanuching chrome.
Another way set proxy  in code like this also can not lanuching chrome.
but If I unset the proxy can launch the browser
the proxy has no authentication
puppeteer.launch({headless:true, args:['--no-sandbox','--proxy-server=http://ip:port']});

**Comment by kblok** [comment]
Maybe your proxy is messing up with Chrome's websocket connections?

**Comment by PccCodesix** [comment]
> Maybe your proxy is messing up with Chrome's websocket connections?


set proxy I can run the chrome.exe direct successful. looks like no problem with the websocket connections? only can not luanch by  code

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
