### ISSUE TITLE
PuppeteerSharp 2.0 WaitForSelector without function

### ISSUE THREAD

**Issue by LucasMaciuga** [hardkoded/puppeteer-sharp#1352]
Hi everybody,

### Description

I use puppeteer-sharp to render html into pdf - for performance reasons I use WaitForSelector - a JavaScript function inside my html adds a css class during rendering, which I looking for.

PuppeteerSharp 1.19 and 1.20 are working without any issue on local and on server (I always used the chromium version which belongs to the PuppeteerSharp version).
With PuppeteerSharp 2.0 the WaitForSelector is running on my server until timeout is reached (I set it to 300000 for test) - If I use chrome installation on server it fails, too.

On my local machine it runs fine - I can even use my local chrome installation - what I prefere, because pdf generation is significant faster.

I really don't get the point what is wrong, because it throws no exception.

### Complete minimal example reproducing the issue

```csharp
### Browser setup

if (_executablePath == null || !File.Exists(_executablePath))
            {
                var downloadDirectory = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData), ".local-chromium");
                var fetcher = await new BrowserFetcher(new BrowserFetcherOptions
                {
                    Path = downloadDirectory,
                    Platform = Platform.Win64
                }).DownloadAsync(BrowserFetcher.DefaultRevision).ConfigureAwait(false);
                _executablePath = fetcher.ExecutablePath;
            }

            var options = new LaunchOptions
            {
                ExecutablePath = _executablePath,
                Headless = true,
                LogProcess = false,
                UserDataDir = "C:\\ProgramData\\PuppeteerService\\UserData\"",
                IgnoreDefaultArgs = true,
                IgnoredDefaultArgs = new[]
                {
                    "--disable-extensions"
                },
                Args = new[]
                {
                    "--disable-web-security",
                    "--disable-background-networking",
                    "--disable-background-timer-throttling",
                    "--disable-backgrounding-occluded-windows",
                    "--disable-breakpad",
                    "--disable-client-side-phishing-detection",
                    "--disable-default-apps",
                    "--disable-dev-shm-usage",
                    "--disable-extensions",
                    "--disable-features=site-per-process",
                    "--disable-hang-monitor",
                    "--disable-ipc-flooding-protection",
                    "--disable-popup-blocking",
                    "--disable-prompt-on-repost",
                    "--disable-renderer-backgrounding",
                    "--disable-sync",
                    "--disable-translate",
                    "--metrics-recording-only",
                    "--safebrowsing-disable-auto-update",
                    "--mute-audio",
                    "--disable-gpu",
                    "--disk-cache-dir=\"C:\\ProgramData\\PuppeteerService\\Cache\"",
                    "--enable-accelerated-mjpeg-decode",
                    "--enable-accelerated-video",
                    "--enable-gpu-rasterization",
                    "--no-sandbox",
                    "--disable-setuid-sandbox",
                    "--enable-native-gpu-memory-buffers",
                    "--ignore-gpu-blacklist"
                }
            };

### Html to pdf generation

public async Task<byte[]> GeneratePdfStreamAsync(string htmlContent)
        {
            //Beginning pdf generation...
            
            var page = await _browser.NewPageAsync().ConfigureAwait(false);
            //chrome page rented...

            await page.SetContentAsync(htmlContent, new NavigationOptions{ WaitUntil = new [] { WaitUntilNavigation.DOMContentLoaded }} ).ConfigureAwait(false);
            //content set done...
            
            //This will run until Timeout is reached with PuppeteerSharp 2.0
            await page.WaitForSelectorAsync(".renderingDone", new WaitForSelectorOptions{ Timeout = 300000, Visible = true }).ConfigureAwait(false);
            //rendering done...

            var printOptions = new PdfOptions { Format = PaperFormat.A4, PrintBackground = true /*Set to true. Otherwise pictures are not printed*/ };
            var pdfData = await page.PdfDataAsync(printOptions).ConfigureAwait(false);
            //pdf data generation finished...
            
            page.Dispose();
            
            using (var pdfStream = new MemoryStream())
            {
                pdfStream.Write(pdfData, 0, pdfData.Length);
                pdfStream.Position = 0;
                //Pdf generation done.

                return new pdfStream.ToArray();
            }
        }
```

### Expected behavior:

The WaitForSelector should be triggered.

### Actual behavior:

Timeout will be reached without any exception that gives a hint to the problem.

### Versions

OS local: Windows 10 Enterprise 1809
OS Server: Windows Server 2012 
Chrome Version 79.0.3945.79 (Official Build) (64-Bit)
Chromium Version 79.0.3945.0 (Developer-Build) (64-Bit)
.Net Core Version 2.2
PuppeteerSharp Version 2.0

### Additional Information

I connected a logger to puppeteer and on my local machine it looks like this:
![image](https://user-images.githubusercontent.com/8288370/71085523-015f7480-2198-11ea-9388-d0159d91bc59.png)

On the Server instead it does not reach the state "rendering done...":
![image](https://user-images.githubusercontent.com/8288370/71087068-94e67480-219b-11ea-830b-42d129abe199.png)

If any additional information is needed don't hesitate to ask.

Thank you in advance 
Lucas

**Comment by LucasMaciuga** [comment]
I tested PuppeteerShar 1.20 with Chrome Version 79.0.3945.79 (Official Build) (64-Bit).
It does also not work.

**Comment by LucasMaciuga** [comment]
So got now PuppeteerSharp 1.17.2 and Chrome Version 76.0.3809.100 (Offizieller Build) (64-Bit) running on the server as expected.

If someone needs the same setup, don't forget to "disable" the "Google Updater": https://stackoverflow.com/questions/18483087/how-to-disable-google-chrome-auto-update/45064002#45064002

**Comment by kblok** [comment]
Did you try opening the browser in headless false on the server and see if everything looks as expected?

**Comment by RambIing** [comment]
> Did you try opening the browser in headless false on the server and see if everything looks as expected?

Running into same issue here, sorry for the late reply. It goes to 30k timeout even though the selector is there. No Google Updater is present.

**Comment by jzabroski** [comment]
I ran into the same problem. 
In my case, it only happens when I use the code path in WaitForSelectorAsync that injects JavaScript to check if an element is hidden or not.  It seems that once this JavaScript is injected, it seriously slows down the page.

I believe the reason the tests don't catch this is it only repro's on a very, very large page. I am using PuppeteerSharp to write an automated smoke test for SSRS reports, to verify things like the stored procedures still work.

In my case, here is my repro:

```c#
public class SsrsConfiguration
{
    public string HomeUrl {get; set; }
}

using System;
using System.IO;
using System.Threading.Tasks;
using PuppeteerSharp;
using Xunit;
using Xunit.Abstractions;

namespace Tests
{
    public class SsrsTest
    {
        [Theory]
        [InlineData("TopLevel", "SecondLevel", "Example Report")]
        public async Task DoIt(string topLevelFolderName, string secondLevelFolderName, string reportName)
        {
            var ssrsConfig = new SsrsConfiguration { HomeUrl = "http://reporting.simmaculate.com/Reports_DEV/" };
            await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
            using (var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = false,
                Args = new[]
                {
                    /*
                     * You can't access an <iframe> with different origin using JavaScript,
                     * it would be a huge security flaw if you could do it.
                     * For the same-origin policy browsers block scripts trying to access a frame with a different origin.
                     */
                    "--disable-web-security",
                    "--disable-features=IsolateOrigins,site-per-process",
                },
            }))
            {
                var paginatedReportViewerSelection = "#main div.view paginated-report-viewer div.viewerContentContainer div div.frame iframe";
                await page.WaitForSelectorAsync(paginatedReportViewerSelection);

                var iframe = await page.QuerySelectorAsync(paginatedReportViewerSelection);
                var content = await iframe.ContentFrameAsync();
                var reportViewerControlLoaded = await content.WaitForSelectorAsync("#VisibleReportContentReportViewerControl_ctl09");

                var checkLoadingFinished = await content.WaitForSelectorAsync("#ReportViewerControl_AsyncWait_Wait", new WaitForSelectorOptions() { Hidden = true });

                var checkThatTheReportExecuted =
                    await content.WaitForSelectorAsync("td[id$='oReportCell']");

                // Record result.
                var currentDirectory = Environment.CurrentDirectory;
                var filePath = Path.Combine(currentDirectory,
                    $@"{topLevelFolderName}\{secondLevelFolderName}\{reportName}.jpg");
                FileUtils.AssertDirectoryForFilePath(filePath);
                await page.ScreenshotAsync(filePath);
            }
        }
    }
}
```

**Comment by jzabroski** [comment]
I realize you might not be interested in a full repro with SSRS, but if you did, you can get 2008 SSRS AdventureWorks reports here: 
https://github.com/microsoft/Reporting-Services/blob/master/PaginatedReportSamples/

The above link contains several sample reports that do not require a database connection.  They literally just render the report.

However, if you want to simulate a large database, you can use Sample Databases found here: https://github.com/microsoft/sql-server-samples/releases

**Comment by jzabroski** [comment]
Actually, after I restarted Visual Studio, the performance of my tests increased.  But the longer Visual Studio stays open, the longer the tests seem to take.  I suppose it could be a problem with SSRS having some memory leak, but it seems to go away after I restart Visual Studio, and comes back when I run the tests many many times.
