### ISSUE TITLE
Browser.CloseAsync().Wait() hangs when called on the same thread that the browser was created on

### ISSUE THREAD

**Issue by madelson** [hardkoded/puppeteer-sharp#1354]
### Description

`Browser.CloseAsync().Wait()` hangs when called on the same thread that the browser was created on.

### Complete minimal example reproducing the issue

```csharp
var browser = await PuppeteerSharp.Puppeteer.LaunchAsync(new LaunchOptions
{
	Headless = true,
	ExecutablePath = @"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
}).ConfigureAwait(false);

// uncommenting this line fixes the hang
//await Task.Yield();

// hangs forever
browser.CloseAsync().Wait();

// awaiting instead prevents the hang
//await browser.CloseAsync(); 

// not waiting on CloseAsync() prevents the hang. The task does complete with RanToCompletion
//browser.CloseAsync().ContinueWith(t => Console.WriteLine(t.Status));
```

### Expected behavior:

`browser.CloseAsync().Wait();` should return normally.

### Actual behavior:

`browser.CloseAsync().Wait();` hangs forever. Oddly, this can be fixed by awaiting `Task.Yield()` beforehand. 

Some other methods of closing DO work, such as awaiting `browser.CloseAsync()` or not awaiting it at all.

### Versions

* Which version of PuppeteerSharp are you using? 
2.0
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
.NET framework 4.6.1

### Additional Information

While it seems silly to call `browser.CloseAsync().Wait();`, this actually came up in some real and (arguably) reasonable code I was working on.

Basically, the code was wrapping the `Browser` object in another class which implemented `IDisposable`. Because `Dispose()` is synchronous, the `Browser` was being closed synchronously.

The reason for calling `browser.CloseAsync().Wait()` over `browser.Dispose()` is that `Dispose()` does not wait for the close to finish; that means that we won't know if an error happens during close and we can't be sure that the browser process is gone before proceeding. For example, we had a test which was asserting `browser.IsClosed` after disposing the outer object; without waiting on `CloseAsync()` this test was failing.

I've reproduced this in both LinqPad and in an NUnit test.

Now that I have some idea of what is going on I can work around this, but it would be nice to fix it to prevent others from encountering the same thing. I also wonder whether the underlying cause could lead to other issues that I haven't run into yet.

Thanks for your work on this library!

**Comment by kblok** [comment]
I'm afraid there is no way to work around that. In fact, that's why [Browser does a fire and forget on Dispose](https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Browser.cs#L535), because we can't force a wait there.

**Comment by madelson** [comment]
@kblok I dug into this a bit more to try to understand what you meant and I figured out what you probably already know.

The root cause of this is the fact that the `GetResponseAsync` "thread" in WebSocketTransport fires `MessageReceived` events synchronously. 

In the launch case, there ends up being a synchronous flow all the way from `GetResponseAsync` through to the completion of `LaunchAsync`, and as such `browser.CloseAsync().Wait()` ends up executing on the `GetResponseAsync` thread. Therefore, we end up in deadlock because the `GetResponseAsync` loop can no longer go around and receive messages.

I think that this should actually be pretty straightforward to fix. 

For example, one really small change that makes this work is this:
```csharp
// in WebSocketTransport.GetResponseAsync
// MessageReceived?.Invoke(this, new MessageReceivedEventArgs(response.ToString()));
Task.Run(() => MessageReceived?.Invoke(this, new MessageReceivedEventArgs(response.ToString())));
```

By doing fire-and-forget for the event, we ensure that the message handler can't ever deadlock.

What I don't like about this solution is that Task.Run doesn't guarantee ordering so we might end up with events being handled concurrently or out of order. We could enforce order with something like this:
```csharp
// outside the loop
var messageHandlingTask = Task.CompletedTask;

while (!IsClosed)
{
    ...

    messageHandlingTask = messageHandlingTask.ContinueWith(
        _ => MessageReceived?.Invoke(this, new MessageReceivedEventArgs(response.ToString())), 
        TaskContinuationOptions.RunContinuationsAsynchronously);
}
```

Another method of fixing would be to add `await Task.Yield()` to any async void event handlers for `MessageReceived`.

Thoughts? If you would be interested in any of these changes, I'd be happy to file a PR.

If the library had this, then Dispose() wouldn't have to be fire-and-forget anymore which could be nice as well.

**Comment by kblok** [comment]
> For example, one really small change that makes this work is this:
> 
> // in WebSocketTransport.GetResponseAsync
> // MessageReceived?.Invoke(this, new MessageReceivedEventArgs(response.ToString()));
> Task.Run(() => MessageReceived?.Invoke(this, new MessageReceivedEventArgs(response.ToString())));

The problem there is that there are several messages that we need to process in order, and that might break many things.

On the other hand, feel free to play around. PRs are welcome.

**Comment by madelson** [comment]
Thinking about this a bit more, I think this might be related to the slightly-inconsistent behavior around Close/Dispose mentioned in https://github.com/hardkoded/puppeteer-sharp/issues/1456#issuecomment-610607909. I think that if all the public  async operations consistently return a TCS that forces async continuation then we won't be able to get into the state where the continuation thread is also the message handler loop thread.

**Comment by kblok** [comment]
Good point @madelson
