### ISSUE TITLE
Screenshot Image Is Repeated For Long Pages

### ISSUE THREAD

**Issue by DavidGKoch** [hardkoded/puppeteer-sharp#1355]
Hi there,

Love this product!! I'm having an issue taking screen shots of very long pages (e.g. over 8200 pixels). The resulting image starts repeating itself prior to reaching the end of the page. Have you seen this issue and, if so, is there a workaround?

I saw a few mentions of it online but no real solutions. 

Version 2.0.0
.Net Framework 4.6.1
VS 2017
Windows 8.1

**Comment by kblok** [comment]
Hey @DavidGKoch. I've seen a few of those reports, even in Puppeteer. 
The thing is that those kinds of issues should be reported upstream on the chromium repo, there is not much we can control from the library.
