### ISSUE TITLE
browser.NewPageAsync() dies in IIS

### ISSUE THREAD

**Issue by FetchBit** [hardkoded/puppeteer-sharp#1367]
browser.NewPageAsync() dies in IIS.

Windows 10
IIS 10.0.18362.1
Target framework .NET Core 2.2

I have tried with PuppeteerSharp 1.18.0 and up, each with different versions (also latest) of Chromium.

Code to reproducing the issue, PuppeteerSharp 1.18.0 :
```
var browserInfo = await new BrowserFetcher(new BrowserFetcherOptions
            {
                Path = AppDomain.CurrentDomain.BaseDirectory + "Chromium"
            }).DownloadAsync(672088);

            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
                ExecutablePath = browserInfo.ExecutablePath
            });
            
            var page = await browser.NewPageAsync();
```

Expected the page to be returned, but nothing happens.

Running it with IIS Express and it works as intended.

**Comment by kblok** [comment]
Could you try adding the `--no-sandbox` flag?

**Comment by FetchBit** [comment]
With --no-sandbox flag it works as intended. I would prefer not to use this flag though. Any thoughts on the issue? Any other workarounds than using no-sandbox?

```
var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
                ExecutablePath = browserInfo.ExecutablePath,
                Args = new[] {"--no-sandbox" }
            });
```

**Comment by kblok** [comment]
It's an environment issue. Another workaround would be creating an external service and your site talk with that service with some queue.

**Comment by FetchBit** [comment]
Thank you for your help.

Is this something that will be addressed in future versions of Puppeteer-Sharp?

**Comment by kblok** [comment]
@FetchBit It's more a limitation from Chromium. If we send a message from chromium and nothing comes back, there is no much we can do on our end...
