### ISSUE TITLE
How long does it take in general for you to upgrade to the newest Puppeteer (2.1.1)?

### ISSUE THREAD

**Issue by ngiakhanh** [hardkoded/puppeteer-sharp#1449]
Hi @kblok , I just investigating the possibility to use puppeteer-sharp in my project to replace selenium. I just want to ask in general, how long does it take you to catch up with the newest version of Puppeteer ?

**Comment by kblok** [comment]
Hey @ngiakhanh my focus is on https://github.com/kblok/playwright-sharp right now.

I would eventually work on 2.1.1 but I don't think it would be in the first half of 2020 (unless it gets sponsored).
