### ISSUE TITLE
NewPageAsync() hangs on Ubuntu Server 18 (x64)

### ISSUE THREAD

**Issue by heppth** [hardkoded/puppeteer-sharp#1451]
### Description

The method call NewPageAsync() hangs on Ubuntu Server 18.04.1 LTS. On Windows it is working very well. I used the PuppeteerSharpPdfDemo for easier reproducing.

The console shows
```
Downloading chromium
Navigating google
```
and then it hangs.

In lsof I can see that the chrome process is running:
```
chrome    30966          thomas  153u  IPv4 151469      0t0  TCP 127.0.0.1:44037 (LISTEN)
```

### Complete minimal example reproducing the issue

1. Simply use the [PDF demo](https://github.com/kblok/puppeteer-sharp/tree/master/demos/PuppeteerSharpPdfDemo)
2. Publish to ubuntu server (Release / netcoreapp3.1 / linux-x64)
3. Run published application on linux

### Expected behavior:

Demo application should create PDF on linux system (just like it works under windows)

### Actual behavior:

Program hangs forever

### Versions

Tested with version 2.0.0 and version 2.0.2 (same behaviour)
Targeting .net core 3.1

### Additional Information

I love this library. I hope it will run on Linux soon. thank you for your help

**Comment by kblok** [comment]
reproduced.

**Comment by ThaDaVos** [comment]
Any fix? Running into the same on my local Ubuntu instance (inside WSL 2)

**Comment by kblok** [comment]
@ThaDaVos I'll take a look during the weekend.

**Comment by ThaDaVos** [comment]
That would be great! Thank you!

Was already looking at your Playwright port - maybe that's a better option?

**Comment by kblok** [comment]
@ThaDaVos it depends on your deadlines. It will take us a few months to get to a version we can ship.

**Comment by ThaDaVos** [comment]
For playwright or for the fix in the puppeteer-sharp?

**Comment by kblok** [comment]
hahaha for Playwright :)

**Comment by ThaDaVos** [comment]
Is it usable yet? I would love to try it, I only need screenshot capability as I'm going to try to create a video stream from the headless browser

**Comment by kblok** [comment]
@ThaDaVos I would start with puppeteer. The migration process from Puppeteer to Playwright won't be that hard.

**Comment by ThaDaVos** [comment]
So,
1. Wait for the fix in puppeteer-sharp
2. Use the nodejs versions as current environment to test and later migrate to C# version
3. Mess around in the Playwright port

**Comment by kblok** [comment]
If you want to mess around with Playwright. I could give priority to the screenshots feature so you can play with it, but downloading the source code, I won't ship to nugget yet.

**Comment by ThaDaVos** [comment]
That would be amazing as Playwright looks like the future to me!

Can you give an estimation on the ETA?
I'll just use the NodeJs version in the meantime

**Comment by kblok** [comment]
We can push screenshots early next week.

**Comment by ThaDaVos** [comment]
That would be great! I would love to help with testing the features!

**Comment by ThaDaVos** [comment]
I think I found out the issue...

Check your env's value of: `printenv | grep DISPLAY`
Is it accessible?

**Comment by ThaDaVos** [comment]
Starting my x-server (runs inside windows) solved the issue for me, it's screenshotting now

**Comment by ThaDaVos** [comment]
So @heppth is there an x-server available on your Ubuntu Server and is the ENV set correctly?

**Comment by kblok** [comment]
Thank you for your time @ThaDaVos. I'm honestly not proficient in Linux.

**Comment by ThaDaVos** [comment]
I noticed it because my NodeJS playwright kept hanging too 😂

**Comment by heppth** [comment]
> So @heppth is there an x-server available on your Ubuntu Server and is the ENV set correctly?

No there isn't a x-server available. I didn't know that this is required.

**Comment by kblok** [comment]
@ThaDaVos feel free to add that in the prerequisites section on the readme ;)

**Comment by ThaDaVos** [comment]
> 
> 
> > So @heppth is there an x-server available on your Ubuntu Server and is the ENV set correctly?
> 
> No there isn't a x-server available. I didn't know that this is required.

An x-server is needed to start the browser - or else the browser will hang

**Comment by ThaDaVos** [comment]
Or something that at least can accept the draw calls :joy:

**Comment by ThaDaVos** [comment]
I'll try @kblok

**Comment by ThaDaVos** [comment]
Like this: https://github.com/hardkoded/puppeteer-sharp/pull/1459
