### ISSUE TITLE
finding an element in an iframe

### ISSUE THREAD

**Issue by mcopur** [hardkoded/puppeteer-sharp#1453]
I tried to find a div ("div.vjs-poster") in https://www.npostart.nl/oogappels/05-03-2020/BV_101396179
First I tried the standard await page.QuerySelectorAsync("div.vjs-poster") but I got null and then I realized that it is in a frame I tried to get that element by using that code block:

```
 await page.WaitForSelectorAsync("iframe");

  var elementHandle = await page.QuerySelectorAsync("iframe");

  var frame = await elementHandle.ContentFrameAsync();

  await frame.WaitForSelectorAsync(selector);

  var preview = await frame.QuerySelectorAsync(selector);

  if (preview != null)
  {
         await preview .ClickAsync();
  }

```
but executing **await elementHandle.ContentFrameAsync();**  throws an exception as "**Frame B8F771E2CB61CBF0C1EB16A440321C25 not found"** 
This frame is actually in the page and I checked the elementHandle which is set in the previous row is not null. What is this issues's solution or how can I get element? Please help.

**Comment by Cuiqs76** [comment]
Is the problem solved? I also came across a button in iframe @mcopur

**Comment by kblok** [comment]
@mcopur your code is working for me, could you share the stack trace?

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.

**Comment by namilkimfree** [comment]
@kblok 
i same issue, 7.0.0

exception:   Frame 8B6EB85116EFEB0ABBEFC65625234E35 not found

page url: https://forum.netmarble.com/enn_ko/view/33/132235

  var elementHandle = await page.QuerySelectorAsync("#contentsDetail iframe");

  var frame = await elementHandle.ContentFrameAsync();   --> throw exception
