### ISSUE TITLE
About Auto Login by default account and pwd in chrome setting.

### ISSUE THREAD

**Issue by Waha-Liu88** [hardkoded/puppeteer-sharp#1454]
how to closed the "Auto Login" Button in the chrome setting.By default, the chrome is open when strart up?.So, puppeteer how to closed it using the code.

**Comment by kblok** [comment]
@Waha-Liu88 I don't get the question, could you clarify a little bit more?

**Comment by Waha-Liu88** [comment]
@kblok chrome setting->"auto fill" the first section "password"->the second section "auto login" the button is open by default.So, I want to close it when I launch the browser.Because it is opened by default.
