### ISSUE TITLE
Windows binaries compiled with "is_multi_dll_chrome", no support for "--single-process"

### ISSUE THREAD

**Issue by danielgindi** [hardkoded/puppeteer-sharp#1455]
### Description

`"--single-process is not supported in chrome multiple dll browser"`

Chromium won't start with `--single-process` flag, due to it being disallowed when compiled with [`is_multi_dll_chrome`](https://chromium.googlesource.com/chromium/src.git/+/master/docs/windows_split_dll.md) flag.

Is there a reason for the binaries compiled in this manner?

Thanks

**Comment by kblok** [comment]
We are using the same repository Puppeteer uses. You could try downloading a browser with that build and use `ExecutablePath`

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
