### ISSUE TITLE
When Converted Html to Pdf document, linked css not rendered.

### ISSUE THREAD

**Issue by mertmtn** [hardkoded/puppeteer-sharp#1462]
I want to create a report which has data from web services, charts, tables, pictures. While converting html to pdf, scripts works but css not rendered.

We have an application works .net framework and MVC pattern. 

Css Path are located below.

`<link href="~/Rapor/SablonCss/FONRAPOR" rel="stylesheet" /> 
`This comes from databese because styles inserted on db. Rapor is a controller name, SablonCss is an action name.

But if we located as css file at physical directory, it works. Hovewer if we will change css code on database, it should be worked. Not take from physical path. 

Physical Located File Path

```
<link href="~/Content/MasterSablon.css?ver=1.0.4" rel="stylesheet" />
<link href="~/Content/Sablon.css?ver=1.0.4" rel="stylesheet" />
```

By the way Chromium works as headless = false, because of an our web service's process.

Expected Result 
[Önizleme (6).pdf](https://github.com/hardkoded/puppeteer-sharp/files/4496253/Onizleme.6.pdf)

Actual Result
[22952_HKV_17042020_sirketbulteni.pdf](https://github.com/hardkoded/puppeteer-sharp/files/4496251/22952_HKV_17042020_sirketbulteni.pdf)

How to solve this issue?

**Comment by mertmtn** [comment]
Also I added css and html code. I did not found any solution.


[sabloncss.txt](https://github.com/hardkoded/puppeteer-sharp/files/4499129/sabloncss.txt)
[sablonhtml.txt](https://github.com/hardkoded/puppeteer-sharp/files/4499130/sablonhtml.txt)

**Comment by kblok** [comment]
If you browse the site with a browser, do you see the expected result?
How does the site look like when you see the browser in headless false open up?

**Comment by mertmtn** [comment]
My expected result is below image which comes from a link. By the way, we have a cookie method to login our application.

![image](https://user-images.githubusercontent.com/37337606/79751533-6b8d4f00-831b-11ea-96ca-208c13a84fd6.png)

**Comment by kblok** [comment]
It looks like a media print issue. Did you try generating a PDF from the same URL?

**Comment by mertmtn** [comment]
I generated pdf from the url but result was below pdf 
[22952_HKV_17042020_sirketbulteni (2).pdf](https://github.com/hardkoded/puppeteer-sharp/files/4503628/22952_HKV_17042020_sirketbulteni.2.pdf)

excepted pdf should be this one which created our automation's interface. Converted pdf is generated by our web service

[Onizleme.6 (2).pdf](https://github.com/hardkoded/puppeteer-sharp/files/4503631/Onizleme.6.2.pdf)

**Comment by kblok** [comment]
Export to PDF en Puppeteer works as a print. It does the same as `File => Print => Save as PDF`.

So [CSS @media print](https://developer.mozilla.org/en-US/docs/Web/CSS/@media) is used. You would need to edit the CSS so it "prints" the page in the way you expect.

**Comment by mertmtn** [comment]
@media print did not worked for me, because pdf page size changed also css layout change. 
I add all css code between @media print{ }

**Comment by kblok** [comment]
@mertmtn could you try setting `PrintBackground` to true?

**Comment by mertmtn** [comment]
I tried to set **PrintBackground** to true as a pdf options and works it. Thanks for your help...

**Comment by rgeromegnace** [comment]
Hello,

I have the same problem in version 7. PuppeteerSharp seems not reading bootstrap css in html tag <link rel ...>

**Comment by rgeromegnace** [comment]
It seems to come from the presence of @media tag in my default css file.
