### ISSUE TITLE
IDE0008 in VS 2019, csharp_style_var_for_built_in_types?

### ISSUE THREAD

**Issue by undefinedfunction** [hardkoded/puppeteer-sharp#1464]
**Before you file a bug, have you:**

* Tried upgrading to newest version of PuppeteerSharp, to see if your issue has already been resolved and released?
* Checked existing open *and* closed [issues](https://github.com/kblok/puppeteer-sharp/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* Tried reproducing your problem in a new isolated project?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/search?q=puppeteer-sharp).

### Description

In #1463 I mentioned about IDE0008 which stems from `lib/.editorconfig`. I thought I'd move on to the next one of the many similar issues (been looking for an OS project to invest in and I have a interest in automated browsers hence being here).

Originally IDE0008 only came in BrowserFetcher.cs but now it comes in the other files (IDE errors only seem to show if the file is open, which makes sense). 

So this is making me think that either `lib/.editorconfig` is wrong or my VS configuration is wrong. I'm assuming the later, but I don't know what. 

If I change set `csharp_style_var_for_built_in_types` to `false:none` instead of `false:error`, IDE0008 disappears. 

Code style preferences is untouched: 
<img width="842" alt="image" src="https://user-images.githubusercontent.com/15334/80538988-8fe1cf00-899e-11ea-8ae0-ea3bab632fcd.png">

Is there something I've missed? 

Thanks! 

### Complete minimal example reproducing the issue

Checkout code and open in VS2019

### Expected behavior:

No compile errors

### Actual behavior:

IDE0008 errors in an open CS file:

<img width="991" alt="image" src="https://user-images.githubusercontent.com/15334/80539744-f4e9f480-899f-11ea-8f08-2962cbfd733b.png">

### Versions

* Which version of PuppeteerSharp are you using?
Master

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
netstandard2.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by kblok** [comment]
As you can see, you jumped into a mini-project about improving this project code quality.
Doing all that at once was going to be a huge impact.
.editorconfig has an interesting behavior on VS, it would only enforce those rules on the files you are editing.
Editor config rules are not hard to fix, so I could buy if new PRs come some changes in code to make editorconfig happy.

**Comment by undefinedfunction** [comment]
Ok, I didn’t see any mention of IDE0008 being expected but if you are saying editorconfig is valid, then it makes sense to me. The use of `var` should be corrected as editorconfig defines.

As It was unexpected to me I didn’t want to create more problems if there was some issue in editorconfig so just looking for clarity.
