### ISSUE TITLE
Different results in Chrome's F12 and CDP

### ISSUE THREAD

**Issue by MilnerAlex** [hardkoded/puppeteer-sharp#1465]
The page https://www.bbc.co.uk/iplayer/live/bbcone
I can query element “div.p_playerControls”  in Chrome's F12 console: 

document.querySelector('div.p_playerControls')
div class=​"p_playerControls" style=​"display:​ block;​ clip:​ rect(1px, 1px, 1px, 1px)​;​"

...but cannot via remote interface (div is null, please see attached image):

var div = await page.QuerySelectorAsync("div.p_playerControls");
var player = await page.QuerySelectorAsync(".player__container");

Am I do something wrong?.. :) Thanks!

![player2_2](https://user-images.githubusercontent.com/64533605/80594280-c4ec3100-8a33-11ea-8fc5-f681c70231b4.jpg)

**Comment by kblok** [comment]
Did you try adding a `WaitForSelectorAsync` before that?

**Comment by MilnerAlex** [comment]
Just tried it, just freeze on wait. The page persistent opened in Chrome! I can switch to Chrome and document.querySelector return element OK...

await page.WaitForSelectorAsync("div.p_playerControls");
var div = await page.QuerySelectorAsync("div.p_playerControls");

**Comment by kblok** [comment]
I'm getting a login wall on that page.

![image](https://user-images.githubusercontent.com/2198466/80595158-aa499600-89fa-11ea-8852-e3cc6752c2ce.png)

**Comment by MilnerAlex** [comment]
Just signup, it's free :) Then you will need select "I have license for watch TV". You will not able see TV if you not in UK, but you will able see "div_p_payerControls" in F12. 
If you will have some ideas, what's going wrong, it will very valuable for me :) Thanks!

**Comment by kblok** [comment]
Are you signing up and selecting "I have license for watch TV" using Puppeteer sharp?

**Comment by MilnerAlex** [comment]
No of course, I'm signup in browser. Browser then store login in cookies, and I can re-run Chrome in dev mode.

**Comment by kblok** [comment]
@MilnerAlex are you launching puppeteer passing the `ExecutablePath` option targeting to the browser you used to log in?

**Comment by MilnerAlex** [comment]
No, I'm use connecting to running instance (for keep page unchanged):
                var coptions = new ConnectOptions
                {
                    AppMode = true,
                    BrowserURL = "http://localhost:9222"
                };
                var browser = await Puppeteer.ConnectAsync(coptions);

**Comment by kblok** [comment]
Can't test that

![image](https://user-images.githubusercontent.com/2198466/80597553-635d9f80-89fe-11ea-9121-6222d70a8878.png)

**Comment by MilnerAlex** [comment]
Hi Dario,

 Yes, as I mentioned, you will not able see TV :) But you WILL be able retrieve div as below:

![image](https://user-images.githubusercontent.com/64533605/80597924-9ec98f80-8a39-11ea-8c2b-13ae969ea5bc.png)

Thanks!

Alex.

**Comment by MilnerAlex** [comment]
I'm just got a point in another thread that it can be related to frame, please see here: 

https://github.com/cyrus-and/chrome-remote-interface/issues/415

I will investigate it now, but maybe you already know), how to get access to this frame?..  Thanks! :)

**Comment by kblok** [comment]
That DIV is inside an `iframe`.  You would need to get the frame first and then query inside the frame.

![image](https://user-images.githubusercontent.com/2198466/80599556-8047a200-8a01-11ea-87cc-b489902fc9f3.png)

**Comment by MilnerAlex** [comment]
Thanks Dario, I will start digging in this way :) Can you please do not close this issue for a while, I'll close tomorrow myself - thanks!

**Comment by kblok** [comment]
You could infer the frame based on the URL :)

```cs
var frame Page.Frames.First(f => f.Url.Contains("iframe.html")
```

**Comment by MilnerAlex** [comment]
I'll try it tomorrow! Thanks a lot again! :)

**Comment by MilnerAlex** [comment]
The problem is solved (get frames and query on each). Thanks a lot Dario! :)
