### ISSUE TITLE
Unable to get application working if it is .Net Core 3.X

### ISSUE THREAD

**Issue by Telavian** [hardkoded/puppeteer-sharp#1467]
### Description

I am receiving this error when trying to use Puppeteer-Sharp in .Net Core 3.X.

`The server returned status code '403' when status code '101' was expected.`

It seems however if the application is .Net core 2.X then it works correctly.
The error appears to be when trying to create a websocket connection to the browser.
I am honestly not sure how websockets act different between .Net Core versions.

I have tried using the launcher and a local version of chrome and edge with the same results.

### Complete minimal example reproducing the issue

Run PuppeteerSharpPdfDemo as .Net core 2.2 -- Works!
Run PuppeteerSharpPdfDemo as .Net core 3.0 -- Fails

### Expected behavior:

Should work on .Net core 3.X

### Actual behavior:

Doesn't work on .Net Core 3.X

### Versions

* Which version of PuppeteerSharp are you using?
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.

**Comment by kblok** [comment]
It's working here @Telavian 

![image](https://user-images.githubusercontent.com/2198466/81060018-0489a180-8ea8-11ea-819f-1b04564647ad.png)

![image](https://user-images.githubusercontent.com/2198466/81060076-1d925280-8ea8-11ea-9865-ada885d4d483.png)

**Comment by Telavian** [comment]
I believe the default proxy settings changed between .Net Core versions.
If I set the default proxy on the WebSocket to null then it seems to work.

Strange that simple things can require so much work to finally figure out.

**Comment by jzabroski** [comment]
> Strange that simple things can require so much work to finally figure out.

Just be thankful you aren't debugging an AngularJS application with 6000 node_modules on the backend.  (If you want this alternative, I can hook you up with people who work at Capital One...)
