### ISSUE TITLE
Add option to run Puppeteer with different browsers

### ISSUE THREAD

**Issue by kblok** [hardkoded/puppeteer-sharp#1471]
https://github.com/kblok/puppeteer/pull/20/commits/c5a72e9887098671c3c940e86e181e3f90f1294f

**Comment by fgiuliani** [comment]
@kblok can I work on this issue?

**Comment by Meir017** [comment]
the firefox version of puppeteer-sharp isn't implemented yet

**Comment by kblok** [comment]
He will work on that @Meir017  ;)
