### ISSUE TITLE
Safe way to find out whether Chromium is downloaded?

### ISSUE THREAD

**Issue by miakh** [hardkoded/puppeteer-sharp#1486]
From what I see, there is only possible via handling exception. It is for scenario, in which not finding executable is continued by downloading Chromium via BrowserFetcher. Is there a way to say whether Chromium is already downloaded?

```csharp
            try
            {
                executableLocalPath = Puppeteer.GetExecutablePath();
            }
            catch (Exception e)
            {
                // Executable not found
            }
```

I would expect something like

```csharp
             bool executableExist = Puppeteer.ExecutableExist();
```

**Comment by kblok** [comment]
@miakh `BrowserFetcher.DownloadAsync` is supposed to download chromium only if chromium it's not on the destination path.

**Comment by miakh** [comment]
It seems as if `Puppeteer.GetExecutablePath` is resolved based on `PUPPETEER_EXECUTABLE_PATH` environment variable. So you might still get executable from different Puppeteer-sharp based project this way.

**Comment by kblok** [comment]
@miakh do you have some code for me to test?

**Comment by miakh** [comment]
@kblok It's not a bug. It's just not behaving way I supposed before I looked into it.
E.g. if I understand it correctly once `BrowserFetcher.DefaultRevision` will change then `BrowserFetcher.DownloadAsync` downloads new version (leaving possible cleaning of older to user). Same for `Puppeteer.GetExecutablePath` (if env variables are not set). Also `Puppeteer.GetExecutablePath` won't take just any already downloaded revison, but one defined by `BrowserFetcher.DefaultRevision`.

**Comment by kblok** [comment]
You could also do something like this `BrowserFetch.RevisionInfo(yourRevision).FolderPath and check that.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
