### ISSUE TITLE
Simple example of a MVC controller returning a PDF from action

### ISSUE THREAD

**Issue by JoopStringer** [hardkoded/puppeteer-sharp#1488]
Is there an example available how to use puppeteer-sharp in a C# MVC ASP.NET controller to return a PDF from an action?

Something like:
```
public FileContentResult GetPdfFromThisAction(){
   .... code here
   return PdfResult;
}
```

**Comment by kblok** [comment]
@ironman1964 how about this https://github.com/kblok/netconfar-puppeteer-sharp-demo/blob/master/hacking-the-browser-api/Controllers/MediumController.cs#L13 ?

**Comment by ironman1964** [comment]
Dario, that one is calling "just" an external page and returns a PDF
What I'm looking for is returning the actions-view in PDF
But will try it out later today ...

**Comment by kblok** [comment]
@ironman1964 got it.
I would love to see that. I created an issue there, but I got no answer https://github.com/webgio/Rotativa.AspNetCore/issues/27

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
