### ISSUE TITLE
process can't exit 

### ISSUE THREAD

**Issue by mxwdxypage** [hardkoded/puppeteer-sharp#1493]
environment:
windows server 2012 r2  ,iis  InProcess Mode .net core 2.2.103
when site start ,it create 4 process
![image](https://user-images.githubusercontent.com/7288511/83322631-ef781680-a28b-11ea-9f49-d5388b58771c.png)
when site stop these process can't exit

but when i change to OutOfProcess Mode 
these process can exit normally

**Comment by kblok** [comment]
@mxwdxypage if you don't dispose the browser explicitly, there is no guarantee that the processes will be killed by the IIS.

**Comment by mxwdxypage** [comment]
`aft.ApplicationStopped.Register(() =>
            {
                LogHelper.WriteInfo(GetType(), "Stopped  " + DateTime.Now);
                try
                {
                    var browser = ServiceLocator.Instance.GetService<Browser>();
                    if (browser != null)
                    {
                        browser.CloseAsync().Wait();
                        LogHelper.WriteInfo(GetType(), "Puppeteer closed");
                    }
                }
                catch (Exception ex)
                {
                    LogHelper.WriteError(GetType(), ex);
                }
            });`

@kblok  thank you the question solved
