### ISSUE TITLE
Evaluation failed "Uncaught (in promise)" - Loading script failed (URL)

### ISSUE THREAD

**Issue by sseyalioglu** [hardkoded/puppeteer-sharp#1495]
### Description

We inject self hosted URL as script to the page and 99% it works but we have one case, which we don't know why it fails.
URL looks like this: http://localhost:5011/js/be/somenamehere/script.js and it is close to 7500 lines.

We see the following:
![image](https://user-images.githubusercontent.com/2631639/83432342-91fbdb00-a3ed-11ea-8453-1f1fa6da615d.png)
In here:
![image](https://user-images.githubusercontent.com/2631639/83432371-9cb67000-a3ed-11ea-8951-071003ab0183.png)
The URL we experience is 112 chars long (including http).

In general here is the exception
PuppeteerSharp.EvaluationFailedException: Evaluation failed: Event
   at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args)
   at PuppeteerSharp.ExecutionContext.EvaluateFunctionHandleAsync(String script, Object[] args)
   at PuppeteerSharp.DOMWorld.<AddScriptTagAsync>g__AddScriptTagPrivate|29_0(String script, String urlOrContent, String type)
   at PuppeteerSharp.DOMWorld.AddScriptTagAsync(AddTagOptions options)

### Complete minimal example reproducing the issue

Here is how we run this:

            var chromiumLaunchOptions = new LaunchOptions
                                        {
                                            Headless       = false,
                                            Devtools       = TRUE,
                                            LogProcess     = true,
                                            Timeout        = 600000
                                        };

var browser = await Puppeteer.LaunchAsync(chromiumLaunchOptions);
var page    = await browser.NewPageAsync();
await  page.AddScriptTagAsync(new AddTagOptions {Url = scriptHostedLocalPath});

### Expected behavior:

script to inject

### Actual behavior:

exception

### Versions

PuppeteerSharp 2.0.3
.NET Core 3.1
MacOs or Ubuntu

**Comment by sseyalioglu** [comment]
Corrected launch scenario
var chromiumLaunchOptions = new LaunchOptions
                                    {
                                        Headless       = false,
                                        Devtools       = TRUE,
                                        LogProcess     = true,
                                        Timeout        = 600000
                                    };
var browser = await Puppeteer.LaunchAsync(chromiumLaunchOptions);
var page = await browser.NewPageAsync();
await page.GoToAsync(url, new NavigationOptions {Timeout = 60000, WaitUntil = new[] {WaitUntilNavigation.DOMContentLoaded}});
await page.AddScriptTagAsync(new AddTagOptions {Url = scriptHostedLocalPath});

**Comment by sseyalioglu** [comment]
I found the issue leading to this.
Once I change the URL that starts the process in page.GoToAsync to shorter one "https://www.google.com/", injection worked.

So somehow we have an issue with long URL paths but I really need that long path, no other choice.

**Comment by sseyalioglu** [comment]
Correction here once again. It is not about the length of the URL but the page content.
Page content is making script injection fail. All other long URLs also work.
So far: The script itself is fine, long url is fine. But somethingin in the page fails this.

**Comment by sseyalioglu** [comment]
Here is the almost final verdict:
If page has appdynamics, then we have this issue.
![image](https://user-images.githubusercontent.com/2631639/83444017-929d6d00-a3ff-11ea-8d7b-7678b1db6b1d.png)

Looking a way to block that content completely to bypass the issue.

**Comment by sseyalioglu** [comment]
Here is the final verdict:
While adding script to the page with the following content
```
   async function addScriptUrl(url, type) {
              const script = document.createElement('script');
              script.src = url;
              if(type)
                script.type = type;
              const promise = new Promise((res, rej) => {
                script.onload = res;
                script.onerror = rej;
              });
              document.head.appendChild(script);
              await promise;
              return script;
            }
```

We get the exception.

Adding the following piece of code, solved all my problems:
```
            await page.SetRequestInterceptionAsync(true);
            var blockDomains = new[] {"adobedtm.com", "ds-aksb-a.akamaihd.net", "ensighten.com", "go-mpulse.net", "appdynamics.com"};
            page.Request += async (sender, args) =>
                            {
                                if (blockDomains.Any(d => args.Request.Url.Contains(d)))
                                    await args.Request.AbortAsync();
                                else
                                    await args.Request.ContinueAsync();
                            };
```

**Comment by kblok** [comment]
@sseyalioglu what I think is that the script being injected is failing, and you are getting the javascript result of that. With that request filter, you might prevent the failing script from being loaded.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
