### ISSUE TITLE
Improve docfx_project/examples/Page.WaitForSelectorAsync.Searching.md

### ISSUE THREAD

**Issue by trentet** [hardkoded/puppeteer-sharp#1497]
Examples of more types of selectors would be appreciated.

For example, I can get #status_info to work for identifying a div that has an id of 'status_info', but I want to be able to take it further and make it so it returns true only when the innerText of the div includes specific text. I can get this to work in the Chrome console, but not with the Page.WaitForSelectorAsync method. Been searching for quite awhile and been unable to find much documentation for this kind of scenario.

**Comment by kblok** [comment]
@trentet could you share the code you used in the chrome console?

**Comment by trentet** [comment]
I have made some adjustments since posting this, but this is the Chrome console command that returns true if the desired element exists: document.queryselector('#status_info').innerText.match('^Showing ([1-9][0-9]*?) to ([1-9][0-9]*?)') of ([1-9][0-9]*?) entries') != null

What is the best way to wait for a Page to load until this returns true, with a timeout parameter? I have a convoluted workaround in place but its definitely way more complicated than I would expect.

**Comment by kblok** [comment]
You can user [WaitForFunctionAsync](http://www.puppeteersharp.com/api/PuppeteerSharp.Page.html#PuppeteerSharp_Page_WaitForFunctionAsync_System_String_PuppeteerSharp_WaitForFunctionOptions_System_Object___).

```cs
var waitTask = Page.WaitForFunctionAsync("() => document.queryselector('#status_info').innerText.match('^Showing ([1-9][0-9]*?) to ([1-9][0-9]*?)') of ([1-9][0-9]*?) entries') != null");
```
