### ISSUE TITLE
Chromium DefaultRevision of PuppeteerSharp 2.0.3 not working on Windows

### ISSUE THREAD

**Issue by blafa** [hardkoded/puppeteer-sharp#1499]
Hi
The DefaultRevision (706915) of the newest PuppeteerSharp 2.0.3 doesnt work on Windows Machine.

PuppeteerSharp throws:
PuppeteerSharp.ChromiumProcessException: 'Failed to launch Chromium! '

Starting chrome.exe manually from Folder downloaded by PuppeteerSharp doesn't start chromium too.
Manually download Chromium (Revision 706915) from https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/ and starting doesn't work also. 

Seems to be an Issue with this Revision. When is it planned to update revision?

**Comment by kblok** [comment]
I just tested 2.0.3 both on windows and on Mac, and it downloaded the revision 706915.

**Comment by blafa** [comment]
And you can start it without Problems? From a .net Core 3.0 Console-Application?

**Comment by kblok** [comment]
I just updated the demo project to 3.1 and it seems to be working https://ci.appveyor.com/project/kblok/puppeteer-sharp-0c8w9/builds/33484403/job/bp8dqmavu8tsqffr

**Comment by blafa** [comment]
Ok, not working on my Machine. Maybe its the windows version. What version (or build) do you have on your machine?

**Comment by kblok** [comment]
Windows 10 is my local, AppVeyor's VM is Windows Server 2019.
The latest version (not implemented on Puppeteer-Sharp) is 756035. You could try calling DownloadAsync using that revision. But it seems it's something on your local env.

**Comment by blafa** [comment]
yes could be my local env. Its strange thats only this specific version. with version from PuppeteerSharp 1.20 its working...

**Comment by blafa** [comment]
It's kind of strange. The next working Version is 756145.

**Comment by kblok** [comment]
Can you try setting the revision of v1.20?

**Comment by blafa** [comment]
![image](https://user-images.githubusercontent.com/36913028/84508294-5b15a700-acc2-11ea-91c2-123ee3b7e964.png)
downloaded...

![image](https://user-images.githubusercontent.com/36913028/84508260-505b1200-acc2-11ea-8c68-008c93fdf053.png)
but crashes :(

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
