### ISSUE TITLE
ChromiumProcessException: Failed to launch Chromium!

### ISSUE THREAD

**Issue by DevGenesis95** [hardkoded/puppeteer-sharp#1502]
### Description

When running the function in AWS lambda getting this exception.

{
    "ClassName": "PuppeteerSharp.ChromiumProcessException",
    "Message": "Failed to launch Chromium! ",
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at PuppeteerSharp.ChromiumProcess.State.StartingState.StartCoreAsync(ChromiumProcess p)\n   at PuppeteerSharp.ChromiumProcess.State.StartingState.StartCoreAsync(ChromiumProcess p)\n   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)\n   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)\n   at ConvertorHelpers.PdfConvertor.ConvertToPdf2(String url, String fileName, String filePath) in ConvertorHelpers\\PdfConvertor.cs:line 107",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2146233088,
    "Source": "System.Private.CoreLib",
    "WatsonBuckets": null
}

### Complete minimal example reproducing the issue

The executable path which is formed in lambda function after fetching the browser is 
"/tmp/chromium/Linux-706915/chrome-linux/chrome"

E.g.

```csharp
// Arrange
 var options = new LaunchOptions
                {
                    ExecutablePath = executablePath,     
                    Headless = true,
                    Devtools = false,
                    LogProcess = true,
                    Args = new[] { "--no-sandbox" }
                };

var chromiumRevision = BrowserFetcher.DefaultRevision;
  using (var browser = await Puppeteer.LaunchAsync(options)) // Exception line 107

// Act
...

// Assert
...
```

### Expected behavior:

launch and convert HTML to PDF

### Actual behavior:

Crasehs

### Versions

* Which version of PuppeteerSharp are you using?
  -- 2.0.3
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
 -- .Net core 2.1 in AWS lambda

### Additional Information

Its working fine when m executing it locally i.e. on my PC(windows) but on lambda function when running on Linux getting the error.

**Comment by kblok** [comment]
Hey @DevGenesis95 can you take a look at this https://github.com/litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet and see if that helps?

**Comment by DevGenesis95** [comment]
Thanks for the reply @kblok but I have tried that too but unfortunately it is not compiling with my lambda which is in .net core 2.1 as mentioned in the repo. Apart from that, I have tried to execute all the permission through my code but yet the issue still persists.


                var fileInfoexec = new UnixFileInfo(executablePath);
                fileInfoexec.FileAccessPermissions = FileAccessPermissions.AllPermissions |
                                                 FileAccessPermissions.AllPermissions;

**Comment by kblok** [comment]
@DevGenesis95 I think it's not only about a permission fix but which is the chromium-browser AWS supports, see https://github.com/alixaxel/chrome-aws-lambda/tree/master/bin

**Comment by DevGenesis95** [comment]
Umm Actually I don't know much about node js..are you taking about the browser revisions? Is that the issue.

**Comment by kblok** [comment]
It seems AWS won't be able to run a normal chromium release. Those 2 libraries are downloading another chromium version there.

**Comment by DevGenesis95** [comment]
The nuget used is PuppeteerSharp version 2.0.3 and the Browserfetcher.DefaultRevision = 706915.
Should I degrade the puppeteer version? Any suggestion about what should I do. It would be really appreciated :)

**Comment by kblok** [comment]
I created this issue https://github.com/litmus/HeadlessChromium.Puppeteer.Lambda.Dotnet/issues/49 :)

**Comment by DevGenesis95** [comment]
Thanks for the help 👍

**Comment by DevGenesis95** [comment]
Yes,
![PuppeteerError](https://user-images.githubusercontent.com/34500301/85053973-fc1bca80-b1b8-11ea-95b5-8e333c4796ef.png)
 I  have downgraded the Pupeeter NuGet package to 1.14.1 which uses the DefaultRevision = 641577 but still, the error persists. Attaching cloudwatch screenshot for this

**Comment by brianfeucht** [comment]
@DevGenesis95 `HeadlessChromium.Puppeteer.Lambda.Dotnet` build `1.0.1.39` is `chromium 756035 (83.0.4103.0)`

I am running this with `PuppeteerSharp` build `2.0.3` on Lambda .NET 3.1.  It should work with Lambda .NET 2.1 but I haven't verified that myself.  Would you be willing to try that combo?

**Comment by DevGenesis95** [comment]
Thanks for the info actually I can go with .Net 3.1 if that's working. No, it's not working in 2.1 for me. Can you give me a solution where you have integrated it 3.1 lambda that would be really helpful :)

**Comment by brianfeucht** [comment]
Our project files looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
	<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="aws-lambda-tools-defaults.json" />
    <Content Include="aws-lambda-tools-defaults.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="PuppeteerSharp" Version="2.0.3" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.2.0" />
    <PackageReference Include="HeadlessChromium.Puppeteer.Lambda.Dotnet" Version="1.0.1.39" />
  </ItemGroup>
</Project>
```

The `aws-lambda-tools-default.json` file looks like:
```
{
  "configuration" : "Release",
  "framework" : "netcoreapp3.1",
  "function-runtime":"dotnetcore3.1",
  "function-memory-size" : 1536,
  "function-timeout" : 60,
  "function-handler" : "Lambda::LambdaHandler::Handle"
}
```

We deploy following a process similar to this:
https://aws.amazon.com/premiumsupport/knowledge-center/build-lambda-deployment-dotnet/

**Comment by DevGenesis95** [comment]
Ok but can you check mine..
![image](https://user-images.githubusercontent.com/34500301/85056720-5585f880-b1bd-11ea-85bf-5cabbea12a0a.png)
![image](https://user-images.githubusercontent.com/34500301/85056734-5d459d00-b1bd-11ea-84c9-ad13c9ac1acb.png)
![image](https://user-images.githubusercontent.com/34500301/85056750-659dd800-b1bd-11ea-96bb-d90f17fa60d0.png)


I have created a lambda function(3.1) and referenced your puppeteer library in it and then run the PowerShell script.

The handler looks like this currently I'm resolving the dependencies and will upgrade the ram as well when i test it locally before publishing...**for publishing, i use visual studio publish to lambda directly**
![image](https://user-images.githubusercontent.com/34500301/85056840-89611e00-b1bd-11ea-9646-877ce7d2ea48.png)

**Comment by brianfeucht** [comment]
Ah I see what is going on here, there is a bit of magic in the creation of the nuget packages that make sure `aws.tar.br`, `chromium.br` and `swiftshader.tar.br` make into the final zip package uploaded to lambda.  Since you are including this project this way, that magic is lost and those files do not make it into your Lambda deploy package.  

Instead of using the project reference can you use the package reference?

**Comment by DevGenesis95** [comment]
Yes, I can use in any way been lost from few days :( 
ok joke apart

so u want me to include these in my csproj of lambda ryt?
 <PackageReference Include="PuppeteerSharp" Version="2.0.3" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.2.0" />
    <PackageReference Include="HeadlessChromium.Puppeteer.Lambda.Dotnet" Version="1.0.1.39" />
  But just a bit confused why we including the "HeadlessChromium.Puppeteer.Lambda.Dotnet" this package if pupeetersharp doing all the stuff.

**Comment by brianfeucht** [comment]
All `HeadlessChromium.Puppeteer.Lambda.Dotnet` does is repackage a build of `chromium` for Lambda and handles copying those files to a place executable by .NET.  It is meant to be a simple helper library to make PuppeteerSharp easier to use.  Building `chromium` for lambda is a bunch of work so we actually reuse the work done for a [NodeJs project](https://github.com/alixaxel/chrome-aws-lambda)

**Comment by DevGenesis95** [comment]
ok that's really impressive work u did there.

Update I have created a new lambda(3.1)..can you verify if its correct this time.
![image](https://user-images.githubusercontent.com/34500301/85059522-689ac780-b1c1-11ea-947f-4b6679bb87f7.png)

![image](https://user-images.githubusercontent.com/34500301/85059565-781a1080-b1c1-11ea-8e15-8221fdce942e.png)

**Comment by brianfeucht** [comment]
@DevGenesis95 yes this looks like it should work

**Comment by DevGenesis95** [comment]
oops..got this when on run i think its gonna take a while :(
![image](https://user-images.githubusercontent.com/34500301/85059679-ae579000-b1c1-11ea-9604-a0cc2c811fb1.png)

**Comment by brianfeucht** [comment]
@DevGenesis95 not sure the mock lambda will work on windows.  Since the chromium build is specific to a Linux Lambda AMI it is likely even if you get past this error you will get a bunch of failures trying to start chrome

**Comment by DevGenesis95** [comment]
ok, last shot I'm trying is to run this in the AWS environment.

**Comment by DevGenesis95** [comment]
Kudos guys..finally its working ..able to generate pdf from URL

![image](https://user-images.githubusercontent.com/34500301/85065917-98e76380-b1cb-11ea-8837-497259156910.png)

Thanks a ton!! @brianfeucht @kblok :)

**Comment by kblok** [comment]
Awesome!!
Thank you @brianfeucht!
