### ISSUE TITLE
How to download a file?

### ISSUE THREAD

**Issue by DreamITSoftware** [hardkoded/puppeteer-sharp#1508]
I am trying to download a file, but can't find any examples to do so.

**Comment by kblok** [comment]
Hey @DreamITSoftware, what would trigger the file download?

**Comment by DreamITSoftware** [comment]
I was hoping to be able to pass a URL without clicking a button

**Comment by DreamITSoftware** [comment]
I was hoping to do something like this page.DownloadFile(URL);

**Comment by kblok** [comment]
If you have the url you could use [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netcore-3.1). You wouldn't need a browser for that.

**Comment by DreamITSoftware** [comment]
Will the HttpClient recognize the cookies from Puppeteer?  This site requires a login.

**Comment by kblok** [comment]
You could try setting the download behavior as example 1 [here](https://github.com/hardkoded/puppeteer-sharp/issues/1238). And then you do Page.GoToAsync to that url.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
