### ISSUE TITLE
Failed to Launch Chromium issue in Pupeteersharp 2.0.3 version

### ISSUE THREAD

**Issue by testk1180** [hardkoded/puppeteer-sharp#1509]
Hello Sir,

We are working for one of enterprise client with having multiple session of pupeteer sharp running at same time with different chromium instances. We have added profile for chrome to separate the instance of chromium in pupeteersharp.

But there are very random issues of "failed to launch chromium" appearing on any of this chromium instance.

When we checked the logs - It said the chrome.exe crashed from the folder we were executing this Chromium instances.

We checked all your articles available for same issue but even after trying the same , the issue is not fixed.

Can you please help here urgently.

### Description

[Description of the issue]

#We are working for one of enterprise client with having multiple session of pupeteer sharp running at same time with different chromium instances. We have added profile for chrome to separate the instance of chromium in pupeteersharp.

But there are very random issues of "failed to launch chromium" appearing on any of this chromium instance.

When we checked the logs - It said the chrome.exe crashed from the folder we were executing this Chromium instances.

We checked all your articles available for same issue but even after trying the same , the issue is not fixed.

### Expected behavior:

Failed to launch chromium

### Actual behavior:
It should work without this issue.

### Versions

* Which version of PuppeteerSharp are you using?- 2.0.3
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0. - .NET framework 4.6.1 and .Net Core 2.2

**Comment by testk1180** [comment]
Hello Sir,

Please let know what can be done in this failed to launch chromium case. Also let us know if any additional details are required fro resolution.

**Comment by kblok** [comment]
@testk1180 do you have anything for me to test locally?

**Comment by mandal-rahul** [comment]
Hi here is a sample code of our application. The failure occurs as Puppeteer.LaunchAsync(options). The code works fine and behaves as expected, but randomly we get 'Failed to launch chromium error.'

Also, we are running 7 instances of the same application in one VM. **All of the 7 instance have their own copy of local-chromium.**

            try
            {

                var args = new List<string>();
                args.Add("--start-maximized");
                args.Add("--ignore-certificate-errors");

                string userDir = Path.Combine(Environment.CurrentDirectory, "userdir");
                try
                {
                    if (!Directory.Exists(userDir))
                    {
                        Directory.CreateDirectory(userDir);
                    }
                }
                catch (Exception ex)
                {
                    //It is okay to not have the dir, where shared user dir would be used

                }

                LaunchOptions options = new LaunchOptions();
                options.Headless = true;
                options.Args = args.ToArray();
                options.DefaultViewport = null;
                //Ignore certificate errors
                options.IgnoreHTTPSErrors = true;
                options.UserDataDir = userDir;
                if (String.IsNullOrEmpty(chromePath))
                    await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
                else
                    options.ExecutablePath = chromePath;

                using (Browser browser = await Puppeteer.LaunchAsync(options))
                {
                    try
                    {
                        //using (var page = await browser.NewPageAsync())
                        var pages = await browser.PagesAsync();
                        var page = pages[0];
                        var enableCache = true;
                        await page.SetCacheEnabledAsync(enableCache);  //default true if not set

                        await page.SetJavaScriptEnabledAsync(true);

                        if (!String.IsNullOrEmpty(userAgentString))
                            await page.SetUserAgentAsync(userAgentString);

                        if (String.IsNullOrEmpty(restrictedTypes))
                            await page.SetRequestInterceptionAsync(false);
                        else
                            await page.SetRequestInterceptionAsync(true);
                        Response response = null;
                        try
                        {

                            page.DOMContentLoaded += Page_DOMContentLoaded;
                            page.Dialog += Page_Dialog;
                            page.Request += (sender, e) => Page_Request(sender, e, restrictedTypes);


                            response = await page.GoToAsync(url, new NavigationOptions { Timeout = timeout, WaitUntil = new WaitUntilNavigation[] { WaitUntilNavigation.DOMContentLoaded, WaitUntilNavigation.Networkidle2 } });



                            if (response != null)
                            {
                                if ((int)response.Status == 200)
                                {
                                    //DoSomething
                                    // then close browser
                                    await browser.CloseAsync();
                                    browser.Dispose();
                                }
                                else
                                {
                                    //Log
                                }
                            }
                            else
                            {
                                //log
                            }
                        }
                        catch (Exception ex)
                        {
                            //handle exception


                        }

                    }}
            }

**Comment by mandal-rahul** [comment]
Also, here is a detailed error.
Failed to launch Chromium! [0713/050224.389:FATAL:feature_list.cc(282)] Check failed: !g_initialized_from_accessor. \r\nBacktrace:\r\n\tovly_debug_event [0x00007FFE055F1252+16183762]\r\n\tovly_debug_event [0x00007FFE055F0832+16181170]\r\n\tovly_debug_event [0x00007FFE05603383+16257795]\r\n\tovly_debug_event [0x00007FFE055F3386+16192262]\r\n\tovly_debug_event [0x00007FFE05144B2E+11283118]\r\n\tovly_debug_event [0x00007FFE0556DB58+15645400]\r\n\tovly_debug_event [0x00007FFE0556DACD+15645261]\r\n\tovly_debug_event [0x00007FFE05598F28+15822504]\r\n\tovly_debug_event [0x00007FFE0556D35E+15643358]\r\n\tovly_debug_event [0x00007FFE055983E3+15819619]\r\n\tovly_debug_event [0x00007FFE055982BB+15819323]\r\n\tovly_debug_event [0x00007FFE055980F2+15818866]\r\n\tChromeMain [0x00007FFE046811B6+286]\r\n\tOrdinal0 [0x00007FF7AE16275F+10079]\r\n\tOrdinal0 [0x00007FF7AE16182D+6189]\r\n\tGetHandleVerifier [0x00007FF7AE26B7C2+697538]\r\n\tBaseThreadInitThunk [0x00007FFE3B7084D4+20]\r\n\tRtlUserThreadStart [0x00007FFE3C1BE871+33]\r\n\r\n

**Comment by KyleCrowley** [comment]
I am also seeing this issue.

What is odd is that this error _sometimes_ occurs when running multiple Chrome instances via puppeteer/puppeteer-sharp. I say "sometimes" because I've seen instances where Chrome is perfectly fine when multiple instances are running/launched simultaneously. In other words, the issue seems to occur randomly.

[This issue](https://github.com/garris/BackstopJS/issues/1084) seems to reference the same problem, and [one suggestion](https://github.com/garris/BackstopJS/issues/1084#issuecomment-535634764) was to add a lock around the `LaunchAsync` call. 

This might work if you spawn multiple browsers within the same process, but not in my case, and not in OP's case, as we are spawning instances of Chrome in multiple processes.

The Chrome error logs aren't that helpful, or maybe I'm not looking in the right place.

I'd be happy to pass along some better logs (provided they exist), if you can point me to them @kblok.

Barring that, I don't know if this is something that can be fixed in this library. My guess is There's something going on in Chrome itself, but maybe we're misusing Chrome/puppeteer?

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
