### ISSUE TITLE
Improve docfx_project/examples/Page.EvaluateExpressionAsync.GetAllLinks.md

### ISSUE THREAD

**Issue by aishamerhebi** [hardkoded/puppeteer-sharp#1512]
Explain how would you like this document to be impoved

**Comment by kblok** [comment]
What do you think this document should be improved @aishamerhebi ?

**Comment by aishamerhebi** [comment]
I was actually looking for a solution for browser disconnect exception.
Eventually i got it is related to the newest version of chromium and i
needed to be on 79
