### ISSUE TITLE
Linux version different and does not execute prototypes

### ISSUE THREAD

**Issue by sseyalioglu** [hardkoded/puppeteer-sharp#1514]
### Description

The same url that works on macos or windows fails to load on linux version (headless or headful).
In the website we have prototype that overrides fetch and while it works perfectly on macos, samething does not work on linux version (to be specific ubuntu 18.04 with desktop/gui installed).

### Complete minimal example reproducing the issue

Just load the following URL, nothing else is required
https://www.wyndhamhotels.com/wyndham-garden/astana-kazakhstan/wyndham-garden-astana/overview?sessionId=1594163013&rooms=1&adults=1&children=0&checkInDate=7/7/2020&checkOutDate=7/8/2020&loc=ChIJCUa1fcSARUIRKJKx3Y0U-Zc&brand_id=GN&brandTier=gn&useWRPoints=false&referringBrand=GN

On MacOS you will see the following succcess
![image](https://user-images.githubusercontent.com/2631639/86854158-bdb55500-c06c-11ea-95c8-a59816ce8516.png)

However the same on linux will result in the following:
![image](https://user-images.githubusercontent.com/2631639/86853928-54cddd00-c06c-11ea-9406-7c60d0155ec4.png)

As you can see most of the 

### Expected behavior:

Work exactly the same and fully functional.

### Actual behavior:

Linux version fails to load resources and execute javascript fully as per expectation.

### Versions

.net Core 3.1
puppeteer 2.0.3

**Comment by kblok** [comment]
@sseyalioglu are you getting the same using Chrome in both platforms?

**Comment by sseyalioglu** [comment]
No.
When chromium is used standalone, everything worked normally on all platforms.

**Comment by sseyalioglu** [comment]
@kblok do you have any suggestion? Is there may be a filter we can use so this issue does not happen? Honestly don't know what the issue is. 

Our JS engineer told me: “We are overriding the prototype of global functions of “window” object, such as fetch() on this page to add some headers to requests. However, seems like puppeteer on linux is interfering with this — fetch is acting the like original one instead of modified version”

**Comment by kblok** [comment]
@sseyalioglu for what I see the problem are the previous requests, instead of 200 they are returning a 301 (redirect)
Could you see where they are redirecting to? Maybe they are detecting a bot.

**Comment by sseyalioglu** [comment]
It is 301 because necessary headers don't go there. Because we are unable to utilize overridden functions of window object like fetch etc.

**Comment by kblok** [comment]
Working for me

![image](https://user-images.githubusercontent.com/2198466/87078440-01d66000-c1fb-11ea-98c8-453dade95fe6.png)

![image](https://user-images.githubusercontent.com/2198466/87078401-f1be8080-c1fa-11ea-8e59-0b1c9954746c.png)

**Comment by sseyalioglu** [comment]
Is this really on linux? I tried on several machines, really.

**Comment by sseyalioglu** [comment]
Technically, used ubuntu 18.04

**Comment by kblok** [comment]
Ubuntu 18.04 on a VM

**Comment by kblok** [comment]
![image](https://user-images.githubusercontent.com/2198466/87079293-3565ba00-c1fc-11ea-9be9-32849a95b18b.png)

**Comment by sseyalioglu** [comment]
I will try this again on desktop ubuntu 18.04, i tried on server version with desktop installed after. (AWS)

**Comment by sseyalioglu** [comment]
Tried the same with same failure.
To make everything super clear, here is the screencast that shows what I experience: 
[https://d.pr/v/P9kXgB](https://d.pr/v/P9kXgB)

Whole code is here to see it again
`            var downloader = new BrowserFetcher(new BrowserFetcherOptions
                                                {
                                                    Path = Path.Combine(Path.GetTempPath(), ".chromium")
                                                });

            var chromiumLaunchOptions = new LaunchOptions
                                        {
                                            ExecutablePath = downloader.GetExecutablePath(BrowserFetcher.DefaultRevision),
                                            Headless       = false,
                                            Devtools       = true,
                                            LogProcess     = true,
                                            Timeout        = 600000
                                        };

            var browser = await Puppeteer.LaunchAsync(chromiumLaunchOptions);
            var page    = await browser.NewPageAsync();
            await page.GoToAsync("https://www.wyndhamhotels.com/wyndham-garden/astana-kazakhstan/wyndham-garden-astana/overview?sessionId=1594163013&rooms=1&adults=1&children=0&checkInDate=7/7/2020&checkOutDate=7/8/2020&loc=ChIJCUa1fcSARUIRKJKx3Y0U-Zc&brand_id=GN&brandTier=gn&useWRPoints=false&referringBrand=GN");

            Console.ReadLine();`

**Comment by sseyalioglu** [comment]
![image](https://user-images.githubusercontent.com/2631639/87086182-0c3a2f00-c1e6-11ea-8a09-c0bd16606fbc.png)

**Comment by kblok** [comment]
I was able to reproduce it. I wasn't looking at the XHR tab. 
But I do get that image
![image](https://user-images.githubusercontent.com/2198466/87088817-cabc7a80-c20b-11ea-9f8e-8eafe30e188c.png)


The same happens in puppeteer in node JS

```js
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({headless: false});
    const page = await browser.newPage();
    await page.goto('https://www.wyndhamhotels.com/wyndham-garden/astana-kazakhstan/wyndham-garden-astana/overview?sessionId=1594163013&rooms=1&adults=1&children=0&checkInDate=7/7/2020&checkOutDate=7/8/2020&loc=ChIJCUa1fcSARUIRKJKx3Y0U-Zc&brand_id=GN&brandTier=gn&useWRPoints=false&referringBrand=GN');

    browser.close();
})();
```

So it must be something on the browser itself.

**Comment by sseyalioglu** [comment]
ok, I am not crazy than at least. Certainly there is something different. And I think this will be the behavior on any linux version, right? 
And do you have any hints that may help?

**Comment by kblok** [comment]
I would report that on `https://bugs.chromium.org/`(you can use the code I shared). Besides that, I would be diving into StackOverflow as you would.

**Comment by sseyalioglu** [comment]
Is it bugs chromium? I think it is related to puppeteer. Chromium by itself works actually. It fails when run with puppeteer only.

**Comment by kblok** [comment]
It's on Chromium. pptr is not doing anything to cause that.

**Comment by sseyalioglu** [comment]
Got your point but can you please look into this short screencast as well: 
[https://d.pr/v/AoPZ4B](https://d.pr/v/AoPZ4B)
This is the sole reason, I think there is something about puppeteer on linux or the way we launch chromium.

**Comment by kblok** [comment]
Try running this `./chrome --remote-debugging-port=0 --enable-automation`

**Comment by sseyalioglu** [comment]
Yes, that is it. Having the same issue.

**Comment by sseyalioglu** [comment]
any of those switches on, causes the issue

**Comment by kblok** [comment]
Those flags make automation possible. We add over 10 more flags ever those two.
That's why the issue is on chromium.

**Comment by sseyalioglu** [comment]
Got it, thanks, will report to them.
