### ISSUE TITLE
[Question] Would you like to have a recorder for puppeteer-sharp?

### ISSUE THREAD

**Issue by nglthach** [hardkoded/puppeteer-sharp#1516]
Hi,
I'm Thach - Smart Monkey's author.
I have added a functionality to Smart Money for exporting a project to Puppeteer code (jest puppeteer). Here is the video for demo: https://www.youtube.com/watch?v=eBzK85MOo-A

In the most of cases, you don't need to write any line of code for creating a test suite.

I have one question: would you like to have similar functionality for exporting project to puppeteer-sharp code? If yes, please react :+1: this post! In case there are enough votes (1000), I will add the function!

Sincerely,
Thach

**Comment by kblok** [comment]
Yes!
