### ISSUE TITLE
Link to "linux troubleshooting guide" in homepage is 404

### ISSUE THREAD

**Issue by shoe-diamente** [hardkoded/puppeteer-sharp#1519]
**Before you file a bug, have you:**

### Description

The link in the master branch for the "linux troubleshooting guide" (https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md)  is not found.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
