### ISSUE TITLE
ContentFrameAsync doesn't work

### ISSUE THREAD

**Issue by maguro1kan** [hardkoded/puppeteer-sharp#1520]
await page.GoToAsync("https://recaptcha-demo.appspot.com/recaptcha-v2-checkbox.php", options);
ElementHandle frameEl = await page.QuerySelectorAsync(".g-recaptcha div iframe");
var frame = await frameEl.ContentFrameAsync(); <- **Error is here**

please check it. thanks

**Comment by kblok** [comment]
@maguro1kan could you try using this line?

```cs
ElementHandle frameEl = await page.WaitForSelectorAsync(".g-recaptcha div iframe");              
```

**Comment by maguro1kan** [comment]
I tried it but not work. VS says 'PuppeteerSharp.PuppeteerException'

**Comment by IliaBrahinets** [comment]
Works for me
Env: Windows 10 x64, .Net core 3.1.102, PuppeteerSharp 2.0.4
Complete code:
```csharp
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
await using var browser = await PuppeteerSharp.Puppeteer.LaunchAsync(new LaunchOptions());
var page = await browser.NewPageAsync();
await page.GoToAsync("https://recaptcha-demo.appspot.com/recaptcha-v2-checkbox.php");
var frameEl = await page.WaitForSelectorAsync(".g-recaptcha div iframe");
var frame = await frameEl.ContentFrameAsync();
```
@maguro1kan can be an issue with your environment, provide more details

**Comment by maguro1kan** [comment]
@IliaBrahinets Many thanks! It worked for me!
