### ISSUE TITLE
PDF Gets bigger and bigger with each new generation

### ISSUE THREAD

**Issue by mgpepe** [hardkoded/puppeteer-sharp#1522]
### Description

I am generating a pdf from HTML. If I load the page in my browser and SaveAs, all pictures, html, css & js is less than 5MB. However, when I generate a PDF, huge files get generated and they grow in size: 70MB, 90MB, 101MB, 115MB....

### Complete minimal example reproducing the issue

Complete means the code snippet can be copied into a unit test method in a fresh C# project and run.
Minimal means it is stripped from code not related to reproducing the issue.

E.g.

```csharp
        [HttpPost("PdfByHtml")]
        public async Task<IActionResult> PdfByHtml(PdfByHtml request)
        {
            await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true
            });
            var page = await browser.NewPageAsync();
            await page.EmulateMediaTypeAsync(MediaType.Screen);
            await page.SetContentAsync(request.Html);

            if (request.PdfOptions == null)
            {
                request.PdfOptions = new PdfOptions() { };
            }

            request.PdfOptions.Format = PaperFormat.A4;
            request.PdfOptions.MarginOptions.Bottom = "1.5cm";
            request.PdfOptions.MarginOptions.Top = "1.5cm";
            request.PdfOptions.MarginOptions.Left = "1.5cm";
            request.PdfOptions.MarginOptions.Right = "1.5cm";
            request.PdfOptions.Scale = new decimal(0.8);

            var pdf = File(await page.PdfDataAsync(request.PdfOptions), "application/pdf");
            await browser.CloseAsync();
            return pdf;
        }
```

### Expected behavior:

Consistent file size with less than or about 5Mb

### Actual behavior:

growing file size 70, 90, 100Mb

### Versions

* Which version of PuppeteerSharp are you using? 2.0.0
* Which .NET runtime and version are you targeting? Core 2.2

### Additional Information

...

**Comment by kblok** [comment]
Could you share some HTMLs with me? at least by email?

**Comment by mgpepe** [comment]
Sure, I just wrote you an email with the attached HTML

**Comment by mgpepe** [comment]
After some fiddling, I noticed that 'background image bloats significantly the size. 
If I use 400kb image with the following html for pdf generation:
```
<html><body>
    <img src="http://path-to-image.com" />
</body></html>
```
I get 403kb for example. 

If I use that same image and I put it in the background like so:
```
<html><body>
    <div style="background-image: url(http://path-to-image.com);  background-size: cover; height: 400px; ">
</div></body></html>'; 
```
I get about 3Mb file. It is a stable always 3Mb file, it doesn't increase like before.

**Comment by kblok** [comment]
Interesting @mgpepe can you see if you get the same results using the print to PDF in Chrome? It should be the same tool.

**Comment by mgpepe** [comment]
Printing is normal, but also, it doesn't have the right styles. We need the media screen, while this pdf is generated out of media print.

**Comment by mgpepe** [comment]
Ah! @kblok but if I tick the "background graphics" check of Chrome it looks like it uses the media screen, and then a 3mb pdf goes up to 113mb.

**Comment by kblok** [comment]
So it's chromium. I would report that here https://bugs.chromium.org/

**Comment by SimonCropp** [comment]
@kblok looks like this can be closed?
