### ISSUE TITLE
  TimeoutException Timeout Exceeded: 30000ms exceeded Void MoveNext()

### ISSUE THREAD

**Issue by mertmtn** [hardkoded/puppeteer-sharp#1527]
When I used Puppeteer sharp to create pdf file, I am getting an error on Actual behavior.
 
At below this code, create a new page and timeout value comes from web config and its value is 2000ms.

        public static Page  SayfaOlustur()
        {
            //Browser browser = null;
            try
            {
                var filePath = ConfigurationManager.AppSettings["PuppeterSharpBrowserFetcherLocalChromium"].ToString();
                int timeOut = 0;
                if (int.TryParse(ConfigurationManager.AppSettings["PuppeterSharpBrowserTimeoutSuresi"], out timeOut))
                {
                    timeOut = Convert.ToInt32(ConfigurationManager.AppSettings["PuppeterSharpBrowserTimeoutSuresi"]);
                }
                var browserFetcher = new BrowserFetcher(new BrowserFetcherOptions
                {
                    Path = string.IsNullOrEmpty(filePath) ? @"D:\PuppeteerSharpLocalChromium" : filePath
                });
                 browserFetcher.DownloadAsync(BrowserFetcher.DefaultRevision).GetAwaiter().GetResult();

                 browser =   Puppeteer.LaunchAsync(new LaunchOptions
                {
                    Timeout = timeOut,
                    Headless = true,
                    ExecutablePath = browserFetcher.RevisionInfo(BrowserFetcher.DefaultRevision).ExecutablePath
                }).GetAwaiter().GetResult();
            }
            catch (WebException ex)
            {
                HelperUtils.CmsLogger.Error(ex, "wSayfaOlustur");
            }
            catch (Exception ex)
            {
                HelperUtils.CmsLogger.Error(ex, "SayfaOlustur");
            }

            return browser.NewPageAsync().GetAwaiter().GetResult();
        }

### Expected behavior:

The page must upload with all scripts and css codes and then create a pdf file

### Actual behavior:

Due to the exception, not create any pdf file.

  TimeoutException Timeout Exceeded: 30000ms exceeded Void MoveNext()

   at PuppeteerSharp.FrameManager.<NavigateFrameAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CMS.PuppeteerSharp.PuppeteerSharpMethods.ArastirmaRaporPdfOlusturFromUrl(Boolean isOnizleme, String filePath, String filename, Dictionary`2 cookies, ArastirmaRaporAramaKriter arastirmaRaporAramaKriter)

### Versions

IIS Version 8.5
NET Framework 4.7.2

### Additional Information

Headless value has to be true. 
If I set Timeout value as 0 (zero), will this problem be solved?
Can published server and application pool affect timeout? Sometimes, server could work slowly.

**Comment by kblok** [comment]
@mertmtn Could you try making your code async? instead of using `.GetAwaiter().GetResult();`across the board?

**Comment by mertmtn** [comment]
Is the GetAwaiter() same logic with async/await?

**Comment by kblok** [comment]
@mertmtn no, it's not :) 
`GetAwaiter().GetResult()` is blocker (see https://blog.stephencleary.com/2014/12/a-tour-of-task-part-6-results.html)

**Comment by mertmtn** [comment]
If I set Timeout value as 0 (zero), will this problem be solved? 
Below link, not belongs to puppeteer sharp but puppeteer. It suggest to set timeout value is zero - 0
https://stackoverflow.com/questions/60051954/puppeteer-timeouterror-navigation-timeout-of-30000-ms-exceeded

PS: Does it matter about number of usage of the appliacation, this application like works content management system so, at least two people use it? Because of this question, to make async is suggested solution?

**Comment by kblok** [comment]
Nothing should prevent you from using async/await. We know that it will work.
If you use ASP.NET FullFramework, you will need to use the AspNetWebSocketTransport.AspNetTransportFactory (https://www.nuget.org/packages/PuppeteerSharp.AspNetFramework/)

Example here https://github.com/hardkoded/puppeteer-sharp/blob/master/samples/PupppeterSharpAspNetFrameworkSample/PupppeterSharpAspNetFrameworkSample/Services/BrowserClient.cs#L23

**Comment by mertmtn** [comment]
Thanks for your help, we will consider to apply your solution when update version of our application. 

We have set timeout to 0 as a temporary solution.
