### ISSUE TITLE
Intercepting requests sent by iframe

### ISSUE THREAD

**Issue by mcopur** [hardkoded/puppeteer-sharp#1529]
I am trying to intercept all web requests using by Puppeteer-Sharp but it is not working properly if the request sent by IFrame which is located on the page. For instance, After navigated this link, I clicked the video [link](https://www.rtlnieuws.nl/nieuws/video/video/5173153/een-mondkapjesplicht-de-kalverstraat-gaat-dat-werken) since the video is in the iframe(maybe this is not the cause, this is only my hypothesis), the new web requests sent by IFrame did not intercept but the others were intercepted. When I checked it on the Chrome Developer Tools I was able to see what I am looking for and also more requests.

By the way, I set Request Interception as true as below:

` await page.SetRequestInterceptionAsync(true);`

and I registered for the PageRequest event as below:

` page.Request += Page_Request`

Is there any other setting or missing setup?

**Comment by mcopur** [comment]
Btw, I also tried to use "MessageReceived" event in page.Client.MessageReceived but there are still missing requests and responses. Is there any way to intercept iframe requests & responses in puppeteer-sharp?

**Comment by kblok** [comment]
Do you have a code for me to test @mcopur ?

**Comment by mcopur** [comment]
@kblok  Thanks for your reply but I found a solution for it. When I passed "--disable-features=IsolateOrigins,site-per-process" parameter to the browser launch arguments, I was able to get all requests and responses.

**Comment by kblok** [comment]
That's great @mcopur. Thanks for taking the time to come here and share the solution :)
