### ISSUE TITLE
I don't know where else to ask, but does Pupeteer Sharp support the Puppeteer Extra Stealth Plugin?

### ISSUE THREAD

**Issue by GramCreator** [hardkoded/puppeteer-sharp#1530]
As the title says, the slack channel link wasn't working, so I don't know where else to ask.

Thanks!

**Comment by acensmar** [comment]
https://github.com/berstend/puppeteer-extra/issues/69
https://github.com/shravan2x/PuppeteerSharp.Extra

You can update some of the classes from here https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth/evasions. 

I am able to change user agent .etc. but not the plugins. It feels like I can't mess with OnPageCreatedAsync any idea how u can run js onpagecreated on PuppeteerSharp

```

  var browser = new PuppeteerExtra();
  var plugin = new PuppeteerExtraPluginStealth();
   var ua = new AnonymizeUaPlugin();
    browser.Use(ua);
   // browser.Use(plugin); -> this wont work I am not sure why!!!

   Browser x = await browser.LaunchAsync(new LaunchOptions
     {
       Headless = true,
        IgnoreHTTPSErrors = true
     });
```
p.s make sure u uncomment the availableEvasions from  PuppeteerExtraPluginStealth.cs

**Comment by Overmiind** [comment]
Hi, I recommend you to use my library - https://github.com/Overmiind/Puppeteer-sharp-extra because the library from the above comment is not working and hasn't been updated in 9 months.
I am going to update and support other plugins soon
