### ISSUE TITLE
add an icon?

### ISSUE THREAD

**Issue by SimonCropp** [hardkoded/puppeteer-sharp#1540]
Perhaps https://thenounproject.com/search/?q=puppet&i=999438
![image](https://user-images.githubusercontent.com/122666/90299765-b4749f00-deda-11ea-891a-fb3f19ec9759.png)

let me know if u want a PR

**Comment by kblok** [comment]
It looks pretty cool 😎 
Could you also update the docfx project with that?

**Comment by SimonCropp** [comment]
https://github.com/hardkoded/puppeteer-sharp/pull/1541
