### ISSUE TITLE
ResponseData.Headers can't deal with multiple headers with same name

### ISSUE THREAD

**Issue by L6Echo** [hardkoded/puppeteer-sharp#1542]
### Description

The Headers field of the ResponseData is a map of header name to header value. This assumes that every header type can be set only once, but this is assumption is not correct. E.g. the Set-Cookie may be listen multiple times.

In System.Net.Http this is solved by using a Map which maps the header name to a list of values.

### Complete minimal example reproducing the issue

When intercepting the http request, it is not possible to set multiple cookies:

E.g.

```csharp
        private async Task InterceptAsync(RequestEventArgs args)
        {
            var responseData = new ResponseData
            {
                Body = "{\"success\": true}",
                ContentType = "application/json; charset=utf-8",
                Headers = new Dictionary<string, object>(),
                Status = HttpStatusCode.OK
            };
            
            responseData.Headers.Add("Set-Cookie", "session=xyz; path=/; samesite=none");
            responseData.Headers.Add("Set-Cookie", "addition=abc; path=/; samesite=none");

            await args.Request.RespondAsync(responseData);
        }
```

### Expected behavior:

It should be possible to set headers multiple times with same name.

### Actual behavior:

Only one value per header name can be added.

### Versions

* PuppeteerSharp: 2.0.4
* .NET: .NET Core 3.1.3

**Comment by kblok** [comment]
I believe [Chrome devtools protocol](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#type-HeaderEntry)  won't support duplicates there. 
Won't `Page.SetCookieAsync` work for you?

**Comment by L6Echo** [comment]
The headers property is an Array of HeaderEntries. So it should be possible to set multiple headers with the same name. Except the protocol checks for uniqueness of header names. But I wouldn't expect this. Because it is a legit case.

Yes, currently i did a workaround with SetCookieAsync. But this bypasses the cookie handling of chrome and this may distort the test result. Additional the cookie header must be parsed manually which may also behave different than the chrome cookie handling itself.

**Comment by venky8951** [comment]
Hi @kblok can I start looking into this ? seems like we need to implement RespondAsync for List<strings>(values)

**Comment by kblok** [comment]
If you can make it work without breaking any test, go for it!

**Comment by venky8951** [comment]
Hi @kblok I have tried couple of ways to address this issue but it seems having Dictionary<string,Object> is difficult to parse
can we use a List<KeyValuePair<string, object>> instead of a Dictionary<string,Object> ?

**Comment by kblok** [comment]
If that's internal yes. I wouldn't break the API for this.
