### ISSUE TITLE
Headers and footers creation on pdf

### ISSUE THREAD

**Issue by raviprithivi** [hardkoded/puppeteer-sharp#1544]
I am currently using puppeteer version 2.0.3 in the back end. I am basically trying to create a print preview option for the user so see how the final report would look like. I have tried options to create headers and footers on the html page as documented here: https://medium.com/@Idan_Co/the-ultimate-print-html-template-with-header-footer-568f415f6d2a

However these code generated headers and footers don't seem to be how puppeteer generate headers and footers. I was able to follow the code line 973 in Page.cs (), PdfInternalAsync function. I am not really sure what happens after that. Do you guys use command line tools to directly change the default headers and footers or use css media like in the above link to create a header and a fooer

It also seems like Chrome does not really give the user/ developer the option to directly edit the header and footer as documented here.
https://superuser.com/questions/1185459/modify-page-header-and-footer-when-printing-in-chrome

Please let me know when you can, just so i can create a page preview option for the user

**Comment by kblok** [comment]
Did you try something like this https://github.com/hardkoded/puppeteer-sharp/blob/e5d2c7d4b85664d1057660c2c5be0c586f458dcb/docfx_project/api/index.md#generate-pdf-files-with-custom-options?

**Comment by raviprithivi** [comment]
Hey @kblok , yep so i have a similar set up where i pass the margins, headers and footers via PdfOptions. What is can't seem to understand is the headers and footers puppetter generates seems to be outside of the actual content within the margin boxes. Any way of generating headers and footers using css seems to put the headers and footers inside the content.

So i just want to know how puppetter sets headers and footers for the page? do you use css media or something else?

**Comment by kblok** [comment]
@raviprithivi header and footer are CDP arguments (https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF). And the CDP pass those values to the Skia engine they use to generate PDF files https://skia.org/user/sample/pdf

**Comment by raviprithivi** [comment]
@kblok Thank you so much. This helps. Also just wanted to know if there is any work being done on page-break-after: avoid property (https://www.w3schools.com/cssref/pr_print_pageba.asp)

As far as i can tell chromium still does not support it, but having that respected by the puppeteer code in some way would be vastly useful in helping create solid pdf output out of HTML. Thank you

**Comment by kblok** [comment]
It seems that property has almost no browser support. Puppeteer/Puppeteer-sharp is no more than an API over Chromium DevTools Protocols. If chromium doesn't support that there is no much we can do.

**Comment by raviprithivi** [comment]
@kblok Fair enough. Thank you anyway
