### ISSUE TITLE
Improve Tabloid

### ISSUE THREAD

**Issue by AdarshSharma1994** [hardkoded/puppeteer-sharp#1545]
Explain how would you like this document to be impoved.
Source URL: https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Media/PaperFormat.cs/#L38

**Comment by kblok** [comment]
@AdarshSharma1994 what do you think we need to do there?

**Comment by AdarshSharma1994** [comment]
I got into a very muddy issue in which I am providing whole HTML to the puppeteer but in result only getting a single page. Everything just works perfect but only one page and rest of the data is slashed. I was trying to fix this and in the mean time clicked on wrong link although any help would be appreciated.
Thanks!
