### ISSUE TITLE
How to fill a form inside an iframe with Puppeteer-Sharp

### ISSUE THREAD

**Issue by ChinaPhusun** [hardkoded/puppeteer-sharp#1546]
WebUrl: http://w8r.fut168.com/
SearchCode:**11188**

I have tried to check the frames with page.Frames, but since the iframes have no name and id, difficult to find the correct frame I am looking for.
![chrome_tZFtjMKoVQ](https://user-images.githubusercontent.com/38497378/91505412-1af9b400-e902-11ea-92af-aa04627980e1.png)

**Comment by kblok** [comment]
Did you try to find it with the URL?

**Comment by ChinaPhusun** [comment]
> Did you try to find it with the URL?

Yeah, But Every time you open a web page, the iframe URL is different.

**Comment by kblok** [comment]
Maybe using a Contains? There is not much Puppeteer can do...
