### ISSUE TITLE
How to set a cookie

### ISSUE THREAD

**Issue by Yeshdl** [hardkoded/puppeteer-sharp#1547]
I've looked at a lot of examples, none of them about how to set cookies。
Can you give me an example?
I know that setting a cookie is SetCookieAsync()
It contains the cookieparam parameter
However, how is this filled in
I use it asp.net

**Comment by kblok** [comment]
Hey @Yeshdl we have a few tests as example https://github.com/hardkoded/puppeteer-sharp/blob/7fca5eeeaa9e138af09e24bd98d11d128cac260b/lib/PuppeteerSharp.Tests/PageTests/Cookies/SetCookiesTests.cs#L10
