### ISSUE TITLE
Error about "Chromium revision is not downloaded. Run BrowserFetcher.DownloadAsync or download Chromium manually"

### ISSUE THREAD

**Issue by mertmtn** [hardkoded/puppeteer-sharp#1550]
## Description

There is a method ,named OpenChromiumPage(), which open Chromium page as headless=true. While opening chromium, download zip file with revision number but its size 0KB.

After that, the method threw an exception with message says that "Chromium revision is not downloaded. Run BrowserFetcher.DownloadAsync or download Chromium manually"

Sometimes zip file extracted but when try to download chromium, giving the same error.

Should I update or add any code to below method? 

My code located below.  

```
         public static async Task<Page> OpenChromiumPage()
        {
            var browserFetcher = new BrowserFetcher(new BrowserFetcherOptions
            {
                Path = "C:\\Chromium"
            });
            await browserFetcher.DownloadAsync(BrowserFetcher.DefaultRevision);
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
                Timeout = 0
            });
            return await browser.NewPageAsync();
        }
```
  
### Expected behavior:

Zip file extracted and Chromium works

### Actual behavior:

"Chromium revision is not downloaded. Run BrowserFetcher.DownloadAsync or download Chromium manually"

### Versions

Version of PuppeteerSharp : v1.19.0 but latest versions give same result.
.NET runtime and version: .NET framework 4.6.2

### Additional Information

I tried to set a value for ExecutablePath property which is chromium.exe file path. Then download and works.

Is there any other solution or What should I update my code?

**Comment by imlokesh** [comment]
You have to pass `ExecutablePath` to `Puppeteer.LaunchAsync`. It will look like this:

         public static async Task<Page> OpenChromiumPage()
        {
            var browserFetcher = new BrowserFetcher(new BrowserFetcherOptions
            {
                Path = "C:\\Chromium"
            });
            await browserFetcher.DownloadAsync(BrowserFetcher.DefaultRevision);
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
                Timeout = 0,
                ExecutablePath = "c:\\....\\chrome.exe"
            });
            return await browser.NewPageAsync();
        }

If you do not pass `Path` in BrowserFetcher, the you do not need to add `ExecutablePath` because it will automatically look into default download location.

**Comment by LastTribunal** [comment]
Chrome is downloaded in its own version folder
C:\ChromiumDL\Win64-706915 (folder created by the downloaded)
How do you specify that folder in the executable path?

**Comment by kblok** [comment]
BrowserFetch will always create its own folder. You can get that folder if you call `GetRevisionInfo` and get the `ExecutablePath` property from there.

**Comment by LastTribunal** [comment]
Thanks, having trouble figuring out how to call GetRevisionInfo..

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.

**Comment by kinguru** [comment]
Little off-topic. Is there a possibility to not include the Chromium with my application and leave it to be downloaded with BrowserFetcher, BUT somehow to configure BrowserFetcher to fetch seme specifi version of the Chrome.

To have consistent behavior of my application which will not be affected by future Chromium engine updates.

**Comment by kblok** [comment]
@kinguru  If you use the `DefaultRevision`.  Puppeteer will download the same revision unless you upgrade the library.

**Comment by kinguru** [comment]
thanks @kblok !
