### ISSUE TITLE
Chrome is getting closed after program execution

### ISSUE THREAD

**Issue by uperformkarthick** [hardkoded/puppeteer-sharp#1551]
We are doing a automation for google accounts. The automation is successful in injecting the username and password. But once the process completes the browser is getting closed. Is there any way to prevent the browser close after execution. Please find the below code for your review.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using puppeteer;
using PuppeteerSharp;

```
namespace puppeteer
{
    class Program
    {
        static async Task Main(string[] args)
        {

            using (var browser = await Puppeteer.ConnectAsync(new ConnectOptions
            {
                BrowserURL = "http://127.0.0.1:2122"
               
            }))
            

            {

                var pages = await browser.PagesAsync();
                var page = pages.FirstOrDefault();
                
                // use page
                await page.GoToAsync("https://accounts.google.com/");
                
                //TODO : change to your email
                await page.TypeAsync("#identifierId", "someusername");
                await page.WaitForSelectorAsync("#identifierNext");
                await page.ClickAsync("#identifierNext");
                await Task.Delay(2000);

                await page.WaitForSelectorAsync(@"input[type='password']");
                await Task.Delay(2000);
                await page.ClickAsync(@"input[type='password']");
                await Task.Delay(2000);

                //TODO : change to your password
                await page.TypeAsync(@"input[name='password']", "sompassword");
                await Task.Delay(2000);
                await page.WaitForSelectorAsync("#passwordNext");
                await Task.Delay(2000);
                await page.ClickAsync("#passwordNext");
                await Task.Delay(2000);
                
            }
        }
    }
}

```

**Comment by kblok** [comment]
@uperformkarthick if you want to leave the browser open, you will need to open the browser by yourself and connect to it.

This example is for Pupppeteer but it will work https://stackoverflow.com/a/55100293/2373249.

**Comment by uperformkarthick** [comment]
Yes. I am launching the chrome manually and using the Puppeteer.ConnectAsync() and able to go to a URL and do all functionalities. But once the process is finished, the browser is getting closed.

**Comment by kblok** [comment]
Ah, so sorry about that. Don't use `using` so the close is not triggered :)

**Comment by uperformkarthick** [comment]
It is working now. Thank you very much for help.
