### ISSUE TITLE
how to set window position after launch browser

### ISSUE THREAD

**Issue by agasii** [hardkoded/puppeteer-sharp#1553]
https://stackoverflow.com/questions/63935318/puppeteer-set-window-position-after-launch

I want to dynamically reposition the window after launch puppeteer browser.
But I couldn't find a way anywhere.
How can I do this in puppeteer?

In selenium, something like this:
driver.manage().window().position = new point(100,200);

**Comment by kblok** [comment]
Let's use the question in SO.
