### ISSUE TITLE
Port of puppeteer-page-proxy

### ISSUE THREAD

**Issue by acensmar** [hardkoded/puppeteer-sharp#1554]
### Description

Is there any port of https://github.com/Cuadrix/puppeteer-page-proxy,

```
Credentials creds = new Credentials();
creds.Username = apiKey;
await page.AuthenticateAsync(creds);
```

<---- works only for HTTP pages. I am trying to use a PROXY API and it's not getting the HTTPS pages!

```
 await page.SetExtraHttpHeadersAsync(new Dictionary<string, string>
 {
          ["Proxy-Authorization"] = "Basic " + encodedApiKey
 });
```

also tried that and I get an ERR_UNEXPECTED_PROXY_AUTH. I installed the certificate nothing happened! (using crawlera)

**Comment by AMBULATUR** [comment]
+1

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
