### ISSUE TITLE
puppeteer ,Deprecated API: page.waitFor and frame.waitFor

### ISSUE THREAD

**Issue by mrs01dev** [hardkoded/puppeteer-sharp#1555]
Puppeteer  project :
https://github.com/puppeteer/
Had released a new version 
 https://github.com/puppeteer/puppeteer/releases/tag/v5.3.0
It had Deprecated API: page.waitFor and frame.waitFor
Is there is any updates to  puppeteer-sharp?

**Comment by kblok** [comment]
My focus is now on playwright that (https://github.com/hardkoded/playwright-sharp)
But I don't see any blocker in the feature you mentioned. They are dropping and extra function.
