### ISSUE TITLE
Optimize instances when multiple Applications running on same machine

### ISSUE THREAD

**Issue by ansbilalgit** [hardkoded/puppeteer-sharp#1556]
### Description

I am using pupeeterr-sharp in my .net core application . Everything is running fine except I have to optimize the system resources . I have following two issues and I am looking for a way to resolve them . 

- Multiple chromium processes 

- Allow multiple applications to access same instance of browser

When I run my application and check my processes it display 4-5 processes of chromium for single application. Note that I am launching browser just once in my application also I am just opening a single page . I have tried to use `"--single-process", "--no-zygote"` flags in browser options but it gives `
Failed to launch Base! [19096:1240:0930/140433.373:FATAL:content_main_runner_impl.cc(528)] --single-process is not supported in chrome multiple dll browser.` Error . 

Secondly I want to run different independent applications. So, I don not want every application downloads its own copy of browser and run . I want to download chromium once on my machine in some global location and I want all my applications to use that instance and open different tabs instead of launching browser multiple time 

```
       try
               {
                LoggerUtility.LogMessage("Initializing Browser");
                WaitUntilNavigation[] waitUntil = { WaitUntilNavigation.Load, WaitUntilNavigation.Networkidle0 };
                await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
                // Checking If browser already running
                if (browser == null || !browser.IsConnected)
                {
                    LoggerUtility.LogMessage("Launching Browser");
                    browser = await Puppeteer.LaunchAsync(getLaunchOptions());
                    browser.Disconnected += OnBrowserDisconnect;
                }
                while (!isPageLoaded && config.Retry > 0)
                {
                    page = (await browser.PagesAsync())[0];
                    await page.ExposeFunctionAsync<string, string, bool>("onCustomEvent", OnCustomEvent);

                    LoggerUtility.LogMessage("Loading Url", config.BaseUrl);
                    try
                    {
                        var response = await page.GoToAsync(config.BaseUrl, new NavigationOptions
                        {
                            Timeout = 0,
                            WaitUntil = waitUntil
                        });
                        if (response.Status == System.Net.HttpStatusCode.OK)
                        {
                            isPageLoaded = true;
                            LoggerUtility.LogMessage("Page Loaded succesfully");
                            //await page.EvaluateExpressionAsync(" $('.event__match').bind('DOMSubtreeModified', function(e) { window.onCustomEvent(e.currentTarget)})");
                            await page.EvaluateExpressionAsync(" $('.event__match').bind('DOMSubtreeModified', function(e) { console.log('live event occured'); window.onCustomEvent($(e.currentTarget).prop('outerHTML'),$(e.currentTarget).attr('id'))})");
                            string html = await page.GetContentAsync();
                            extractLiveTable(html);
                        }
                        else
                        {
                            LoggerUtility.LogMessage("Error in loading page", response.Status.ToString(), response.StatusText);
                            config.Retry--;
                            Thread.Sleep(500);
                        }
                    }
                    catch (Exception ex)
                    {
                        LoggerUtility.Error(ex);
                        config.Retry--;
                        Thread.Sleep(500);
                    }
                }
            }
            catch (Exception ex)
            {
                LoggerUtility.Error(ex);
                throw ex;
            }
```

### Expected behavior:

I am expecting to run single instance of browser for multiple application with minimum processes in background

### Actual behavior:

Every application is launching it own instance of browser with multiple processes in background 

### Versions

* puppeteer-sharp 2.0.4
* .NET Core 3.1.

**Comment by matyasbach** [comment]
Have you tried PuppeteerSharp.Puppeteer.ConnectAsync()?
https://github.com/hardkoded/puppeteer-sharp#connect-to-a-remote-browser

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
