### ISSUE TITLE
Fix Linux CI

### ISSUE THREAD

**Issue by kblok** [hardkoded/puppeteer-sharp#1558]
Let's fix the Linux CI.

**Comment by bulat-gab** [comment]
Hello, can you please provide some more information?

**Comment by kblok** [comment]
Yes @bulat-gab. 
The Linux CI, triggered by https://ci.appveyor.com/project/kblok/puppeteer-sharp-esipd/builds/35593283,  started failing a few months ago. See https://github.com/hardkoded/puppeteer-sharp/blob/master/appveyor-linux.yml

The job would be trying to see what needs to be changed in that yml to bring that back to life.

**Comment by RahulSapkota** [comment]
hi, how do i provide the chromium installed path link in .net core.

**Comment by kblok** [comment]
@RahulSapkota `LaunchAsync` has an `executablePath` attribute in the `LaunchOptions`. You can also use the environment variable `PUPPETEER_EXECUTABLE_PATH` from outside the code.

**Comment by RahulSapkota** [comment]
i am using chromium.exe within the folder inside project itself. but when i use the same in linux i think .exe is not working.  can you please help on this like how to run this in linux. please refer to below screen.i am alreadyng using the attribute you mentioned.

![image](https://user-images.githubusercontent.com/10920769/95767067-e5ebca00-0cd3-11eb-9c5f-9979f1147260.png)

**Comment by RahulSapkota** [comment]
i have fixed it and get it working on linux as well but not sure why it's very very slow :(

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
