### ISSUE TITLE
Allow Microphone and Camera Access

### ISSUE THREAD

**Issue by mmehdidehghani** [hardkoded/puppeteer-sharp#1570]
I am using puppeteer-sharp to enter a virtual conference and retrieve data, but I have to pass the permission prompt for microphone and camera, my codes are:

var browser = await Puppeteer.LaunchAsync(new LaunchOptions { Headless = true, Timeout = 50000, Args = new[] { "--use-fake-device-for-media-stream" }});
var context = browser.DefaultContext;
await context.ClearPermissionOverridesAsync();
await context.OverridePermissionsAsync("https://video-app-123456",  new []{ OverridePermission.Camera, OverridePermission.Microphone});
var page = await context.NewPageAsync();
await page.SetUserAgentAsync(HttpContext.Request.Headers["User-Agent"]);
await page.GoToAsync("https://video-123456?passcode=123456789");
//Fill inputs
await page.WaitForSelectorAsync("#input-user-name");
await page.FocusAsync("#input-user-name");
await page.Keyboard.TypeAsync("NewUser");
//Click First Join Button
await page.ClickAsync("#join1Button");
//Click Second Join Button (Camera and Microphone Access)
await page.ClickAsync("#join2Button");
await page.WaitForNavigationAsync();
string content = await page.GetContentAsync();         
await browser.CloseAsync();

How can I allow the browser to use camera and microphone?

![Capture](https://user-images.githubusercontent.com/14868539/95653313-b175e380-0b04-11eb-8f2e-728d27c9c641.JPG)

**Comment by kblok** [comment]
Maybe related to this upstream issue https://github.com/puppeteer/puppeteer/issues/3241

**Comment by mmehdidehghani** [comment]
Dear kblok
Thanks for your response.
I checked that and I couldn't run that on c#:
const granted = await page.evaluate(async () => {
  return (await navigator.permissions.query({name: 'camera'})).state;
});
Could you please help me?

**Comment by kblok** [comment]
@mmehdidehghani here you have an example :) 
https://github.com/hardkoded/puppeteer-sharp/blob/7fca5eeeaa9e138af09e24bd98d11d128cac260b/lib/PuppeteerSharp.Tests/PageTests/BrowserContextOverridePermissionsTests.cs#L14

**Comment by mmehdidehghani** [comment]
Dear kblok
It worked!!!!!!
Thankssssssssss for your help.
Best Regards
