### ISSUE TITLE
Protocol error (Runtime.callFunctionOn) on remote debugger

### ISSUE THREAD

**Issue by victornor** [hardkoded/puppeteer-sharp#1575]
**Issue**
I'm having this strange exception, which seems to happen randomly, shortly after making the connection.

**Exception**
"Protocol error (Runtime.callFunctionOn): Session closed. Most likely the Page has been closed.Close reason: The remote party closed the WebSocket connection without completing the close handshake."

**Stacktrace**
"  at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback)
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args)
   at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args)
   at PuppeteerSharp.ExecutionContext.EvaluateFunctionHandleAsync(String script, Object[] args)
   at PuppeteerSharp.ElementHandle.XPathAsync(String expression)
   at PuppeteerSharp.DOMWorld.XPathAsync(String expression)"

This doesn't happen when i launch the chrome instance within the code itself through Puppeteer.LaunchAsync.
This happens only when using a remote chrome debugger like browserless.io in docker.

**Reproduction:**
1. Start browserless docker container
docker run -e "DEFAULT_HEADLESS=false" -p 3000:3000 --restart always -d --name browserless browserless/chrome:1.40-chrome-stable

2. Connect with PuppeteerSharp

`var browser = await Puppeteer.ConnectAsync(new ConnectOptions()
   {
      BrowserWSEndpoint = "ws://localhost:3000"
   });
 var page = await browser.NewPageAsync();`

3. Navigate to some arbitrary page and loop random actions like
await page.XPathAsync()
await (elementHandle).ClickAsync()
etc.

In my case, the exception seems to be thrown by either of the actions listed above.

**Any suggestions or possible fixes would be greatly appreciated**
**Thanks for building this amazing port!**

**Comment by victornor** [comment]
I apologize for somehow failing to find the issue #1492 
I am however already on PuppeteerSharp 2.0.4 and PR #1521 seems to not have fixed the issue for me.

**Comment by victornor** [comment]
@kblok You don't consider this a bug?

**Comment by kblok** [comment]
@victornor it could be.
`The remote party closed the WebSocket connection without completing the close handshake.` generally means that the browser crashed.  It depends on what makes the browser crash.

**Comment by victornor** [comment]
So this would most likely be an issue on the docker side, rather than the client(PuppeteerSharp) side?

**Comment by kblok** [comment]
@victornor do you get any log on docker?

**Comment by victornor** [comment]
I don't get any logs on the docker container.
But i'm using browserless docker image, so there might be some argument to enable logging.
Will look more into that!

**Comment by victornor** [comment]
Apparently browserless kills sessions automatically after 30 seconds.
The argument is called "connection timeout", so i didn't think this was the issue.

Thanks for your time.
