### ISSUE TITLE
Puppeteer and Cloudflare

### ISSUE THREAD

**Issue by Uceef94** [hardkoded/puppeteer-sharp#1576]
### Description

I'm having a hard time with cloudflare based websites, especially with the js challenge.

### Complete minimal example reproducing the issue
```
            var url = "https://www.leafproxies.io";
            var version = new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision).Result;
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = false,
                IgnoreHTTPSErrors = true,
                
                IgnoredDefaultArgs = new string[] {"--disable-extensions" }
            }) ;
            
            Page page = null;
            var pages = await browser.PagesAsync();
            
           if (pages.Length > 0)
            {
                page = pages[0];
            }
            else
            {
                page = browser.NewPageAsync().Result;
            }

            await page.SetUserAgentAsync("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36");
            await page.SetJavaScriptEnabledAsync(true);

            await page.GoToAsync(url);
            Console.ReadKey();
```

### Expected behavior:

Wait for a countdown of 5sec then get redirected to the website.

### Actual behavior:

Wait for a countdown of 5sec then the page reload and countdown starts again.

### Versions

* Which version of PuppeteerSharp are you using? 
2.0.4

* Which .NET runtime and version are you targeting? 
.NET Core 3.1

Thank you in advance!

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.

**Comment by Prologh** [comment]
Bumping this as it still occurs.

**Comment by MathboyL3** [comment]
I'm having the same issue... I've already tried a bunch of things
