### ISSUE TITLE
.NET Core 3.1 in Windows 10 with chrome Win64-706915 failed to load 

### ISSUE THREAD

**Issue by unruledboy** [hardkoded/puppeteer-sharp#1577]
**Before you file a bug, have you:**

* Tried upgrading to newest version of PuppeteerSharp, to see if your issue has already been resolved and released? Yes
* Checked existing open *and* closed [issues](https://github.com/kblok/puppeteer-sharp/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported? Yes
* Tried reproducing your problem in a new isolated project? Yes
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/search?q=puppeteer-sharp). It's bug

### Description

Failed to launch the headless chrome, with exception saying "chrome_elf.dll" is missing. Tried to copy the one from the latest version of chrome, then it gave this error:

> PuppeteerSharp.ProcessException: 'Failed to launch Base! [1022/073224.428:ERROR:icu_util.cc(183)] Couldn't mmap icu data file
> [1022/073224.429:FATAL:icu_util.cc(359)] Check failed: result. 
> Backtrace:
> 	ovly_debug_event [0x00007FFDC3161252+16183762]
> 	ovly_debug_event [0x00007FFDC3160832+16181170]
> 	ovly_debug_event [0x00007FFDC3173383+16257795]
> 	ovly_debug_event [0x00007FFDC32BE28C+17613324]
> 	ovly_debug_event [0x00007FFDC30DD76B+15644395]
> 	ovly_debug_event [0x00007FFDC3108D4E+15822030]
> 	ovly_debug_event [0x00007FFDC30DD35E+15643358]
> 	ovly_debug_event [0x00007FFDC31083E3+15819619]
> 	ovly_debug_event [0x00007FFDC31082BB+15819323]
> 	ovly_debug_event [0x00007FFDC31080F2+15818866]
> 	ChromeMain [0x00007FFDC21F11B6+286]
> 	Ordinal0 [0x00007FF7C54B275F+10079]
> 	Ordinal0 [0x00007FF7C54B182D+6189]
> 	GetHandleVerifier [0x00007FF7C55BB7C2+697538]
> 	BaseThreadInitThunk [0x00007FFE6E9C7034+20]
> 	RtlUserThreadStart [0x00007FFE7045CEC1+33]
> 

### Complete minimal example reproducing the issue

Installed latest version of PuppeteerSharp in a brand new .NET Core 3.1 console project, with the following code:
```
		static async Task Main(string[] args)
		{
			await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
			var browser = await Puppeteer.LaunchAsync(new LaunchOptions
			{
				Headless = true
			});
			var page = await browser.NewPageAsync();
			await page.GoToAsync("http://www.google.com");
		}
```

It gave the following exception:

---------------------------
chrome.exe - System Error
---------------------------
The code execution cannot proceed because C:\Users\Foo\source\repos\TestPuppeteer\TestPuppeteer\bin\Debug\netcoreapp3.1\.local-chromium\Win64-706915\chrome-win\chrome_elf.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------

After clicking ok, it gave this error message:

> PuppeteerSharp.ProcessException: 'Failed to launch Base! '

And the stack trace:

>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at PuppeteerSharp.LauncherBase.State.StartingState.<StartCoreAsync>d__5.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at PuppeteerSharp.LauncherBase.State.StartingState.<StartCoreAsync>d__5.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
>    at PuppeteerSharp.Launcher.<LaunchAsync>d__7.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at PuppeteerSharp.Launcher.<LaunchAsync>d__7.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at TestPuppeteer.Program.<Main>d__0.MoveNext() in C:\Users\Foo\source\repos\TestPuppeteer\TestPuppeteer\Program.cs:line 12
> 
> 

### Expected behavior:

It should not throw exception and the code functions as expected.

### Actual behavior:

It throws exception and failed to launch the headless chrome.

### Versions

* Which version of PuppeteerSharp are you using:  **2.0.4**
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0:  **.NET Core 3.1**

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

It downloaded file "download-Win64-706915.zip" and the complete list is this:

![image](https://user-images.githubusercontent.com/682883/96782882-17356a00-1439-11eb-9991-1e6d3835baaf.png)

**Comment by unruledboy** [comment]
I manually downloaded the latest version of chromium from the official website (https://download-chromium.appspot.com/) and copied all the files to the chrome-win folder, then it is working

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
