### ISSUE TITLE
How to get HTML and properties of control?

### ISSUE THREAD

**Issue by bbhxwl** [hardkoded/puppeteer-sharp#1585]
var list = await page.QuerySelectorAllAsync("a");
                        foreach (var item in list)
                        {
                          var v=  item.GetPropertyAsync("value");
                        }

**Comment by Meir017** [comment]
@bbhxwl looks like you posted the solution? 

I think this should be moved to [stackoverflow](https://stackoverflow.com/search?q=puppeteer-sharp)
