### ISSUE TITLE
Feature Request: .NET5 Support

### ISSUE THREAD

**Issue by litan1106** [hardkoded/puppeteer-sharp#1586]
.NET 5 released.

https://devblogs.microsoft.com/dotnet/announcing-net-5-0/

**Comment by kblok** [comment]
@litan1106 PuppeteerSharp is netstandard2.0. It should work with .NET 5

**Comment by litan1106** [comment]
> @litan1106 PuppeteerSharp is netstandard2.0. It should work with .NET 5

Yes, it works but .NET 5 is the future. 
https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/

**Comment by kblok** [comment]
@litan1106 time will tell.
If we move to .NET 5 we will leave a lot of people out. netstandard is just an interface. If you use it on a .NET 5 project it will run crazy fast :)

**Comment by jzabroski** [comment]
@kblok I think the ask should be for the tests to pass on `net5.0` TFM, see: 

https://github.com/hardkoded/puppeteer-sharp/blob/master/lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj#L4

**Comment by kblok** [comment]
We can for sure do that @jzabroski  :)

**Comment by jzabroski** [comment]
The reason this is important is complicated and I've been arguing with Immo Landwerth about this for awhile, but basically, two nuget packages don't necessarily compose well especially when across TFMs and FrameworkReference dependencies.  The easiest way to pseudo-guarantee compatibility is to provide various TFM targets so that the end user can trick the compiler into choosing the right dependencies.  But a good cheap way to cut down on issues is to just have all packages run their test suite against "HEAD, GLOBALLY", which is net5.0 for now.

**Comment by jzabroski** [comment]
Updated previous reply

**Comment by kblok** [comment]
We can start changing the TFM on the test project and wait for user feedback. We had some huge headaches with .NET Framework and .NET Core, but we solved that with the right tests and some optional tweaks. I hope .NET 5.0 will be a friendly partner.

**Comment by jzabroski** [comment]
I think if you run into issues, DM me on Twitter.  I know that Microsoft wants to limit headaches, so would be good to pass consolidated feedback.  Counter-examples are the best way to instruct better design at times.

**Comment by kblok** [comment]
Thanks for the insight @jzabroski! 
I will try your scenario tomorrow. My focus now is on https://github.com/microsoft/playwright-sharp. 
Let's keep in touch :)

**Comment by jzabroski** [comment]
Neat, Just saw Playwright Sharp.  Have you been in touch with the person behind AbotX?  The main pain point with robotic automation APIs is sometimes you need a real web browser, and other times you can just do a headless test.  And there is no uniform API across all the scenarios.

**Comment by kblok** [comment]
I never heard about AbotX. PlaywrightSharp is part of the Playwright family https://playwright.dev/. We are doing pretty cool things there :)

**Comment by jzabroski** [comment]
The guy behind AbotX is super friendly in my limited experience.
