### ISSUE TITLE
PagesAsync does not return current list of pages after opened a new tab

### ISSUE THREAD

**Issue by RileyCodes** [hardkoded/puppeteer-sharp#1587]
PagesAsync always return only two tabs from following code, if a user clicked a link and opens a new tab, the new tab does not appear from PagesAsync. issue occur when there is an infinite loop

in actual project, I am experiencing this issue after I executed some JS code to click a link and wait for a new page to appear in a loop by polling with PagesAsync

is this a bug or am I doing something wrong? 

Code to reproduce:

```
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = false,
                DefaultViewport = null
            });
            var page = await browser.NewPageAsync();
            await page.GoToAsync("https://github.com/");

            for (; ; )
            {
                var res = await browser.PagesAsync();
                int xxxx = 0;//make a breakpoint here and see res from debugger
            }

```

**Comment by RileyCodes** [comment]
a strange fix would be add another await operation before PagesAsync

works just fine:
```
                var ver = await browser.GetVersionAsync();
                var pages = await browser.PagesAsync();
```

**Comment by ojundi** [comment]
Thank you for the work around.. saved me bunch of additional headache..

**Comment by a-jiang** [comment]
神奇。有效

**Comment by a-jiang** [comment]
神奇。有效

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
