### ISSUE TITLE
Browser Launch option Arg "--remote-debugging-address=0.0.0.0" triggers Exception

### ISSUE THREAD

**Issue by gfaessler** [hardkoded/puppeteer-sharp#1588]
### Description
Browser Launch option arg "--remote-debugging-address=0.0.0.0" triggers Exception

```csharp
string[] args = new[] { "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9523" };
                    using (Program.Browser = await Puppeteer.LaunchAsync(new LaunchOptions { Headless = true, Args = args }))
                    {
                        using (var page = await Program.Browser.NewPageAsync())
                        {                                                                                   
                            await page.GoToAsync("https://www.puppeteersharp.com/");
                            await page.WaitForSelectorAsync("h1#puppeteer-sharp");                                                        
                        }
                    }
```

### Expected behavior:
"--remote-debugging-address=0.0.0.0" should be possible to listen on all interfaces
### Actual behavior:
ArgumentException : IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. 

### Versions

* PuppeteerSharp 2.0.4
* .Net Core 3.1

**Comment by kblok** [comment]
Hey @gfaessler, why do you need to set those values?

**Comment by gfaessler** [comment]
Well I would like to be able to connect to remote debugger from several others machines

**Comment by kblok** [comment]
What's your scenario? Can't you use ConnectAsync?

**Comment by gfaessler** [comment]
Well I would like to automate some tasks using a puppeteersharp page and then connect to the page using Chrome to perform some checks manually. This is why I thought to use remote debugging. I have to check if browserless.io allows this.

**Comment by gfaessler** [comment]
I confirm it works perfectly using ConnectAsync
