### ISSUE TITLE
Using (Browser browser = await Puppeteer.ConnectAsync()) causes Browser to close when disposed

### ISSUE THREAD

**Issue by gfaessler** [hardkoded/puppeteer-sharp#1589]
### Description
When using (Browser browser= await Puppeteer.ConnectAsync()) to connect to an existing chromium browser, the entire chromium browser closes when the browser.Dispose() method is called

### Complete minimal example reproducing the issue
```csharp
browserURL = "http://localhost:9222";
using (Browser browser = await Puppeteer.ConnectAsync(new ConnectOptions { BrowserURL = browserURL }))
{
    using (var page = await browser.NewPageAsync())
    {                           
        await page.GoToAsync("https://github.com/hardkoded/puppeteer-sharp");
        Thread.Sleep(3000);
    } // Here the page closes
} // !! Here the remote browser closes !!
```

### Expected behavior:
Remote browser should not be closed, only runtime ressource should be released. Several tabs could be open on the remote browser.

### Actual behavior:
Remote browser closes

### Versions
PuppeteerSharp 2.0.4
.Net Core 3.1

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
