### ISSUE TITLE
Improve WaitForResponseAsync(Func<Response, Boolean>, WaitForOptions)

### ISSUE THREAD

**Issue by d668** [hardkoded/puppeteer-sharp#1591]
The example 
```
var response = await page.WaitForResponseAsync(response => response.Url === "http://example.com" && response.Status === HttpStatus.Ok;
return response.Url;
```
doesn't work, not C# for sure and even if I correct, still doesn't

The example is actually here https://www.puppeteersharp.com/api/PuppeteerSharp.Page.html

**Comment by d668** [comment]
and the next example 
```
var firstResponse = await page.WaitForResponseAsync("http://example.com/resource");
return firstResponse.Url;
```
doesn't work either. I am getting `System.TimeoutException: 'Timeout of 30000 ms exceeded'`

**Comment by kblok** [comment]
Are you sure you are not calling WaitForResponseAsync too late?

**Comment by d668** [comment]
It seems pretty straightforward according to the [test case](https://github.com/hardkoded/puppeteer-sharp/blob/master/lib/PuppeteerSharp.Tests/PageTests/WaitForResponseTests.cs#L17)
Just navigate to any image URL with Page.WaitForResponseAsync

            var imgUrl = "https://avatars2.githubusercontent.com/u/2198466";
            await page.WaitForResponseAsync(imgUrl);

I also updated the link to the example https://www.puppeteersharp.com/api/PuppeteerSharp.Page.html, there is JS there with ===. Probably was missed and not converted to C#.

**Comment by kblok** [comment]
@d668 can you post a test breaking?

**Comment by d668** [comment]
public static async Task Do()
        {
            await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = false,
            });
            var page = (await browser.PagesAsync()).First();
            var imgUrl = "https://avatars2.githubusercontent.com/u/2198466";
            await page.WaitForResponseAsync(imgUrl);

        }

**Comment by d668** [comment]
or am I supposed to do something like this? Which also doesn't work
  ```
      public static async Task Do1()
        {
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                ExecutablePath = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
                Headless = false,
            });
            var page = (await browser.PagesAsync()).First();
            //var url = "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4";
            var url = "https://avatars2.githubusercontent.com/u/2198466";
            byte[] buff;
            var task = page.WaitForResponseAsync(response => 
                 {
                     buff = response.BufferAsync().Result;
                     return true;
                 }
           );

            await page.GoToAsync(url);
            await Task.WhenAny(task);
        }
```

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
