### ISSUE TITLE
WaitForNavigationAsync always fail after click

### ISSUE THREAD

**Issue by zxstack** [hardkoded/puppeteer-sharp#1593]
```
//Clicking raise the page to refresh
await page.ClickAsync("#selector-id-example"); 

//I can wait for a specific element, but I want to use waitfornavigationasync as well.
await page.WaitForNavigationAsync(); 
```

I have tested this on several sites
This does not work when the page is reloaded or moved after clicking

**How to use waitfornavigationasync to wait for the page to finish loading caused by a click?**

Event Type Moniker	Event	Time	Duration	Thread
	Exception thrown: '**System.TimeoutException**' in mscorlib.dll ("Timeout of 30000 ms exceeded") Exception thrown: 'System.TimeoutException' in mscorlib.dll ("Timeout of 30000 ms exceeded") Hyperlink: Activate Historical Debugging	137.46s		[29976] Main Thread

**Comment by kblok** [comment]
I would wrap both tasks into a WhenAll

```cs
await Task.WhenAll(
  page.WaitForNavigationAsync(),
  page.ClickAsync("#selector-id-example"));
```

**Comment by zxstack** [comment]
Thank you for your help !!
