### ISSUE TITLE
If no  Page.Request event handler is specified,  await page.SetRequestInterceptionAsync(true) causes the browser to hang

### ISSUE THREAD

**Issue by d668** [hardkoded/puppeteer-sharp#1594]
### Description

If no  `Page.Request +=` event handler is specified,  `await page.SetRequestInterceptionAsync(true);` causes the browser to hang

### Complete minimal example reproducing the issue

        public static async Task Do()
        {
            await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = false,
            });
            var page = (await browser.PagesAsync()).First();
            await page.SetRequestInterceptionAsync(true);
            await page.GoToAsync("https://www.google.com/");
        }

### Expected behavior:

I would assume it shouldn't hang just because there is no event handler defined

### Actual behavior:

It hangs

### Versions

* Which version of PuppeteerSharp are you using? 2.0.4
* Which .NET runtime and version are you targeting? 4.8

**Comment by kblok** [comment]
If you use `SetRequestInterceptionAsync(true)`, you need to implement `Page.Request +=`  to intercept the request and at least call `ContinueAsync`.

**Comment by d668** [comment]
imho this shouldn't be designed this way, there is no compile warning, the issue is basically undetectable. The advantage of C# is compile time warnings and all the logic that supports fast development. In this case I have to remember to comment this like if I commented another one. Can if be fixed?

**Comment by kblok** [comment]
A few thoughts.
1. Not all the usage errors are solved by the compiler. If so, we would live in a bug-free world :)
2. PuppeteerSharp is a port of Puppeteer. If Puppeteer hangs we hang.
3. I don't see many people falling into this trap. If you want to intercept a request you have to implement the event. It wouldn't make any sense to set SetRequestInterception if you don't want to intercept.

**Comment by d668** [comment]
does Puppeteer hang?

**Comment by kblok** [comment]
it does

**Comment by d668** [comment]
Compiler warning would be nice at least. Node is a constant pain, that's why we use C# over here

**Comment by KoalaBear84** [comment]
Well, I did also went down this rabbit hole and was lost for maybe an hour why it didn't work anymore :)

I wouldn't mind that it throws and exception when SetRequestInterceptionAsync is set but no event handler is set. But maybe that could break something indeed. Just wanted to let you know that you are not alone :)

**Comment by kblok** [comment]
Thank you for sharing that @KoalaBear84 😉

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
