### ISSUE TITLE
Get newest Chromium stable revision id

### ISSUE THREAD

**Issue by KoalaBear84** [hardkoded/puppeteer-sharp#1595]
Continuation from https://github.com/microsoft/playwright-sharp/issues/1045

### Description

What's the best way to get the newest Stable release revision id?

### Complete minimal example reproducing the issue

1. http://omahaproxy.appspot.com/
2. See Win x64 stable at branch_base_position 812852
3. But this revision is not on https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/

### Expected behavior:

A way to determine the correct revision, that you are sure that it is the stable one, and not a maybe beta/dev/canary one.

### Actual behavior:

It can't find the 812852 because it's not on the website.

### Versions

* Which version of PuppeteerSharp are you using?

Newest.

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.

.NET Framework 4.7.2 (currently), but doesn't matter for this issue.

**Comment by kblok** [comment]
Why don't you download the required version with `BrowserFetcher`?

**Comment by KoalaBear84** [comment]
You mean the default? There is no option to do like:

```c#
await new BrowserFetcher().DownloadAsync("87.0.4280.88");
```

**Comment by kblok** [comment]
The revision used by the latest version is `706915`. Why don't you use that?

**Comment by KoalaBear84** [comment]
That's Chromium 79.0.3945.0 from December 11, 2019, almost a year ago, and I like to keep a little up to date 😂

**Comment by kblok** [comment]
You could try `818858`. But I'm not 100% sure

**Comment by KoalaBear84** [comment]
With 818858 I get 88.0.4298.0.

OK, thanks, then I know it's not that I'm missing something. ✌
