### ISSUE TITLE
Chrome.exe never closes

### ISSUE THREAD

**Issue by effyteva** [hardkoded/puppeteer-sharp#1597]
Hi,

We're constantly running into issues on our production environment,
Puppeteer seems to leave some chrome.exe processes open (even after we close our .NET process completely).
We're creating the Browser Instance with a "using" syntax: using var Browser = await Puppeteer.LaunchAsync.
We're also creating new pages with the same syntax: using var Page = await Browser.NewPageAsync();

Is there any other scenario which might leave the chrome.exe process open?

We're using the latest release from NuGet (2.0.4) on .NET Core 5.0, on a Windows server.

Thank you for your help,
Effy

**Comment by jzabroski** [comment]
@effyteva Can you try something like this? https://stackoverflow.com/a/7189381/1040437

The idea is to kill all processes spawned by your process that launches browses via Puppeteer.

You can put this in the shutdown event.

**Comment by effyteva** [comment]
Hi @jzabroski
I could try that, but it won't really help in our case,
Our software (Windows Service) is always running, and should automatically open and close chrome instances. We can't afford restarting our service and killing all chrome instances on some interval. We would rather solve the issue that's causing chrome instances to remain open.

**Comment by fr4gles** [comment]
We has similar issue and ended up with workaround - we are monitoring processes running under our main process and killing periodically not needed ones.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.

**Comment by danielgindi** [comment]
This could be solved if we get the process id of the instance of Chrome, and add it to a JobObject (Windows Only) that's owned by the current process.

**Comment by danielgindi** [comment]
I use this JobObject class:
https://github.com/jmderuty/JobObject.Net/blob/master/JobObject.Net/Job.cs

And I do this:
```cs
private static Stormancer.JobManagement.Job wpJob = null;

// Before creating the browser, one time - do this:
if (wpJob == null)
  wpJob = new Stormancer.JobManagement.Job();

// And immediately after calling Puppeter.LauncAsync:
if (System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.Windows))
{
    try
    {
        if (newBrowser.Process != null && !newBrowser.Process.HasExited)
        {
            wpJob.AddProcess(newBrowser.Process);
        }
    }
    catch
    {
    }
}
```

@kblok This is worth putting in the notes somewhere. Work perfectly for me, especially when using `--single-process`.
