### ISSUE TITLE
Cannot get form data from waitforrequestasync

### ISSUE THREAD

**Issue by AnshimDev** [hardkoded/puppeteer-sharp#1599]
**Before you file a bug, have you:**

* Tried upgrading to newest version of PuppeteerSharp, to see if your issue has already been resolved and released?
* Checked existing open *and* closed [issues](https://github.com/kblok/puppeteer-sharp/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* Tried reproducing your problem in a new isolated project?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/search?q=puppeteer-sharp).

### Description

[Description of the issue]

Cannot get the postdata from request if payload/postdata is form data.
### Complete minimal example reproducing the issue
var tst = await page.WaitForRequestAsync("https://example.com")
var formData = tst.PostData.ToString(); (expected formdata as string but I get null instead).
                        
Complete means the code snippet can be copied into a unit test method in a fresh C# project and run.
Minimal means it is stripped from code not related to reproducing the issue.

E.g.

```csharp
// Arrange
var options = new LaunchOptions { /*  */ };
var chromiumRevision = BrowserFetcher.DefaultRevision;
var browser = await Puppeteer.LaunchAsync(options, chromiumRevision);
var page = browser.NewPageAsync();

// Act
var tst = await page.WaitForRequestAsync("https://example.com")
var formData = tst.PostData.ToString();
```

### Expected behavior:

[What you expect to happen]

Expected to get a string with the form data.
### Actual behavior:

[What actually happens]

I get always null.

### Versions

* Which version of PuppeteerSharp are you using?
2.0.4
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
NET 5
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by AnshimDev** [comment]
I want to mention that this behavior is happening only with request of resource type "fetch" which only accepts json as posdata and not binary...

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
