### ISSUE TITLE
missing handleSIGTERM in launch options

### ISSUE THREAD

**Issue by clement128** [hardkoded/puppeteer-sharp#1600]
It seems don't support all launch options yet compare with puppeteer nodejs version. (https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteerlaunchoptions)

And `handleSIGTERM` I think it's quite important if running on some autoscale platform for example Kubernetes.

**Comment by kblok** [comment]
I didn't find a solid way of supporting that using the .NET API. But I'm willing to see PRs covering this feature.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
