### ISSUE TITLE
Add chrome extension docs

### ISSUE THREAD

**Issue by jzabroski** [hardkoded/puppeteer-sharp#1603]
https://github.com/hardkoded/puppeteer-sharp/pull/1602#issuecomment-747850968

**Comment by jzabroski** [comment]
@kblok I don't understand how adding the docs in the location you suggest causes it to update puppeteersharp.com?

**Comment by kblok** [comment]
You create an MD file (like the ones we have there).  You add the entry in the toc.yml file. And when we ship a new version the site will be updated.

**Comment by jzabroski** [comment]
Got it.  the toc.yml is the part I was missing.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
