### ISSUE TITLE
Some Chinese symbols are grabled, when you're using PdfAsync() method;

### ISSUE THREAD

**Issue by rodion-andreev-d8** [hardkoded/puppeteer-sharp#1605]
### Description

Some of Chinese letters are grabled after PDF creating.

### Complete minimal example reproducing the issue

Please try with these chinese symbols 屯門區 entered on your page in browser. And after that use Puppeteer and take PdfDataAsync method.
// Arrange
 await using var browser = await Puppeteer.LaunchAsync(new LaunchOptions
                {
                    Headless = true
                });
 await using var page = await browser.NewPageAsync();
                if (headers != null && headers.Any())
                {
                    await page.SetExtraHttpHeadersAsync(headers);
                }

                await page.SetJavaScriptEnabledAsync(true);

                var navigationOptions = new NavigationOptions {
                    WaitUntil = new[]
                    {
                        WaitUntilNavigation.Load,
                        WaitUntilNavigation.Networkidle2
                    }
                };
                await page.GoToAsync(url, navigationOptions);

// Act
var pdfData = await page.PdfDataAsync(new PdfOptions 
                { 
                    PrintBackground = true,
                    FooterTemplate = footerTemplate,
                    DisplayHeaderFooter = true,
                    MarginOptions = new PuppeteerSharp.Media.MarginOptions
                    {
                        Bottom = "100px"
                    }
                });

// Assert

### Expected behavior:

屯門區 instead of those squres with crosses shown on screenshot

### Actual behavior:
![image](https://user-images.githubusercontent.com/66254512/102788322-8127ac80-43b3-11eb-96c3-464fd52e46fd.png)

### Versions

Version of PuppeteerSharp is 2.0.4
 .NET runtime and version is .NET Core 3.1.

**Comment by kblok** [comment]
@rodion-andreev-d8 do you get that if you print to PDF using Chrome?

**Comment by rodion-andreev-d8** [comment]
@kblok 
![image](https://user-images.githubusercontent.com/66254512/102795163-7b36c900-43bd-11eb-9140-12461b9700cf.png)
all internally

**Comment by kblok** [comment]
But, do you get that if you print to PDF using Chrome navigating the page manually?

**Comment by rodion-andreev-d8** [comment]
@kblok More info. When i run this app locally using Visual Studio all is working well. When a build it using docker i catch that issue. 
this is a part of dockerfile
![image](https://user-images.githubusercontent.com/66254512/102800930-a02f3a00-43c5-11eb-820c-1114ff8aa286.png)

**Comment by venky8951** [comment]
Hi @kblok I feel since we are using Convert.FromBase64String() we may encounter this problem can we try Encoding.Unicode.GetBytes() in [ ProtocolStreamReader.cs](https://github.com/hardkoded/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Helpers/ProtocolStreamReader.cs) ReadProtocolStreamByteAsync()
Guide me if I'm on right path, if we can do this to fix this issue

**Comment by kblok** [comment]
I'm not quite sure @venky8951. We are getting the content of the PDF there, not the text itself.

**Comment by rodion-andreev-d8** [comment]
@kblok @venky8951 SOLVED. We had to use new fonts for asian symbols.
we/ve updated like here
![image](https://user-images.githubusercontent.com/66254512/102914106-deddf680-4490-11eb-9a06-edbeb56fb3c3.png)

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
