### ISSUE TITLE
Unable to extract browser zip on mounted file share in Linux

### ISSUE THREAD

**Issue by emanuel-virca** [hardkoded/puppeteer-sharp#1612]
### Description

The BrowserFetcher is unable to extract the zip files if the working directory is set to a mounted file storage [(Mount a file share to a Python function app using Azure CLI)](az webapp config storage-account add) attached to azure function running on Linux with dotnet runtime.

Environment: Azure function running in Linux with mounted file share

### Expected behavior:

The zip should be extracted successfully regardless the fact that the destination folder is on a mounted file share in linux

### Actual behavior:

The DownloadAsync method of the BrowserFetcher throws the following exception

`Failed to process the message with error:{"ClassName":"System.UnauthorizedAccessException","Message":"Access to the path '/mounted/Linux-706915/chrome-linux/crashpad_handler' is denied.","Data":null,"InnerException":{"ClassName":"System.IO.IOException","Message":"Operation not permitted","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":null,"RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":1,"Source":null,"WatsonBuckets":null},"HelpURL":null,"StackTraceString":" at System.IO.FileStatus.SetAccessOrWriteTime(String path, DateTimeOffset time, Boolean isAccessTime)\n at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)\n at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)\n at System.IO.Compression.ZipFileExtensions.ExtractRelativeToDirectory(ZipArchiveEntry source, String destinationDirectoryName, Boolean overwrite)\n at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName, Boolean overwriteFiles)\n at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)\n at PuppeteerSharp.BrowserFetcher.DownloadAsync(Int32 revision)\n at .....`

### Versions

* Which version of PuppeteerSharp are you using?
* v2.0.4
* Which .NET runtime and version are you targeting? 
*  .NET Core 3.1

### Additional Information

The unzipping works if the working directory is set to temp folder of VM and not a mounted file share.
If I manually execute code of the NativeExtractToDirectory, the extraction works.
It also works if I extract the library using third party library like SharpZipLib.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
