### ISSUE TITLE
Unable to create new page with headless and relative userdatadir path

### ISSUE THREAD

**Issue by ogendogen** [hardkoded/puppeteer-sharp#1613]
### Description

There is a problem with creating new page with headless=true and custom userdatadir relative path options. Application freezes on line with method creating new page. Problem occurs only with certain options and only relative path, for other combinations it works fine.

### Complete minimal example reproducing the issue

```csharp
var options = new LaunchOptions
{
    Headless = true,
    UserDataDir = "./UserData"
};

string startPage = "https://google.com";

Console.WriteLine("Downloading chromium");
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);

Console.WriteLine("Navigating to start page");

using (var browser = await Puppeteer.LaunchAsync(options))
using (var page = await browser.NewPageAsync())
{
    await page.GoToAsync(startPage, WaitUntilNavigation.Networkidle0);
    Console.WriteLine("Opened!");
}

Console.ReadKey();
```

### Expected behavior:

Open new page with headless and custom userdatadir relative path

### Actual behavior:

Application freezes on creating new page step (checked with debugger)

### Versions

* Which version of PuppeteerSharp are you using?
2.0.4
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
.NET Core 3.1

### Additional Information

Tested it with Windows 7 / Windows 10 with clear project (debug/release as well) and got the same result.
Code works fine with headless=false:

```csharp
var options = new LaunchOptions
{
    Headless = false,
    UserDataDir = "./UserData"
};
```
Works without UserDataDir:
```csharp
var options = new LaunchOptions
{
    Headless = false
};
```
Works with absolute path:
```csharp
var options = new LaunchOptions
{
    Headless = true,
    UserDataDir = @"C:\Users\Marcin\Source\Repos\TestPuppeteer\TestPuppeteer\bin\Debug\netcoreapp3.1\UserData"
};
```

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
