### ISSUE TITLE
Is there a method of waiting for page load?

### ISSUE THREAD

**Issue by scott-david-walker** [hardkoded/puppeteer-sharp#1615]
I can't see anywhere in the docs where I can wait for a page to render without having to pass in selectors as arguments etc

Is there a simple method?

**Comment by kblok** [comment]
Hey @scott-david-walker how do you normally know that the page is rendered?

**Comment by scott-david-walker** [comment]
Well, I'm presuming there would be a method of knowing when a page is loaded without having to pass in elements. If you look at PaperPlane.io as an example. If you render their example document of https://www.paperplane.app/examples/invoice it looks different if you render it with their tool (Which according to their FAQ is Puppeteer) and PuppeteerSharp (style differentiation etc). 

I suppose what I'm looking for is a time delay? Wait x seconds etc?

**Comment by kblok** [comment]
You could try something like this:

```
await Page.GoToAsync("https://www.paperplane.app/examples/invoice", WaitUntilNavigation.Networkidle0);
```

**Comment by scott-david-walker** [comment]
Unfortunately I have the same issue. In the Paperplane example the background of the word "paid" is green and that appears to be missed in PuppeteerSharp. Also the case with sites where images take a little longer to load. 
Is there anything else that I could try?

**Comment by kblok** [comment]
Are you generating a PDF? If so, did you enabled the print background color?

**Comment by scott-david-walker** [comment]
That's solved the issue. Sorry, I completely missed that in the docs :-)

Thank you very much for your quick help :-)
