### ISSUE TITLE
puppeteer-sharp downloads old version of chromium

### ISSUE THREAD

**Issue by LastTribunal** [hardkoded/puppeteer-sharp#1617]
### Description
When puppeteer runs (windows 10) it downloads Win64-706915 version of chrome

### Complete minimal example reproducing the issue
Get latest nuget of puppeteer-sharp and run any code that will cause the download of chromium
Observe the above version is being downloaded (from 10/17/2019)

**Comment by Androbin** [comment]
> By default, Puppeteer downloads and uses a specific version of Chromium so its API is guaranteed to work out of the box. To use Puppeteer with a different version of Chrome or Chromium, pass in the executable's path when creating a Browser instance.
