### ISSUE TITLE
puppeteersharp Error: Execution context was destroyed, most likely because of a navigation.

### ISSUE THREAD

**Issue by andrew2558** [hardkoded/puppeteer-sharp#1618]
Since the page is automatically redirected to the oauth login page when I visit the page, I want to automatically enter the username on the new login page, but when I execute the TypeAsync or EvaluateFunctionAsync method I get this error, I think it is caused by the page jump.

Error: Execution context was destroyed, most likely because of a navigation.

**Comment by kblok** [comment]
@andrew2558 as you mentioned. That might happen if you try to interact with an element from a page that was disposed.

**Comment by andrew2558** [comment]
thanks  @kblok  , For the elements in the new page I visited, does each page have a context? If the page jumps, how to get the context of the new page?

**Comment by kblok** [comment]
It's about getting the elements you want to interact with after the navigation. Basically don't keep elements between navigations.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
