### ISSUE TITLE
LaunchAsync using "--incognito" args creates a new BrowserContext window when invoking NewPageAsync()

### ISSUE THREAD

**Issue by johnearnshaw** [hardkoded/puppeteer-sharp#1623]
### Description

When using --incognito flag to launch a new Chromium instance with PuppeteerSharp opens an Incognito browser window but Browser.DefaultContext.IsIncognito returns false. Browser.NewPageAsync() opens a new browser window that is not incognito instead of opening a new page tab in incognito mode.

### Complete minimal example reproducing the issue

```csharp
using System;
using System.Linq;
using System.Threading;
using PuppeteerSharp;

namespace PuppeteerIncognitoTest
{
    class Program
    {
        static EventWaitHandle BlockingHandle = new EventWaitHandle(false, EventResetMode.AutoReset);
        static Browser Browser;

        static void Main(string[] args)
        {
            var fetcher = new BrowserFetcher();

            if (!fetcher.LocalRevisions().Contains(BrowserFetcher.DefaultRevision))
            {
                var result = fetcher.DownloadAsync(BrowserFetcher.DefaultRevision).Result;
            }

            Browser = Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = false,
                Args = new[] {
                    "--incognito"
                },
            }).Result;

            Console.WriteLine("IsIncognito = " + Browser.DefaultContext.IsIncognito);
            var page = Browser.NewPageAsync().Result;
            BlockingHandle.WaitOne();
        }
    }
}
```

### Expected behavior:

1) A Chromium Browser should launch in incognito mode (This is the correct and working behavior).
2) A new page should open within the incognito browser window (This does not work and opens a new window instead).

### Actual behavior:

1) A Chromium Browser launches in incognito mode.
2) Invoking Browser.NewPageAsync() opens a new non-incognito BrowserContext window and a new non-incognito page within the newly created BrowserContext.

### Versions

* PuppeteerSharp 2.0.4
* Chrome/79.0.3945.0
* .NET Core 2.0.

**Comment by kblok** [comment]
This looks like an upstream issue.
