### ISSUE TITLE
Create a tool to tell us what tests we are missing

### ISSUE THREAD

**Issue by Androbin** [hardkoded/puppeteer-sharp#1652]
Let's create a console tool to grab the attributes created on #1655 and create a report.
This could be a good start https://github.com/microsoft/playwright-sharp/blob/main/src/tools/PlaywrightSharp.Tooling/IdentifyMissingTests.cs

**Comment by Androbin** [comment]
I have written some Python code that should do the trick:
https://gist.github.com/Androbin/3357c03613cf422de3e49e92e4498c40

**Comment by kblok** [comment]
Attributes proved to be effective on Playwright-Sharp. e.g. https://github.com/microsoft/playwright-sharp/blob/main/src/PlaywrightSharp.Tests/BrowserContextAddCookiesTests.cs#L20. Where is clear what's the target test. I think we should start with that and then with the compare tool. We could mimic the tool we have in PlaywrightSharp as well https://github.com/microsoft/playwright-sharp/blob/main/src/tools/PlaywrightSharp.Tooling/IdentifyMissingTests.cs

**Comment by Androbin** [comment]
The test names are basically the same, except for spaces, punctuation and case. My idea was to normalize the test names from both projects and compare them. If we keep this convention, we don't necessarily need the attributes.

**Comment by kblok** [comment]
@Androbin you could try that approach first and see how solid it could be.

**Comment by Androbin** [comment]
> We could mimic the tool we have in PlaywrightSharp as well https://github.com/microsoft/playwright-sharp/blob/main/src/tools/PlaywrightSharp.Tooling/IdentifyMissingTests.cs

Can we just copy that tool license-wise?

**Comment by kblok** [comment]
We can. PlaywrightSharp is highly inspired on pptr# as well :)
