### ISSUE TITLE
Detect __puppeteer_evaluation_script__ on other site

### ISSUE THREAD

**Issue by caffreysbb** [hardkoded/puppeteer-sharp#1664]
bet365 detect puppeteer. I guess that's because of this prefix. The bet365 website, when opened through the puppeteer, starts an infinite loop. Tricks 
```csharp
Object.defineProperty(navigator, 'webdriver', {get: () => undefined,});
Object.defineProperty(navigator, 'languages', {
get: () => ['ru-Ru', 'ru'] });
```
and other don't work.

I found a code demo link - https://github.com/digitalhurricane-io/puppeteer-detection-100-percent

in the puppeteer-extra, this is implemented as follows - https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js

but I can't port to C#.

**Comment by kblok** [comment]
That's something you can implement with pptr#
