### ISSUE TITLE
Concurrently modified lists not thread-safe

### ISSUE THREAD

**Issue by Androbin** [hardkoded/puppeteer-sharp#1680]
https://github.com/hardkoded/puppeteer-sharp/blob/984fdc06a564e8ded3071a703f83d5dce1627696/lib/PuppeteerSharp/DOMWorld.cs#L19
https://github.com/hardkoded/puppeteer-sharp/blob/984fdc06a564e8ded3071a703f83d5dce1627696/lib/PuppeteerSharp/Frame.cs#L49
https://github.com/hardkoded/puppeteer-sharp/blob/984fdc06a564e8ded3071a703f83d5dce1627696/lib/PuppeteerSharp/Frame.cs#L80
https://github.com/hardkoded/puppeteer-sharp/blob/984fdc06a564e8ded3071a703f83d5dce1627696/lib/PuppeteerSharp/NetworkManager.cs#L26
https://github.com/hardkoded/puppeteer-sharp/blob/984fdc06a564e8ded3071a703f83d5dce1627696/lib/PuppeteerSharp/Helpers/MultiMap.cs#L9

**Comment by Androbin** [comment]
@kblok What's the "`ConcurrentList`" implementation of your choice?

**Comment by Androbin** [comment]
If order is not important, we can use `ConcurrentBag<T>`

**Comment by kblok** [comment]
Do we have any reported bug around this?

**Comment by kblok** [comment]
Do you think all these should be thread-safe?

**Comment by Androbin** [comment]
I have looked at each and every list in the library and assessed whether they might be accessed/modified concurrently and whether that may be a problem. See https://github.com/hardkoded/puppeteer-sharp/issues/1681#issuecomment-813072742 for the kinds of problems this may cause.

**Comment by Androbin** [comment]
In fact `WaitTasks` could explain #1670.

**Comment by Androbin** [comment]
`_attemptedAuthentications` is modified concurrently for numerous network requests and you shouldn't be surprised to see it break. It may randomly cancel requests and I have observed errors that might have caused by it but it's difficult to confirm.

**Comment by Androbin** [comment]
`MultiMap` is used in `AsyncDictionaryHelper`, which is specifically designed to be thread-safe, but it may break in unexpected ways, due to the unsynchronized lists within the otherwise synchronized dictionary.

**Comment by Androbin** [comment]
`LifecycleEvents` is not very likely to cause problems, but it may prevent a page from reporting the `load` event.

**Comment by Androbin** [comment]
`Frame.ChildFrames` might lose frames, which is clearly not desirable.

**Comment by Androbin** [comment]
`NetworkManager._attemptedAuthentications` could be a `ConcurrentBag` or a `ConcurrentDictionary` used as a `Set`.
The overhead should be negligible.

**Comment by kblok** [comment]
Let's try to go little by little and see how the code behaves.

**Comment by kblok** [comment]
@Androbin do you think we can close this?

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
