### ISSUE TITLE
Concurrently modified dictionary not thread-safe

### ISSUE THREAD

**Issue by Androbin** [hardkoded/puppeteer-sharp#1681]
https://github.com/hardkoded/puppeteer-sharp/blob/984fdc06a564e8ded3071a703f83d5dce1627696/lib/PuppeteerSharp/Page.cs#L43

**Comment by kblok** [comment]
Does it need to be?

**Comment by Androbin** [comment]
It's modified by `OnAttachedToTargetAsync` and `OnDetachedFromTarget`, both of which may be called concurrently for multiple workers

**Comment by Androbin** [comment]
https://stackoverflow.com/a/9301533

**Comment by kblok** [comment]
Can we close this @Androbin ?

**Comment by Androbin** [comment]
@kblok See #1696
