### ISSUE TITLE
PuppeteerSharp 3.0.0 with PublicSign fails under shadow copy

### ISSUE THREAD

**Issue by leonardo-fernandes** [hardkoded/puppeteer-sharp#1691]
### Description

We are using PuppeteerSharp inside of a web application, and the version 3.0.0 fails to load the PuppeteerSharp.dll assembly:

`System.IO.FileLoadException: 'Could not load file or assembly 'PuppeteerSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=db12f80f85d8ba23' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key.`

From what I could understand, this arises from trying to load a public signed assembly in an AppDomain that is using shadow copy. This document highlights the unsupported scenarios for public signed assemblies: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/public-signing.md

A public signed assembly has the public key information, but no signature. You seem to have committed the `keypair.snk` into the repository, so you could instead be distributing a signed assembly. To make this change, you would need to replace `public.snk` by `keypair.snk`, and disable public signing with `<PublicSign>false</PublicSign>` on the `SignAssembly.props` file. I can submit a PR if you want.

I suspect this won't introduce binary incompatibility, since the public key will match with that of version 3.0.0. But that needs proper testing.

### Complete minimal example reproducing the issue

```csharp
AppDomain.CurrentDomain.SetShadowCopyFiles();
Assembly a = Assembly.LoadFrom("PuppeteerSharp.dll");
```

### Expected behavior:

PuppeteerSharp assembly loads in the context of a web application

### Actual behavior:

PuppeteerSharp assembly fails to load in the context of a web application

### Versions

Using PuppeteerSharp 3.0.0 and targeting .NET framework 4.7.2.

**Comment by kblok** [comment]
PR is welcome @leonardo-fernandes :)
