### ISSUE TITLE
PuppeteerSharp.EvaluationFailedException: Execution context was destroyed, most likely because of a navigation

### ISSUE THREAD

**Issue by ovolkov** [hardkoded/puppeteer-sharp#1692]
**Description**
It throws exception only when it's executed from code. Running the same script in browser console works fine:
goto link [https://www.zillow.com/captchaPerimeterX/?url=%2fhomes%2f&uuid=12d145a0-9798-11eb-b86e-b333bf5d74a4&vid=9508e9f9-9780-11eb-a149-0242ac120003](https://www.zillow.com/captchaPerimeterX/?url=%2fhomes%2f&uuid=12d145a0-9798-11eb-b86e-b333bf5d74a4&vid=9508e9f9-9780-11eb-a149-0242ac120003)

`await page.ReloadAsync();
await page.WaitForNavigationAsync();
var js="document.getElementById("g-recaptcha-response").value=\"03AGdBq27UIr9zjY3QIrVGGmjNSFgFOaRzK04ndNPpdX-PYgKLSQLxyirVwLFnwe7ANCZ-87qzf3dSZiXXWdH6oa80DlySrjhB9RZ9D4u2omiRxub2lMYzf0-yJtE77fqOfhokEknzXfliDaY7Nk44_9G8f_WwIMADykRL1vE39WinWKW3kkwGdRn0UuPicO0aDZqiUStHG_FawNwSLKcpd3ImaJPTWuapyaNq3jGvf96AGQs_DmwkVVjX-IiZHCtlAjhDarppDDw0n3FZEzz0Bef8uVYQXZ0i8zeYy8ScK986nlkF4sbNfuPeJ5JTtAwUfnx1Kacv1RVbod1jSVtzvKoMHH0sgK7Jx6ICQ49oi_wym8e5O7-LZGs-pLgDhdH3ia06rDycMYrMwSOViBFdhtpL7-jLC9px1lFFwezGq7lbxSOp4vkojPhfvRhtUMAdqp6MVa5w8G6t3cQ-ti1n3FVvO2WDMX1h7YhNKsZfvhhFkwNNDALcABauClmGVKLmjOreaSiCnNxSSqLTvyJpneLd9dA2F_22Ag\"";
 var elem = await page.EvaluateExpressionAsync(js);`

**Error**
`PuppeteerSharp.EvaluationFailedException: Execution context was destroyed, most likely because of a navigation.
 ---> PuppeteerSharp.MessageException: Execution context was destroyed, most likely because of a navigation.
   at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 157
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 109
   at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 182
   --- End of inner exception stack trace ---`

**Versions**

Using PuppeteerSharp 3.0.0 and .net core 5.0

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
