### ISSUE TITLE
Making queryselectoraasync wait for return seems to be deadlocked. Here is my usage

### ISSUE THREAD

**Issue by wulincheng** [hardkoded/puppeteer-sharp#1702]
using Page page = _browser.NewPageAsync().ConfigureAwait(false).GetAwaiter().GetResult();
                page.Load += (sender, e) =>
                {
                    try
                    {
                        var _page = (Page)sender;
                        if (string.IsNullOrEmpty(isTagName)) return;
                        
                        var tag = page.QuerySelectorAsync(isTagName).ConfigureAwait(false).GetAwaiter().GetResult();//There's a deadlock here

                        if (tag == null) return;
                        page.ScreenshotAsync(savePath, new ScreenshotOptions() { Type = ScreenshotType.Png }).ConfigureAwait(false).GetAwaiter().GetResult();
                    }
                    catch (Exception ex)
                    {
                       
                    }
                };
                page.SetViewportAsync(new ViewPortOptions
                {
                    Width = width,
                    Height = height
                }).ConfigureAwait(false);
                page.GoToAsync(url).ConfigureAwait(false).GetAwaiter().GetResult();

**Comment by wulincheng** [comment]
> 你为什么用这么多，你不能代替他们吗？`GetAwaiter().GetResult()``await`

**Comment by kblok** [comment]
PlaywrightSharp is an async library. You should async all the way if not you will have issues like this.
