### ISSUE TITLE
Improve AddStyleTagAsync(String)

### ISSUE THREAD

**Issue by InhumanPwnage** [hardkoded/puppeteer-sharp#1706]
Explain how would you like this document to be impoved.
Source URL: https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Page.cs/#L732

This method has the same explanation as the other one which takes AddTagOptions object.

In this case since it is a URL, what kind of URL? One which loads a file locally via file://? One which loads a file from the web?

Where does it even store the styling in the page object so we can check whether the styling as been loaded properly?

Thanks and regards

**Comment by kblok** [comment]
That's the `stylesheel url`. It will add something like this on the page:

```
<link rel="stylesheet" href="the_url_you_passed">
```

If the browser can process your `file://` that will load.

**Comment by InhumanPwnage** [comment]
Thanks for the clarification kblok :)
