### ISSUE TITLE
Add option to strip sourceURL from scripts injected by puppeteer

### ISSUE THREAD

**Issue by Androbin** [hardkoded/puppeteer-sharp#1709]
I have ported the `puppeteer-extra-plugin-stealth` package to PuppeteerSharp, with the exception of the `sourceURL` evasion:
https://github.com/berstend/puppeteer-extra/blob/master/packages/puppeteer-extra-plugin-stealth/evasions/sourceurl/index.js

The other evasions rely on `evaluateOnNewDocument` and can easily be port (I recommend `EnqueueAsyncMessages = true`).
This evasion relies on monkey-patching `page._client.send`, which can't easily be ported. A flag would come in handy here.

The relevant file is [`ExecutionContext.cs`](https://github.com/hardkoded/puppeteer-sharp/blob/master/lib/PuppeteerSharp/ExecutionContext.cs)

```csharp
private Task<RemoteObject> EvaluateExpressionInternalAsync(bool returnByValue, string script)
    => ExecuteEvaluationAsync("Runtime.evaluate", new Dictionary<string, object>
    {
        ["expression"] = _sourceUrlRegex.IsMatch(script) ? script : $"{script}\n{_evaluationScriptSuffix}",
        ["contextId"] = _contextId,
        ["returnByValue"] = returnByValue,
        ["awaitPromise"] = true,
        ["userGesture"] = true
    });

private Task<RemoteObject> EvaluateFunctionInternalAsync(bool returnByValue, string script, params object[] args)
    => ExecuteEvaluationAsync("Runtime.callFunctionOn", new RuntimeCallFunctionOnRequest
    {
        FunctionDeclaration = $"{script}\n{_evaluationScriptSuffix}\n",
        ExecutionContextId = _contextId,
        Arguments = args.Select(FormatArgument),
        ReturnByValue = returnByValue,
        AwaitPromise = true,
        UserGesture = true
    });
```

**Comment by kblok** [comment]
What if the connection could raise some event to patch the JSON that is about to be sent?

**Comment by Androbin** [comment]
I suppose that could work.

**Comment by Androbin** [comment]
Actually, I would rather patch the `CDPSession` than the `Connection`.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
