### ISSUE TITLE
showing warning on downloadasync code

### ISSUE THREAD

**Issue by MohammadAnsari98** [hardkoded/puppeteer-sharp#1714]
**showing warning for line which is copied from documentation**

###  I'm using puppeteer with .net 5 and visual studio 2019 community edition when I try this line from docs

`            await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
*` 

### i get this warning

![warning](https://user-images.githubusercontent.com/25693849/118326336-191c6300-b51a-11eb-97c3-7bdfc942aba6.PNG)

**Comment by kblok** [comment]
We don't need the DefaultRevision anymore :) 
Leaving this issue opened so we can update the docs
