### ISSUE TITLE
How to enable cookies for browser session?

### ISSUE THREAD

**Issue by dahanj95** [hardkoded/puppeteer-sharp#1715]
Hi.

I have a webpage I'm visiting which after the initial navigation to different page, it's showing me "checking your browser, please wait 5 seconds.." because I don't have cookies enabled in the controlled browser session. My question is, how do I enable cookies? Is it done at launch with `LaunchOptions`? Thanks.

**Comment by kblok** [comment]
How's that you don't have cookies enabled?

**Comment by dahanj95** [comment]
> How's that you don't have cookies enabled?

Heh, my bad. Seems like I needed to enable a flag in the browser arguments in order to bypass cloudflare protection in a certain website I'm automating.

When I've gotten the browser check phase, I viewed the page source and it showed me in the markup a warning that I needed to enable cookies.

**Comment by kblok** [comment]
@dahanj95 you will need to write automation code to click on the accept button if you get a cookies warning.

**Comment by dahanj95** [comment]
> @dahanj95 you will need to write automation code to click on the accept button if you get a cookies warning.

I'm not talking about the cookie policy overlay, it was just a page which refreshed itself every five seconds and blocked my automation from continuing.

**Comment by dahanj95** [comment]
Ok, there's a new problem on a different website. When I navigate to the search form and accept cookie policy, I can no longer continue automation. I get `Exception thrown: 'PuppeteerSharp.EvaluationFailedException' in mscorlib.dll` when i'm using `TypeAsync` targeting a specific selector based on its `id`.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.

**Comment by jvarela07** [comment]
So I noticed one site always gives it to me in puppeteersharp and never asks for it when I try going to the site using Brave or google chrome.
