### ISSUE TITLE
Unable To get puppeteer sharop working

### ISSUE THREAD

**Issue by Shogo175R** [hardkoded/puppeteer-sharp#1720]
hi.
i'm doing some test to understand how to work with the API and i'm trying the example of the screenshot

```
var browserFetcher = new BrowserFetcher();
await browserFetcher.DownloadAsync();
await using var browser = await Puppeteer.LaunchAsync(
    new LaunchOptions { Headless = true });
await using var page = await browser.NewPageAsync();
await page.GoToAsync("http://www.google.com");
await page.ScreenshotAsync(outputFile);
```

well, looks that at await browserFetcher.DownloadAsync(); the console app exit with 0 code, without any kind of error... what i missing up?

**Comment by kblok** [comment]
File permissions? Network errors? many things might happen.

**Comment by Shogo175R** [comment]
solved, with 

`            ServicePointManager.SecurityProtocol =
                SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
            ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;`
