### ISSUE TITLE
conflict when run multiple project that use browser

### ISSUE THREAD

**Issue by Flynns82** [hardkoded/puppeteer-sharp#1721]
I have two projects running on the same pc, both use puppeteer-sharp. 
The first takes data every second from different sites.
The second instead every half hour / hour, solves a redirect.
For the second i use it inside a using, unlike the first that I instantiate it publicly since I need the pages to be called from different classes in different sequences. 
I noticed, however, that when the second starts the browser to perform its function, the first stops working. 
it's normal? how can i solve the problem?

**Comment by kblok** [comment]
You could try passing a different debugging port to each one using the `--remote-debugging-port` argument

**Comment by Flynns82** [comment]
`bw = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
                Args = new[] { "--remote-debugging-port:9666" }
            });
            i`
i've added this argument but when i try to start the browser it gives me this error:

PuppeteerSharp.ProcessException
  HResult=0x80131500
  Message=Failed to launch browser! [0614/191635.569:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL isswiftshader
