### ISSUE TITLE
How to wait for a promise in puppeteer-sharp?

### ISSUE THREAD

**Issue by Shogo175R** [hardkoded/puppeteer-sharp#1723]
i'm having some problems with my application close event. where i'm going to stop all created browser instance and pages, but an navigation error exception will be throwed because some tasks was running i suppose, there is a way to wait for it?

**Comment by kblok** [comment]
Do you have any code example I can use to reproduce it?

**Comment by Shogo175R** [comment]
hi, actually there is no much to show because what i'm currently doing is to close all (page and browser) during an await of query selector by doing this 

`        private async Task CloseAll()
        {            
            if( _tokenSource != null )
            {
                _tokenSource.Cancel();               
            }

            var page =
                _page;
            _page = null;
            if (page != null)
            {
                await page.CloseAsync();
            }

            var browser =
                _browserPuppeteer;
            _browserPuppeteer = null;

            if( browser != null )
            {
                //browser.Disconnect();

                await browser.CloseAsync();
            }
        }
`

**Comment by kblok** [comment]
I would try to catch that exception on close.
