### ISSUE TITLE
::marker pseudo-class is ignored

### ISSUE THREAD

**Issue by sanishtjppi** [hardkoded/puppeteer-sharp#1724]
First of all, thank you for making such a nice product. I am using it for generating PDFs in my projects. An issue I noticed when I pass a particular CSS property, 

```
ol li::marker {
  color: rgb(117, 154, 199);
  display: inline-block;
  width: 1em;
  margin-left: -1em;
}
```

::marker pseudo-class is ignored.

`ul li::before { content: "•"; color: rgb(117, 154, 199); display: inline-block; width: 1em; margin-left: -1em; } ` works fine though. I had tested this on both Chrome and Chromium and ::marker is showing up as expected, so my doubt is on puppeteer.

**Comment by kblok** [comment]
Ignored for styling or as a CSS selector?

**Comment by sanishtjppi** [comment]
The styles inside the ::marker are not applied on the PDF. If I save the HTML and CSS used for generating the PDF, and open it in Chrome or Chromium, I can see the ::marker class applied.

**Comment by kblok** [comment]
That might be an issue with the PDF renderer from Chromium. Can you confirm that it is working if you print that page to PDF using Chrome?

**Comment by sanishtjppi** [comment]
Works fine when print and saved as a PDF from both chrome and chromium.

**Comment by sanishtjppi** [comment]
Currently, in the docker container on the server, I have Chrome CHROME_VERSION="81.0.4044.138-1". I had tried to use the latest chrome[91.0.4472.114], and after the 1st PDF generation, it stops working for some reason. I had to use CHROME_VERSION="81.0.4044.138-1". Is there any Chrome version that puppeteer-sharp recommends, and if yes, where can I find that info?

**Comment by kblok** [comment]
This piece of code worked for me.

```cs
using var browser = await Puppeteer.LaunchAsync();
using var page = await browser.NewPageAsync();
await page.GoToAsync("https://www.w3schools.com/css/tryit.asp?filename=trycss_marker");

Console.WriteLine("Generating PDF");
await page.PdfAsync(Path.Combine(Directory.GetCurrentDirectory(), "bullets.pdf"));
```


![image](https://user-images.githubusercontent.com/2198466/123008639-9fd22480-d391-11eb-8317-307e7d2260e6.png)

**Comment by sanishtjppi** [comment]
My API looks like this,

```
       [HttpPost]
        public async Task<IActionResult> Post([FromBody] RequestObject req)
        {
            try
            {
                
                using (var browser = await Puppeteer.LaunchAsync(new LaunchOptions
                {
                    Headless = true,
                    Args = new[] {   "--no-sandbox",
                        "--disable-setuid-sandbox", }                   
                }))
                using (var page = await browser.NewPageAsync())
                {
                    await page.SetContentAsync("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=2.0\"><meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\"></head><body>" + req.Html + "</body></html>");
                    await page.AddStyleTagAsync(new AddTagOptions()
                    {
                        Content = req.Css
                    });

                    var stream = await page.PdfStreamAsync();
                    return new FileStreamResult(stream, "application/pdf");
                }            

                
            }
            catch (Exception ex)
            {

                return BadRequest(ex);
            }

        }
```

Let me try your method.

**Comment by sanishtjppi** [comment]
Same result. Didn't work for me. Could be the difference in chromium versions. in my test code, I am pointing to, `public const int DefaultRevision = 706915;` Is there any difference between my Chromium and yours?

**Comment by kblok** [comment]
I'm using the default one. Are you getting the same outside docker?

**Comment by sanishtjppi** [comment]
yes.

**Comment by kblok** [comment]
hmm no idea.

**Comment by sanishtjppi** [comment]
tried your code and still no luck.

![image](https://user-images.githubusercontent.com/86326292/123010857-43144100-d374-11eb-8c64-58bca120263f.png)

**Comment by sanishtjppi** [comment]
Everything worked when I updated the puppeteer-sharp to version 4. Now Chromium is 848005. in my docker, which version of Chrome can I install to get this working? I already have puppeteer-sharp 4.0 in my docker project. My chrome version inside docker is 81.0.4044.138-1.

**Comment by sanishtjppi** [comment]
Finally, I got it working from Docker. As you said in the beginning, it was the issue with the old chrome version. Now I am using Chrome 88.0.4324.96 inside docker and everything seems to work. I had to track the 848005 chromium version release date and used a chrome version in that month. The latest chrome seems not to work well with Puppeteer.
