### ISSUE TITLE
How to port puppeteer code to PuppeteerSharp for find WebSocket information

### ISSUE THREAD

**Issue by zydjohnHotmail** [hardkoded/puppeteer-sharp#1727]
Hello:
I have to write some C# code to get Sec-WebSocket-Key information for WebSocket connection, so I can use some WebSocket packages to send and receive the underlying WebSocket data.
I found the following Node code can get some useful information:

var puppeteer = require('puppeteer');

async function run() {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  await page.goto('http://powerline.io');
  const cdp = await page.target().createCDPSession();
  await cdp.send('Network.enable');
  await cdp.send('Page.enable');

  const printResponse = response => console.log('response: ', response);

  cdp.on('Network.webSocketFrameReceived', printResponse); // Fired when WebSocket message is received.
  cdp.on('Network.webSocketFrameSent', printResponse); // Fired when WebSocket message is sent.
}

run();

So, I want to port the above code to PuppeteerSharp (version 4.0), but I don’t know how to do this for the last 3 statements:
  const printResponse = response => console.log('response: ', response);
  cdp.on('Network.webSocketFrameReceived', printResponse); 
  cdp.on('Network.webSocketFrameSent', printResponse); 

Please advise.

**Comment by kblok** [comment]
@zydjohnHotmail you can listen to the `MessageReceived` event. There you can add a switch.

```
var client = await Page.Target.CreateCDPSessionAsync();
await client.SendAsync("Network.enable");
var events = new List<object>();

client.MessageReceived += (_, e) =>
{
    if (e.MessageID == "Network.requestWillBeSent")
    {
        events.Add(e.MessageData);
    }
};
```

**Comment by zydjohnHotmail** [comment]
Hello:
I modified my code according to your advice:
        static void Main()
        {
            _Browser = await Puppeteer.LaunchAsync(gui_launch_option);
            _Page = await _Browser.NewPageAsync();
            NavigationOptions options =
                new() { Timeout = (int)TimeSpan.FromSeconds(120).TotalMilliseconds };
            await _Page.SetViewportAsync((new ViewPortOptions
            { Width = 1920, Height = 3939 }));
            await _Page.GoToAsync("http://powerline.io", options);
            CDPSession client = await _Page.Target.CreateCDPSessionAsync();
            await client.SendAsync("Network.enable");
            var events = new List<object>();
            while (true)
            {
                client.MessageReceived += (_, e) =>
                {
                    if (e.MessageID == "Network.requestWillBeSent")
                    {
                        events.Add(e.MessageData);
                    }
                };
            }
        }

But my code did NOT work, as the client has no MessageReceived, therefore, the events has no elements.
But the Node JS code works.
Let me know how to fix the issue.
Thanks,

**Comment by kblok** [comment]
`MessageReceived` is an event, you shouldn't put that into a while loop.

**Comment by zydjohnHotmail** [comment]
Hello:
I also tried not to put it in a while loop, but I got the same result: nothing.
If you know how to get the result, please share your code.
Thanks,
