### ISSUE TITLE
Improve EvaluateExpressionAsync<T>(String)

### ISSUE THREAD

**Issue by shazam19** [hardkoded/puppeteer-sharp#1768]
Please add some example code with explanation how it works. e.g. if I add a lambda script how do I return value from it?

Source URL: https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Page.cs/#L1395

**Comment by kgar** [comment]
@kblok Is this something I could do? I've made excessive use of this method and could write up an example 😁

**Comment by kblok** [comment]
Got for it @kgar!
