### ISSUE TITLE
PuppeteerSharp CORS issue

### ISSUE THREAD

**Issue by johnstaveley** [hardkoded/puppeteer-sharp#1770]
This is not a CORS issue as the issue ONLY occurs in puppeteersharp and does not happen in any browser.
I have a problem which is only apparent when using Chromium 898563 in PuppeteerSharp using the following arguments:

    "--no-sandbox", "--headless", "--disable-gpu", "--disable-dev-shm-usage"

    "When I attempt to access the following resource:"

CDN: https://cdn2.mysite.com/fonts/glyphicons-halflings-regular.woff2

    "I get the following Error Message:"

Access to font at 'https://cdn2.mysite.com/fonts/glyphicons-halflings-regular.woff2' from origin 'https://hitachiat300.staged.excelwraps.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check

I attempted to solve the issue useing the headers shown below — as well as all combinations of them — on the site that is trying to access the resource.
Headers:

        <add name="Access-Control-Allow-Origin" value="*" />
        <add name="Access-Control-Allow-Methods" value="DELETE, POST, GET, PUT, OPTIONS" />
        <add name="Access-Control-Allow-Headers" value="Access-Control-Allow-Origin, Access-Control-Allow-Methods, Accept, Content-Type, Access-Control-Allow-Headers, Access-Control-Allow-Credentials, Authorization, X-Requested-With" />
        <add name="Access-Control-Allow-Credentials" value="false" />

...and I still get an error like the one shown above. I cannot reproduce the error in puppeteer, chromium, or any other browser. It seems to me that this is a PuppeteerSharp issue.
I have tried all of the solutions that were suggested in this 
https://stackoverflow.com/questions/53298478/has-been-blocked-by-cors-policy-response-to-preflight-request-doesn-t-pass-acce#53298478%20
https://stackoverflow.com/questions/50614397/value-of-the-access-control-allow-origin-header-in-the-response-must-not-be-th

I Use the Following Versions:

    PdfSharpCore 1.2.17
    PuppeteerSharp 4.0.0

The only solution that mitigates the issue is to use puppeteer with the following argument:

"--disable-web-security"

I find this solution unacceptable as it poses several major security risk (the name of the flag speaks for its-self). It is an argument that shouldn't be needed.

**Comment by kblok** [comment]
Can you share some code to test?

**Comment by johnstaveley** [comment]
I tried creating a bare bones test project to reproduce the issue but can't
