### ISSUE TITLE
performance issues with the FW

### ISSUE THREAD

**Issue by yakiginz** [hardkoded/puppeteer-sharp#1771]
Hi, 
Observing significant degradation in performance moving from dev machine to production: for example, same 6 HTML pages, when rendered to PDF moved from 2 seconds on 4 core dev machine on win10 to 10 seconds on 8 core win 2019 production server.  
Using Puppeteer sharp ver 2.0.4. 
Any suggestions for improvements? 
Much obliged, Yaki

**Comment by kblok** [comment]
No clue
