### ISSUE TITLE
Open Chromium with C# App window as parenting host

### ISSUE THREAD

**Issue by lsgIT-HH** [hardkoded/puppeteer-sharp#1772]
Hello,

would it be somehow possible to launch Chromium controlled by Puppeteer hosted inside my applications window?

I mean similar to something like this  

    Process p = Process.Start("chromium.exe");
    p.WaitForInputIdle();
    SetParent(p.MainWindowHandle, panel1.Handle);

Thanks in advance.

Regards
Lars

**Comment by kblok** [comment]
I think I'd rather experiment with something like WebView2. But I didn't try that out.
