### ISSUE TITLE
SetContentAsync won't load local images

### ISSUE THREAD

**Issue by pauljame** [hardkoded/puppeteer-sharp#1773]
Hello,

I am trying to generate a PDF from a Razor View using SetContentAsync. 
Everything works great except the image does not load.

 ```
await using var browser = await Puppeteer.LaunchAsync(new LaunchOptions
  {
          Headless = true,
          ExecutablePath = PuppeteerExtensions.ExecutablePath
  });
```

```
  await using var page = await browser.NewPageAsync();
  await page.EmulateMediaTypeAsync(MediaType.Screen);     

  await page.SetContentAsync("<div><img src='~/images/test.png' style='width: 186px'/><h1>Hello</h1><h2 style='color: red; text-align: center;'>Greetings </h2></div>");

  var pdfContent = await page.PdfStreamAsync(new PdfOptions
  {                
         Format = PaperFormat.A4,
         PrintBackground = true
  });
```

Here are a complete sample using Razor view, same problem : https://github.com/pmchlk/pdfgenerator

Any idea?

**Comment by Androbin** [comment]
The image URL is resolved to `chrome://new-tab-page/~/images/test.png`

**Comment by Androbin** [comment]
Try something like `file:///home/pauljame/images/test.png`

**Comment by Androbin** [comment]
Try something like `file:///home/pauljame/images/test.png`

**Comment by Androbin** [comment]
Note that by default, Chrome will say "Not allowed to load local resource".
To fix that, launch Chrome with these flags: `--allow-file-access-from-files --disable-web-security`

**Comment by tolgabalci** [comment]
A fantastic example of how to make Puppeteer-Sharp work with ASP.NET razor pages, thank you @pauljame !

After much tinkering, I think embedding the images into the page the best way to go. I realize this is not desired as any new images would require code changes, but for basic forms where there are limited images, I think it is an acceptable solution.

**Here are the changes I made:**

Added to InvoiceViewModel:
`public string LogoBase64 { get; set; }`

Changed the image in InvoiceViewModel to use:
`<img src="data:image/jpeg;base64,@Model.LogoBase64"`

Then in PrintController:
First inject the environment:
```
private readonly IWebHostEnvironment _environment;

public PrintController(ITemplateService templateService, IWebHostEnvironment environment)
{
    _templateService = templateService ?? throw new ArgumentNullException(nameof(templateService));
    _environment = environment;
}
```

Then set LogoBase64 as such:
`LogoBase64 = Convert.ToBase64String(System.IO.File.ReadAllBytes(Path.Join(_environment.WebRootPath, @"images\logo.png"))),
`

**Comment by roolek** [comment]
The problem is that SetContentAsync applies content to an empty page, which is about:blank. The browser does not allow loading local files on a page that is not local (does not have file:// at the beginning). The solution is to first navigate to an empty local HTML page and then use SetContent.

```csharp
  await page.GoToAsync($"file://{currentDir}/Templates");
  await page.SetContentAsync(htmlContent);

**Comment by sanathe06** [comment]
> The problem is that SetContentAsync applies content to an empty page, which is about:blank. The browser does not allow loading local files on a page that is not local (does not have file:// at the beginning). The solution is to first navigate to an empty local HTML page and then use SetContentAsync.
> 
>   await page.GoToAsync($"file://{currentDir}/Templates/local-empty-page.html");
>   await page.SetContentAsync(htmlContent);

this works for me. had same issue.

`public async Task<byte[]> GeneratePdfFromTemplate(Dictionary<string, object> data)
    {
        var emptyPagePath = Path.Combine(_templateRoot, "local-empty-page.html");
        var templatePath = Path.Combine(_templateRoot, "base-template.html");
        var html = await File.ReadAllTextAsync(templatePath);
        html = BindData(html, data);
        await new BrowserFetcher().DownloadAsync();
        using var browser = await Puppeteer.LaunchAsync(new LaunchOptions
        {
            Headless = true,
            Args = new[] { "--no-sandbox" } // For Linux environments
        });
        using var page = await browser.NewPageAsync();

        // Set base URL for images
        await page.GoToAsync($"file://{emptyPagePath}");
        await page.SetContentAsync(html, new NavigationOptions
        {
            WaitUntil = new[] { WaitUntilNavigation.Networkidle0 }
        });

        return await page.PdfDataAsync(new PdfOptions
        {
            Format = PaperFormat.A4,
            DisplayHeaderFooter = true,
            MarginOptions = new MarginOptions
            {
                Top = "0mm",
                Bottom = "0mm",
                Left = "0mm",
                Right = "0mm"
            },
            PrintBackground = true
        });
    }`
