### ISSUE TITLE
Cannot fetch Firefox

### ISSUE THREAD

**Issue by snowphantom** [hardkoded/puppeteer-sharp#1775]
Hi,

I'm trying to run automatic testing with Firefox, when I start to fetch Firefox and launch it, I got an exception with message: **"The remote server returned an error: (404) Not Found."**. My puppeteer-sharp version is latest (4.0.0.0). Maybe the download link have been deprecated.

![image](https://user-images.githubusercontent.com/69063602/125152279-c526a700-e175-11eb-9607-3cedbf940d72.png)
![image](https://user-images.githubusercontent.com/69063602/125152290-e7b8c000-e175-11eb-9a86-2b9b4f09e6fe.png)

Any ideas? Thanks!

Regards,
Hung Nguyen

**Comment by kblok** [comment]
I will fix this and ship 4.1 :)
