### ISSUE TITLE
[Firefox] function 'TypeAysnc' not work

### ISSUE THREAD

**Issue by snowphantom** [hardkoded/puppeteer-sharp#1779]
Hi,

I have updated my version to 5.0.0 and I have problem with function **TypeAsync**. When I called it, Firefox browser just typed first character in content to Url bar and crashed, It looked like:

![image](https://user-images.githubusercontent.com/69063602/125200020-2728fe80-e293-11eb-9abf-bac29f7361b3.png)

_Bonus:_
I launch Firefox browser, and try to execute some basic functions, Debugger write many exceptions about Newtonsoft.Json like this:

> Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
The thread 0x3518 has exited with code 0 (0x0).
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll
console.error: 
  TypeError: can't access property "innerWindowId", this.window.windowGlobalChild is null: ExecutionContext@chrome://remote/content/cdp/domains/content/runtime/ExecutionContext.jsm:57:5
_onContextCreated@chrome://remote/content/cdp/domains/content/Runtime.jsm:489:21
_onScriptLoaded@chrome://remote/content/cdp/domains/content/Page.jsm:325:15
emit@resource://gre/modules/EventEmitter.jsm:160:20
handleEvent/<@chrome://remote/content/cdp/observers/ContextObserver.jsm:94:16
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll
Exception thrown: 'System.ArgumentException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll

Thank you!!!

Best regards,
Hung Nguyen

_Update 1:_ call TapAsync throw an exception, then app crash too.

**Comment by kblok** [comment]
We are moving to bidi. That will help. Closing.
