### ISSUE TITLE
UploadFileAsync is not working when pass aws s3 full file url as path param

### ISSUE THREAD

**Issue by mmitushevskiMelon** [hardkoded/puppeteer-sharp#1781]
Example: 
await UploadFileAsync(AWS_S3_Full_File_PathUrl).
How I am able to provide the path to file that is not stored on my local file system ?

**Comment by kblok** [comment]
You are automating a browser. The file should be in your local system, like when you use a browser.

**Comment by mmitushevskiMelon** [comment]
There is no an option to use external url example: https://image.shutterstock.com/image-vector/vector-yellow-sun-rays-glow-260nw-437252794.jpg ?

**Comment by kblok** [comment]
This is the API for file uploads https://www.puppeteersharp.com/api/PuppeteerSharp.FileChooser.html#PuppeteerSharp_FileChooser_AcceptAsync_System_String___

If you need to upload a file from AWS it should be 2 max 3 lines. You download a file and then you upload it.
