### ISSUE TITLE
CA1303 error isnt enforced as warning, cannot build.

### ISSUE THREAD

**Issue by Erik-Bard** [hardkoded/puppeteer-sharp#1782]
## Looking for some help? Get priority support by [sponsoring the project](https://github.com/sponsors/hardkoded)/

**Before you file a bug, have you:**

* Tried upgrading to newest version of PuppeteerSharp, to see if your issue has already been resolved and released?
* Checked existing open *and* closed [issues](https://github.com/kblok/puppeteer-sharp/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* Tried reproducing your problem in a new isolated project?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/search?q=puppeteer-sharp).

### Description

Tried to Supress and/or Configure again the issue #CA1303 and it is an error and cannot change in configure or work as warning as its configured when pulled from master, newest version. Causing 74 error messages and cannot build program. Errors are in PuppeteerSharp.sln.

### Complete minimal example reproducing the issue

Complete means the code snippet can be copied into a unit test method in a fresh C# project and run.
Minimal means it is stripped from code not related to reproducing the issue.

E.g.

```csharp
// Arrange
var options = new LaunchOptions { /*  */ };
var chromiumRevision = BrowserFetcher.DefaultRevision;
var browser = await Puppeteer.LaunchAsync(options, chromiumRevision);
var page = browser.NewPageAsync();

// Act
...

// Assert
...
```

### Expected behavior:

[What you expect to happen]

### Actual behavior:

[What actually happens]

### Versions

* Which version of PuppeteerSharp are you using?
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by kblok** [comment]
Let me see if I understand the issue.
You have a project, with the CA1303 turned on and you want to add the `csproj` of this project into your solution?

**Comment by Erik-Bard** [comment]
No, I fixed SA1622 and then when i tried to build i got 65 errors of type
CA1303 and i checked and it was set in config as warning, but VS gave me it
as errors which resulted in not being able to build.

tis 13 juli 2021 kl. 00:49 skrev Darío Kondratiuk ***@***.***

**Comment by kblok** [comment]
Are you using the Nuget package?

**Comment by Erik-Bard** [comment]
No, I cloned the project in order to help fix an Open source issue .


tis 13 juli 2021 kl. 01:01 skrev Darío Kondratiuk ***@***.***

**Comment by kblok** [comment]
CA1303 is explicitly set to none https://github.com/hardkoded/puppeteer-sharp/blob/076897d0cf627c947c61a1192fcb20d968d05cbc/lib/PuppeteerSharp.ruleset#L88 .

**Comment by Erik-Bard** [comment]
But as my issue states, i got 65 errors from it anyway.

tis 13 juli 2021 kl. 01:44 skrev Darío Kondratiuk ***@***.***

**Comment by kgar** [comment]
I have seen where errors appear in the Error List but do not appear in the Output panel's compilation results, so I still have a successful build even though there are style errors. Is that what is happening when you attempt to build? Or does the output panel also state that one of the projects failed?

Also, are you using an IDE when building the solution? If so, which one and which version?
