### ISSUE TITLE
How to support multiple languages on 1 page?

### ISSUE THREAD

**Issue by daikeung** [hardkoded/puppeteer-sharp#1783]
Would like to print multiple languages on a page like below, how to support this?
Thanks.

![Screenshot 2021-07-12 at 3 40 55 PM](https://user-images.githubusercontent.com/39689240/125423919-fdb5b507-9156-4137-aec9-dac159dd241a.png)

**Comment by kblok** [comment]
Is this a puppeteer question?

**Comment by daikeung** [comment]
Kind of, as I am using Puppeteer Sharp which is deployed to Azure Linux Functions. However, some characters could not be printed successfully there.

**Comment by kblok** [comment]
Ah got it. I think this should be reported on AZ. This is about the VM running the function.

**Comment by daikeung** [comment]
I reported to Azure support and they have no ideas yet. Thus, they asked me to ask here to see whether other people faced similar issues before with solutions. 
Please let me know if others know the solutions.
Thanks.
