### ISSUE TITLE
PuppeteerSharp Fails silently in Azure Function Linux Consumption Plan

### ISSUE THREAD

**Issue by jaltenbernd** [hardkoded/puppeteer-sharp#1787]
### Description

Wondering if anyone has tried using PuppeteeSharp in an Azure Function Linux Consumption Plan. I have it working, but now and then it will fail silently. It doesn't throw any errors. I added the arguments to my LaunchOptions. Unfortunately, I don't know where the logging would send to. 

### Complete minimal example reproducing the issue

```csharp
 browser = await PuppeteerSharp.Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
                ExecutablePath = browserPath,
                Args = new[] { "--enable-logging", "--v=1", "--no-sandbox" }
            });
```

### Expected behavior:

To log an error in Application Insights in Azure. 

### Actual behavior:

No errors are fired. Can't capture anything with a number of try/catch blocks. 

### Versions

* Which version of PuppeteerSharp are you using? 5.0.0
* Which .NET runtime and version are you targeting? .NET Core 3.1.1

👉  https://opencollective.com/puppeteer-sharp/donate -->

**Comment by kblok** [comment]
Did you try this recipe https://anthonychu.ca/post/azure-functions-puppeteer-pdf-razor-template/ ?

**Comment by jaltenbernd** [comment]
Yes. That's the very same article I used to setup my whole Linux Consumption Plan to use Puppeteersharp. My question is why does it fail intermittently when trying to open a new browser. Just curious if there's a way to capture these silent failures.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
