### ISSUE TITLE
What version of Puppeteer is PuppeteerSharp running?

### ISSUE THREAD

**Issue by gavin310** [hardkoded/puppeteer-sharp#1805]
In v9.0.0 of Puppeteer, the property `omitBackground` was added to the Page.pdf() method. Is PuppeteerSharp running Puppeteer v9.0.0 or greater so that this property can be used?

**Comment by kblok** [comment]
Hey @gavin310. We are in a limbo state right now. I'm trying to catch v9. I'm somewhere between v3 and v9.
But I think we could implement that property and ship a version for you :)

**Comment by gavin310** [comment]
@kblok Thank you for the offer! It actually wouldn't be for me personally, but for a service I use that uses PuppeteerSharp on the backend. I'll let them know. Thanks again!

**Comment by gavin310** [comment]
@kblok Understandably, the developers of the service would rather not use a side fork of PuppeteerSharp that's off of the main branch. Or did you actually mean you could add the `omitBackground` property to the master branch and release a new version?

Thanks again for the help!

**Comment by kblok** [comment]
@gavin310 we already have that property https://www.puppeteersharp.com/api/PuppeteerSharp.ScreenshotOptions.html#PuppeteerSharp_ScreenshotOptions_OmitBackground

**Comment by gavin310** [comment]
> @gavin310 we already have that property https://www.puppeteersharp.com/api/PuppeteerSharp.ScreenshotOptions.html#PuppeteerSharp_ScreenshotOptions_OmitBackground

Thanks for the response! I'm actually needing to render PDFs with transparent backgrounds, not screenshots. Sorry, I should've clarified that from the start. I do see that `omitBackground` is an option for Puppeteer's `page.screenshot` method, but from what I understand it was only added as an option for the `page.pdf` method recently in v9.0.0.

**Comment by kblok** [comment]
Implemented on #1812
Friendly reminder. You can now sponsor my work using [GitHub Sponsors](https://github.com/sponsors/kblok) 😊.

**Comment by gavin310** [comment]
@kblok That's amazing! Thanks!
