### ISSUE TITLE
Is there any way to be able to use puppeteer-extra-plugin-stealth plugin?

### ISSUE THREAD

**Issue by m-1s** [hardkoded/puppeteer-sharp#1817]
As you know, this plugin is very popular for is there any way to be able to use puppeteer. Do you have a way to use it in C#?

**Comment by kblok** [comment]
There are a few conversations about that [here](https://github.com/hardkoded/puppeteer-sharp/issues/1530) and [here](https://github.com/hardkoded/puppeteer-sharp/issues/1709).

**Comment by m-1s** [comment]
thanks @kblok , i found a great repo from your answer. It's resolved my problem.
Thanks you very much!
