### ISSUE TITLE
Need Support for Mac Arm64 (Apple Silicon) Chromium Builds

### ISSUE THREAD

**Issue by argentini** [hardkoded/puppeteer-sharp#1861]
### Description

Need Support for Mac Arm64 (Apple Silicon) Chromium Builds

### Complete minimal example reproducing the issue

n/a

### Expected behavior:

n/a

### Actual behavior:

n/a

### Versions

Latest

### Additional Information

n/a

**Comment by kblok** [comment]
Mi workspace is an M1 and I didn't have any issues with it...

**Comment by argentini** [comment]
@kblok We can't rely on Rosetta 2 being around forever. So it would be good to add the architecture as soon as it makes sense. Chromium is available for Mac_Arm64 in the same repository that Puppeteer uses today so they're ready to go.

**Comment by kblok** [comment]
@argentini I don't see puppeteer downloading an arm64 specific browser https://github.com/puppeteer/puppeteer/blob/main/src/node/BrowserFetcher.ts#L301

**Comment by argentini** [comment]
@kblok Yes, that's what I was saying. Puppeteer isn't downloading the Mac_Arm64 chromium browser yet, even though one is available. So I was wondering when the Puppeteer Sharp team would be getting around to adding support for it.

**Comment by Cheatoid** [comment]
Related: https://github.com/puppeteer/puppeteer/pull/7546/files

**Comment by argentini** [comment]
> Related: https://github.com/puppeteer/puppeteer/pull/7546/files

Nice. Hopefully they'll accept this pull request. Thanks @Cheatoid !

**Comment by montyclt** [comment]
> > Related: https://github.com/puppeteer/puppeteer/pull/7546/files
> 
> Nice. Hopefully they'll accept this pull request. Thanks @Cheatoid !

The pull request is accepted.

**Comment by kblok** [comment]
Shipped on v10.1.2
