### ISSUE TITLE
Cannot get browser context id (BrowserContextId)

### ISSUE THREAD

**Issue by deaktomi** [hardkoded/puppeteer-sharp#1877]
### Description

I would like to get the Browser Context's ID.

What I have is a reference for PuppeteerSharp.Browser that was initialized by connecting to an existing browser. I would like to get the Browser Context Id of the default context.

I see that the `browser` has a `DefaultContext` property and that has a `private readonly string _id` [field](https://github.com/hardkoded/puppeteer-sharp/blob/master/lib/PuppeteerSharp/BrowserContext.cs#L16).

I tried to get it with reflection, but it was `null`.

I also tried to get it through `Browser.Target` 's `TargetInfo` internal property, but it was also a piece of non initialized object.

### Complete minimal example reproducing the issue

```csharp
public async Task Connect()
{
	var browser = await Puppeteer.ConnectAsync(new ConnectOptions { BrowserWSEndpoint = WebSocketEndpoint, InitAction = InitAction}, null);
	
	var t = browser.DefaultContext.GetType();
	var fieldInfo = t.GetField("_id", BindingFlags.Instance | BindingFlags.NonPublic);
	var browserContextId = fieldInfo.GetValue(browser.DefaultContext) as string; // this sohuldn't be null
}

private void InitAction(PuppeteerSharp.Browser browser)
{
	var t = browser.DefaultContext.GetType();
	var fieldInfo = t.GetField("_id", BindingFlags.Instance | BindingFlags.NonPublic);
	var browserContextId = fieldInfo.GetValue(browser.DefaultContext) as string; // this sohuldn't be null
}
```

### Expected behavior:

I should be able to retrieve the browser context id

### Actual behavior:

Browser Context Id cannot be reached without reflection and after getting it with Reflection the value is `null`

### Versions

* PuppeteerSharp 6.0.0
* .NET Core 3.1

**Comment by kblok** [comment]
Why do you need that Id?

**Comment by deaktomi** [comment]
I'm working on a big codebase that is testing my company's websites. It is using Selenium and I cannot port it to Puppeteer. BTW there are a couple of tests that could be performed by using Puppeteer (so we can use some _Emulation_ on the site easier). There are commands which has no wrapper in your library but I must include the browser context id in the args.

**Comment by deaktomi** [comment]
I found the same "lack of information" in the case with Chromium when I subscribe for the `browser.TargetCreated`

The `TargetInfo` in the `TargetChangedArgs` is `null`

Do you plan to support these? Am I doing something wrong?

**Comment by kblok** [comment]
I see what you are doing :). 
How about closing this issue and create a new one requesting the TargetInfo stuff?

**Comment by deaktomi** [comment]
The reason why I need the `TargetInfo` is the same. The `BrowserContextId` is listed in it. But actually, this won't solve my issue. I need the above code to work. There is no `TargetInfo`, but there is a `browser.DefaultContext.Id`
