### ISSUE TITLE
Improve docfx_project/index.md

### ISSUE THREAD

**Issue by ericmutta** [hardkoded/puppeteer-sharp#1879]
The docs say **Mono is required on Linux**...but I successfully tested puppeteer-sharp with .NET 6 on Linux (Ubuntu). Perhaps it should say Mono is required for .NET Framework projects only to avoid giving the impression that you must use Mono for .NET Core/5/6?

**Comment by kblok** [comment]
Good catch! PRs are welcome :)

**Comment by ericmutta** [comment]
[Here](https://github.com/hardkoded/puppeteer-sharp/pull/1885) you go!
