### ISSUE TITLE
PuppeteerSharp.TargetClosedException: Protocol error(Runtime.callFunctionOn): Target closed. (The remote party closed the WebSocket connection without completing the close handshake.)

### ISSUE THREAD

**Issue by yfrindel** [hardkoded/puppeteer-sharp#1882]
Hi,

since recently (since I'm using the new version of the "Wiki PDF export" plugin in DevOps), I have an unexpected error :

![image](https://user-images.githubusercontent.com/22955005/146345231-541a9e16-9057-446b-b302-b80e5d0a4990.png)

and this is the code used : 

![image](https://user-images.githubusercontent.com/22955005/146345674-00ddbf35-992e-4d2c-af1d-141a48f47378.png)
![image](https://user-images.githubusercontent.com/22955005/146345892-9e921e57-3ff8-4c17-90ca-d59d7a72322a.png)

Someone could help me please? Any idea of the issue? How to fix?

Thanks

**Comment by trebor678** [comment]
I'm getting something similar but not using any plugins. It seems like Chrome is crashing but I can't get any logs out. It doesn't seem to happy it you are in header mode. Also doesn't happening when debugging, only when deployed on servers which makes it very difficult to diagnose

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.

**Comment by eluchsinger** [comment]
Same issue here...
