### ISSUE TITLE
Add support for passing "latest" to `DownloadAsync` (for both Chrome and Firefox)

### ISSUE THREAD

**Issue by Cheatoid** [hardkoded/puppeteer-sharp#1892]
![feature request](https://img.shields.io/badge/-feature_request-blue?style=flat-square)

The idea is to automatically fetch the latest (stable) revision by performing HTTP GET request according to the specified platform/product.

#### Product: Chrome
For reference, see [explorer-like viewer](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html).
- OperatingSystem/Platform: Windows
  - [x64 / 64-bit](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2FLAST_CHANGE?alt=media)
  - [x86 / 32-bit](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win%2FLAST_CHANGE?alt=media)
- OperatingSystem/Platform: Linux
  - [x64 / 64-bit](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2FLAST_CHANGE?alt=media)
- OperatingSystem/Platform: Mac
  - [Intel](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Mac%2FLAST_CHANGE?alt=media)
  - [Arm](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Mac_Arm%2FLAST_CHANGE?alt=media)

As for Firefox, there already seems to be some kind of mechanism for this in PuppeteerSharp, but I am not sure if it is functioning properly as I haven't tested that myself yet.

### Further?
Perhaps also add support for "nightly" / "beta" builds... At which point it would be a good idea to have enumeration overload instead of using string to reduce likely hood of errors (e.g. `DownloadAsync(BrowserRevision.Beta)`).

**Comment by kblok** [comment]
We have a mechanism for Firefox. But for Chromium, each Puppeteer version goes with a Chromium revision. There is no guarantee that any puppeteer version will work with the latest chromium version.
