### ISSUE TITLE
puppeteer-sharp NavigationException Firefox

### ISSUE THREAD

**Issue by siilens** [hardkoded/puppeteer-sharp#1897]
### Description

Please tell me, I can’t navigate to the page when using option "userdatadir" with firefox. The site opens in the browser, but i get an error while use

`await page.GoToAsync`

```
Browser browser = await Puppeteer.LaunchAsync(new LaunchOptions
        {
            Headless = false,
            ExecutablePath = "C:\\Program Files\\Mozilla Firefox\\firefox.exe",
            Product = Product.Firefox,
            UserDataDir = @"C:\Users\Nihao\AppData\Roaming\Mozilla\Firefox\Profiles\fp8f64bb.Mika",
            DefaultViewport = null,
            IgnoreHTTPSErrors = true,
            Args = new[] { "-wait-for-browser" }
        });
```
    
   
```
 Page page = await browser.NewPageAsync();
 await page.GoToAsync("https://whoer.net"); //exception here
```

Exception

`PuppeteerSharp.NavigationException: "Timeout of 30000 ms exceeded"`

And Exception while use timeout 0

`page.DefaultNavigationTimeout = 0;`

`PuppeteerSharp.NavigationException: "Navigation failed because browser has disconnected! PuppeteerSharp.FrameManager.d__42.MoveNext()`

Everything works fine, when i dont use "UserDataDir" (Without profile). Maybe there is another way, how to use the Firefox Profile?

### Versions

NET framework 4.6.1 
Puppeteer 6.1.0

**Comment by Sergio1C** [comment]
I also faced with this exception, but my case is different and much simpler. I am running a standard chromiuim browser by:

`            var browserFetcher = Puppeteer.CreateBrowserFetcher(new BrowserFetcherOptions());
            var revisionInfo = await browserFetcher.DownloadAsync(revision: BrowserFetcher.DefaultChromiumRevision);

            var browser = await Puppeteer.LaunchAsync(new LaunchOptions()
            {
                Headless = false,
                //SlowMo = 1000,
                DefaultViewport = new ViewPortOptions()
                {
                    Width = 1024,
                    Height = 800
                }
            });

            var pages = await browser.PagesAsync();           
            var page = pages[0];

            var response = await page.GoToAsync("https://whoer.net"); //If specify SlowMo property (allow), here is exception...`

I just noticed, when I trying to use SlowMo option (as enabled) then I facing to TimeOutException:

without specify "SlowMo" all is working as expected
