### ISSUE TITLE
BrowserFetcher directory location issue

### ISSUE THREAD

**Issue by LeeeJoe** [hardkoded/puppeteer-sharp#1909]
### Description

Using Directory.GetCurrentDirectory() on Centos 7 (Linux) results in the directory from which the command to start the process is issued, not the directory where the executable is located.
Thank you.

P.S. Perhaps more better will be: Path.GetDirectoryName(Environment.ProcessPath)

**Comment by kblok** [comment]
PRs are welcome :)
