### ISSUE TITLE
Puppeteer Hangs On CreateNewPageAsync, When More than One Process Opened.  

### ISSUE THREAD

**Issue by omamoo** [hardkoded/puppeteer-sharp#1914]
**Before you file a bug, have you:**

* Tried upgrading to newest version of PuppeteerSharp, to see if your issue has already been resolved and released? **Yes**
* Checked existing open *and* closed [issues](https://github.com/kblok/puppeteer-sharp/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported? **Yes**
* Tried reproducing your problem in a new isolated project? **Yes**

### Description
When I'm trying to open more than one chromium process simultaneously, the code is hangs while executing the following line of code:
```
_browserPage = await browser.NewPageAsync();
```

### Complete minimal example reproducing the issue
```
var browser =
                await Puppeteer.LaunchAsync(
                    new LaunchOptions
                    {
                        Args =
                            new[]
                            {
                                "--disable-gpu",
                                "--incognito",
                                "--no-sandbox",
                                "--no-zygote",
                                "--single-process"
                            },
                        LogProcess = true
                    },
                    _loggerFactory);
            _browserPage = await browser.NewPageAsync();
```
### Expected behavior:
New pages created and code continue to execute.

### Actual behavior:
The code hangs, after some debugging I can observe that Puppeteer sends `Traget.createTarget` command via the web-socket
```
web-app-1_1  | {"EventId":0,"LogLevel":"Trace","Category":"PuppeteerSharp.Connection","Message":"Send { id :2, method : Target.createTarget , params :{ url : about:blank }}","State":{"Message":"Send   { id :2, method : Target.createTarget , params :{ url : about:blank }}","Message":"{ id :2, method : Target.createTarget , params :{ url : about:blank }}","{OriginalFormat}":"Send   {Message}"}}
```

And expecting the following messages from chromium:
`Target.targetCreated`, `Target.targetInfoChanged`

But the message `Target.targetInfoChanged` never received. 

### Versions

* Which version of PuppeteerSharp are you using? 6.1.0
* Which .NET runtime and version are you targeting? .NET Core 2.0.

**Comment by micha-nerves** [comment]
I guess I have the same or similar problem. If multiple threads are at "browser.NewPageAsync();" they all hang or timeout. Those which don't timeout continue at the same time.
