### ISSUE TITLE
Find element using xpath

### ISSUE THREAD

**Issue by sabindev** [hardkoded/puppeteer-sharp#1917]
in normal puppeter finding element by xpath is done using page.$x("xpath"), but i cant find the equivalent in puppeteer sharp

**Comment by kblok** [comment]
As `$x` is not a valid function name in C#. It is [XPathAsync](https://www.puppeteersharp.com/api/PuppeteerSharp.Page.html#PuppeteerSharp_Page_XPathAsync_System_String_).

**Comment by sabindev** [comment]
> As `$x` is not a valid function name in C#. It is [XPathAsync](https://www.puppeteersharp.com/api/PuppeteerSharp.Page.html#PuppeteerSharp_Page_XPathAsync_System_String_).

well that doesnt work for what im trying to do, im trying to find an iframe using xpath and then get the contents from that iframe, i get this error when i try to do that `Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'ElementHandle[]' does not contain a definition for 'ContentFrameAsync' and no accessible extension method 'ContentFrameAsync' accepting a first argument of type 'ElementHandle[]' could be found (are you missing a using directive or an assembly reference?)	ConsoleApp6	C:\Users\sabin\source\repos\ConsoleApp6\ConsoleApp6\Program.cs	22	Active
`

**Comment by kblok** [comment]
That function returns an array. You will need to check if you got elements and grab the first one.

**Comment by AngryOwlAdv** [comment]
@kblok How do u do that lets say u wanna grab the third one how would u do it

**Comment by kblok** [comment]
@AngryOwlAdv `XPathAsync` returns an array. You can grab the third element as you'd grab the third element of any array.
