### ISSUE TITLE
PostData is blank when using chromium versions after 85.0.4183.121-1

### ISSUE THREAD

**Issue by centripicalforcesman** [hardkoded/puppeteer-sharp#1924]
## Looking for some help? Get priority support by [sponsoring the project](https://github.com/sponsors/hardkoded)/

**Before you file a bug, have you:**

* Tried upgrading to newest version of PuppeteerSharp, to see if your issue has already been resolved and released?
* Checked existing open *and* closed [issues](https://github.com/kblok/puppeteer-sharp/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* Tried reproducing your problem in a new isolated project?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/search?q=puppeteer-sharp).

### Description

When trying to set add PostData through request interception, the body data is blank when it gets to the site it is posting to.  This is running through docker with the following [Dockerfile](https://github.com/centripicalforcesman/bug_repro_files/blob/main/Dockerfile).  The PostData contains expected data when using Chromium versions 85.0.4183.121-1 and earlier

### Complete minimal example reproducing the issue

Complete means the code snippet can be copied into a unit test method in a fresh C# project and run.
Minimal means it is stripped from code not related to reproducing the issue.

E.g.

```csharp
// Arrange
var options = new LaunchOptions {
      Headless = true,
      Args = new[] { "--incognito}", "--no-sandbox", "--ignore-certificate-errors" },
      ExecutablePath = "/usr/bin/google-chrome-stable",
      IgnoreHTTPSErrors = true,
};

var browser = await Puppeteer.LaunchAsync(options);
var page = browser.NewPageAsync();
await page.SetRequestInterceptionAsync(true);

page.Request += async (sender, args) =>
{
    var pl = new Payload();
        
      var currentPostData = "";
      if (args.Request.Method == HttpMethod.Post)
      {
          if (args.Request.PostData != null)
              currentPostData = args.Request.PostData.ToString();
      }

      pl.Method = HttpMethod.Post;
      var tokenPostData = "foo=bar";

      if (String.IsNullOrEmpty(currentPostData))
          pl.PostData = tokenPostData ;
      else
          pl.PostData = $"{currentPostData}&{tokenPostData}";
    await args.Request.ContinueAsync(pl);
};

  // Go to site
  await Page.GoToAsync("http://localhost", WaitUntilNavigation.Networkidle0);



### Expected behavior:
For data that was set in PostData to be in the body of the request once it makes it to the site I am posting to.

### Actual behavior:

The body is blank

### Versions

* Which version of PuppeteerSharp are you using? 6.2.0
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
.Net Standard 2.1

### Additional Information

**Comment by kblok** [comment]
Can you try this with Puppeteer 7 and Chrome 100?

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
