### ISSUE TITLE
Feature Request: Implement Interfaces for Browser/Page classes

### ISSUE THREAD

**Issue by danbopes** [hardkoded/puppeteer-sharp#1925]
When prototyping projects, especially for testing, it would be a lot nicer if `Page` implemented an `IPage` with all of it's main methods/events. I could then mock up my own page class (With something like Moq) which I could create my own implementation to return specific data, or track how many times methods get called.  Right now, this isn't really possible with PuppeteerSharp.

**Comment by kblok** [comment]
I think I would review a PR with this change. It would be quite massive thought.

**Comment by brnbs** [comment]
+1 an IBrowser interface would be awesome for the Browser object, so I can mock it during unit testing

**Comment by pthomaz** [comment]
Hey guys
Any news on the topic?
