### ISSUE TITLE
Unable to render Unicode Characters 

### ISSUE THREAD

**Issue by mrdo23** [hardkoded/puppeteer-sharp#1951]
Hi,

I'm successfully generating a PDF from HTML content in a Linux Azure Function. Everything works as expected except that Unicode characters are missing from the output. 

I have so far assumed that this is caused by a missing font but no matter what I try, I am unable to get the unicode chars to render. The CSS file that I'm linking to references '@font-face{font-family:'Roboto';src:url("../fonts/Roboto/Roboto-Regular.ttf") format("truetype")}' but would be unable to reach the ttf file.

So far I have tried:

Prefixing the html with the following: <link href='http://fonts.googleapis.com/css2?family=Roboto&display=swap' rel='stylesheet'>
Prefixing the html with a style tag and link to a known source of the ttf (only 167KB) using: '@font-face { font-family: 'Roboto'; src: url(https://path-to-website/Roboto-Regular.ttf) format('truetype');}'
Using AddTagOptions to add the Google stylesheet used above

None of these seem to be working. Curiously, when I view the content in Acrobat reader, the unicode text does appear to be there (but is invisible but selectable). In all opther renderers, there is nothing there at all.

Can anyone suggest anything that might help?

**Comment by mrdo23** [comment]
I have further narrowed down the issue to Chinese characters only (for the moment) as Russian characters seem to be ok. I have seen reference to installing a Chrome Dev package that seems to render fonts properly if using a Docker image:

'Install latest chrome dev package and fonts to support major charsets (Chinese, Japanese, Arabic, Hebrew, Thai and a few others) Note: this installs the necessary libs to make the bundled version of Chromium that Puppeteer installs, work'

Is there any way to get this install outwith Docker?

**Comment by kblok** [comment]
I think this is more a question for the Chromium team.
