### ISSUE TITLE
Local IP address selection

### ISSUE THREAD

**Issue by starkdm** [hardkoded/puppeteer-sharp#1957]
Is it possible to use a specific IP address if multiple addresses are assigned to a Windows network interface on server?

**Comment by kblok** [comment]
@starkdm how would you do that on Chrome?

**Comment by starkdm** [comment]
Don't know. I want to understand how it can be done

**Comment by kblok** [comment]
@starkdm Puppeteer-Sharp automates Chrome, so it would be a matter to know what to automate.
