### ISSUE TITLE
How to load extension

### ISSUE THREAD

**Issue by bxthanhlove** [hardkoded/puppeteer-sharp#1959]
## Failed to load extension

I install the extension but get the error:
 "Failed to load extension from: C:\Users\BxThanhLove\Desktop\Project\shopeeseo\ShopeeSeo\bin\Debug\Extension\FingerprintSpoofing.crx. Manifest file is missing or unreadable"
Or is there a way to # install the extension?

Below is my code

```csharp
 await new BrowserFetcher().DownloadAsync();
 var pathToExtension = @"C:\Users\BxThanhLove\Desktop\Project\shopeeseo\ShopeeSeo\bin\Debug\Extension\FingerprintSpoofing.crx";
 var options = new LaunchOptions
 {
      Headless = false,
      DefaultViewport = new ViewPortOptions() { },
      Args = new[]
      {
              $"--disable-extensions-except={pathToExtension}",
              $"--load-extension={pathToExtension}",
          }
  };
 var browser = await Puppeteer.LaunchAsync(options);
```
Puppeteer-sharp version 7.0

**Comment by bxthanhlove** [comment]
Puppeteer-sharp version 7.0

**Comment by kblok** [comment]
If you launch chrome from a terminal with those arguments does it work?
