### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by starkdm** [hardkoded/puppeteer-sharp#1960]
Very often I get a `503 Service Not Available` error when loading web page. The page doesn't load at all, or it loads partially and doesn't work as intended. If I load this website through normal Google Chrome, everything works correctly (sometimes the server gives this error, but the page either fully loads or does not load at all - there are no situations when some resources did not load with a 503 error and the page does not work as expected).

```
await new BrowserFetcher().DownloadAsync(); 
Browser browser = await Puppeteer.LaunchAsync(new LaunchOptions { 
 Headless = true, 
 Product = Product.Chrome, 
 IgnoreHTTPSErrors = true 
}); 
 
Page page = await browser.NewPageAsync(); 
await page.GoToAsync(pageUrl);
```

**Comment by kblok** [comment]
Puppeteer-Sharp relies heavily on Chromium features.
Some bugs are caused by puppeteer, but others can be caused by chromium.
This sounds like a chromium issue. You can report those issues [here](https://bugs.chromium.org/p/chromium/issues/list).
