### ISSUE TITLE
UnobservedTaskException TargetClosedException

### ISSUE THREAD

**Issue by georgiosd** [hardkoded/puppeteer-sharp#1964]
Not sure if this a bug or a problem in my code, probably the latter, but I would appreciate any hints to help resolve it.

I have a background process that executes once a day and runs some ops on a website.

After a few hours of the script running, I *sometimes* get this exception caught by the unobserved task handler:

```
PuppeteerSharp.TargetClosedException
Target closed (Session closed)
```

Sadly the exception doesn't contain any other information (stack etc) - it's caught by Sentry, which we use for error tracking.

Both the browser and page are part of using statements so I wouldn't expect this to happen.

Also, I am NOT attaching any event handlers to the page.

Any ideas?

Thanks

**Comment by kblok** [comment]
Target closed errors are hard to track. They are caused by the tab being closed (or crashed) or the browser getting closed.
There is no generic answer for this.

**Comment by georgiosd** [comment]
Okay, I guess I'll ignore them, thanks
