### ISSUE TITLE
Puppeteer-sharp renders pdf  with grey text and small font

### ISSUE THREAD

**Issue by vindhya124** [hardkoded/puppeteer-sharp#1973]
Hi

I am using razor html template and puppeteer-sharp to generate a pdf receipt and sending as any attachment to the email.

The pdf rendered shows the grey font and small font size. I have tired changing the css but its not working.

Please find below pdf.

![image](https://user-images.githubusercontent.com/38023844/174679819-2ceff344-2813-4ef4-9c82-0f92a5855a4f.png)

**Comment by kblok** [comment]
If you open a browser and print that to PDF what does it look like?

**Comment by vindhya124** [comment]
> If you open a browser and print that to PDF what does it look like?
Its same a above image

**Comment by kblok** [comment]
So it's something you need to fix on your media print.
