### ISSUE TITLE
I can not render mi webpage when headless is true

### ISSUE THREAD

**Issue by ExpErgio** [hardkoded/puppeteer-sharp#1998]
Hello. I expose my problem. I am trying to access a website with PuppeteerSharp which, conveniently and on purpose, I will not be able to access. This is because the only thing I need is a code that generates that website after performing several actions that are not relevant now.

The question is: if I set "headless" to "false", the page will not load after a few seconds, but google will generate a web view as shown on the screen. When generating it, my code will be found in the HTML code and I will be able to get it (image 1)
![imagen1](https://user-images.githubusercontent.com/75345847/180950216-cf708f29-7659-411e-944d-bf17e5eb6867.png)

On the contrary, if I set my "headless" to "true", the page will not load, but google does not generate the preview in which my code is inserted. It stays as a completely blank screen, as seen on the screen (image 2)
![imagen2](https://user-images.githubusercontent.com/75345847/180949865-f53bb3b6-31ad-4eb7-a96d-5f4953baa080.png)

Is there anything I can do?

**Comment by kblok** [comment]
How is your code inserted in the Chrome error page?
