### ISSUE TITLE
Can't set external fonts for header or footer with calling PdfDataAsync

### ISSUE THREAD

**Issue by Prototipo-Erick-Santander** [hardkoded/puppeteer-sharp#2001]
### Description
I have found a problem with while using this library to create a pdf from a html.

The specific problem is that I can't use external fonts on custom header/footers of documents.

It just throws an exeception whenever I try to use an external font. usinf <link> tag with href on header of the document.
this doesn't seem to happen in the body, only on the header or the footer.

### Complete minimal example reproducing the issue
```
public static async Task MinimumViableTest()
    {
        string htmlBody = "<html><body>This is a body</body></html>";
        string htmlHeader = "<html><header><link href=\"https://fonts.googleapis.com/css2?family=Oxygen&display=swap\" rel=\"stylesheet\"></header><body><div style=\"overflow: hidden; font-family: Oxygen\">Header</div></body></html>";
        string htmlFooter = "<html><header><link href=\"https://fonts.googleapis.com/css2?family=Oxygen&display=swap\" rel=\"stylesheet\"></header><body><div style=\"overflow: hidden; font-family: Oxygen\">Footer</div></body></html>";
        
        try
        {
            _fetcher ??= new BrowserFetcher(Product.Chrome);
            _revisionInfo ??= await _fetcher.DownloadAsync("1022525");
            _browser ??= await Puppeteer.LaunchAsync(new LaunchOptions { Headless = true, ExecutablePath = _revisionInfo.ExecutablePath, Args = new [] {"--force-color-profile=srgb", "--font-render-hinting=none"} });
            await using var page = await _browser.NewPageAsync();
            await page.SetContentAsync(htmlBody);
            await page.EvaluateExpressionHandleAsync("document.fonts.ready");

            var margins = new MarginOptions
            {
                Top = "30",
                Bottom = "30",
                Left = "30",
                Right = "30",
            };
            
            var bytes = await page.PdfDataAsync(new PdfOptions
            {
                MarginOptions = margins,
                HeaderTemplate = htmlHeader, 
                FooterTemplate = htmlFooter, 
                DisplayHeaderFooter = true, 
                Format = PaperFormat.A4,
            });
            
            await File.WriteAllBytesAsync("Generated/headlessChrome.pdf", bytes);
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
        }
    }
```

### Expected behavior:
The expected behaviour would be to export a pdf with the referenced font on the header and footer.

### Actual behavior:
Throws this exception:
![image](https://user-images.githubusercontent.com/62098744/182371244-5f3b4c6d-54c0-44b3-8589-44ac558eff16.png)
Message: 
> Protocol error (Page.printToPDF): Printing failed

StackTrace:
>    at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 159
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 110
   at PuppeteerSharp.Page.PdfInternalAsync(String file, PdfOptions options) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 1036
   at TestProject.HtmlToPDf_Tests.MinimumViableTest() in /home/prototipo-dev/RiderProjects/TestProject/HtmlToPDf_Tests.cs:line 162
   at TestProject.HtmlToPDf_Tests.MinimumViableTest() in /home/prototipo-dev/RiderProjects/TestProject/HtmlToPDf_Tests.cs:line 171

### Versions

Im using the nuget package of this library in ersion 7.1.0
Im runing the project in .NET 6

### Additional Information
The idea im using is Jetbrains Rider
Im runing Ubuntu 20.04 (focal) Linux

**Comment by Prototipo-Erick-Santander** [comment]
I saw online that this might be a limitation of the library, but, even if a fix is not possible, is there any workaround that I could use to use external fonts on custom header or footer of the exported pdf?

**Comment by kblok** [comment]
@Prototipo-Erick-Santander I think this is something to report on [chromium](https://bugs.chromium.org/p/chromium/issues/list)

**Comment by kemmis** [comment]
@Prototipo-Erick-Santander Do you just need to use <head> instead of <header> in your code?
