### ISSUE TITLE
Trying to execute a selector on a cross-domain IFrame never returns

### ISSUE THREAD

**Issue by JenyaRostov** [hardkoded/puppeteer-sharp#2005]
### Description

Basically I try to get a div from cross-domain IFrame and method never returns(maybe i'm doing this wrong, if so, please tell me!)
Can be reproduced on any page with hCaptcha (i think)
I also use those flags: 
![image](https://user-images.githubusercontent.com/52300935/184758717-08e5a859-748c-4ed5-9cb0-a7de00823515.png)

### Complete minimal example reproducing the issue

```csharp
var frames = _page.Frames;
 var frame = frames[1];
var checkbox = await frame.QuerySelectorAsync("div[id='checkbox']"); // never returns
```

### Expected behavior:

Get an element

### Actual behavior:

Method never returns

### Versions

* Which version of PuppeteerSharp are you using - 7.1.0
* Which .NET runtime and version are you targeting - NET6.0

**Comment by kblok** [comment]
Do you have a piece of code I can run to replicate this?

**Comment by JenyaRostov** [comment]
Will write one when i get home

**Comment by JenyaRostov** [comment]
nvm, had an issue with my code
apparently blocking some resources disables accessing iframes?

**Comment by JenyaRostov** [comment]
`ResourceType.Image, ResourceType.Font, ResourceType.Img, ResourceType.Media, ResourceType.StyleSheet`
blocking those via `BlockResourcesPlugin` broke everything
