### ISSUE TITLE
lighthouse interop?

### ISSUE THREAD

**Issue by OnurGumus** [hardkoded/puppeteer-sharp#2009]
puppeteer itself can use npm lighthouse package to interop with lighthouse. Any ways to do same with puppeteersharp?

**Comment by kblok** [comment]
It seems that the only thing that the lighthouse does with puppeteer is [getting the port and connect to that port](https://github.com/dima-horror/lighthouse.net/blob/master/lighthouse.net/Core/ScriptMaker.cs#L20).
There is a [lighthouse.net project](https://github.com/dima-horror/lighthouse.net), but [it always launches a new browser](https://github.com/dima-horror/lighthouse.net/blob/master/lighthouse.net/Core/ScriptMaker.cs#L102). It also requires node and lighthouse installed.
I don't think it would be that hard to fork that project and change it to connect to a port, like the example in lighthouse.

**Comment by OnurGumus** [comment]
Yes that can be done. But it still executes node and lighthouse package manually and parses the output. What I was looking for perhaps a direct implementation of the lighthouse without requiring node

**Comment by kblok** [comment]
Yeah... I just took a look at the lighthouse project, and it's quite a massive project :(

BTW, thank you for the donation. I really appreciate it!

**Comment by OnurGumus** [comment]
Eventually it sends some commands via CDP but couldn't find what they are.

**Comment by kblok** [comment]
I was looking at that too.

**Comment by OnurGumus** [comment]
By the way this is pretty interesting article. I have checked existing links in there. Apparently it is possible to run node in .NET
https://andrewlock.net/running-javascript-in-a-dotnet-app-with-javascriptengineswitcher/

**Comment by OnurGumus** [comment]
Just as a side note, I solved the problem using lighthouse package directly and passing the port to it via
https://github.com/JeringTech/Javascript.NodeJS
