### ISSUE TITLE
support for aria queries

### ISSUE THREAD

**Issue by OnurGumus** [hardkoded/puppeteer-sharp#2010]
I saw puppeteer supports aria based queries since some time
https://developer.chrome.com/blog/puppetaria/

```javascript
const button = await page.$('aria/Submit[role="button"]');
await button.click();
```

When I try to do same with .net 

it fails as below 
`
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (Query set to use "aria", but no query handler of that name was found)
 ---> PuppeteerSharp.PuppeteerException: Query set to use "aria", but no query handler of that name was found
   at PuppeteerSharp.CustomQueriesManager.GetQueryHandlerAndSelector(String selector) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CustomQueriesManager.cs:line 103
`
wheras my code is as below
`page.ClickAsync("aria/Submit[role='button']")`
Is this a supported scenario?

**Comment by kblok** [comment]
I’m [working on that](https://github.com/hardkoded/puppeteer-sharp/pull/2002) :)
It’s not ready yet.
