### ISSUE TITLE
ClickablePointAsync throws error "Node is either not visible or not an HTMLElement"

### ISSUE THREAD

**Issue by MartinDlt** [hardkoded/puppeteer-sharp#2037]
Version 8.0.0

ClickablePointAsync fails at !quads.Any(),
I debugged during the run and found out that the values of the BoxModelPoints are reset to 0 directly after ApplyOffsetsToQuad.
Before it is called this was one of my BoxModelPoints:
{X = 75.5, Y = 191.0}

offsetX = 0
offsetY = 0

after ApplyOffsetsToQuad, my point is:
{X = 0, Y = 0}

**Comment by kblok** [comment]
Do we have any code example to test?

**Comment by MartinDlt** [comment]
```
var url = "http://127.0.0.1:9123";
using var browser = await Puppeteer.ConnectAsync( new ConnectOptions { BrowserURL = url, SlowMo = 0 });
var pages = await browser.PagesAsync();
var pageOne = pages[0];
await pageOne.GoToAsync("https://en.wikipedia.org/wiki/Main_Page");

...

var s = (await pageOne.XPathAsync("//span[text()=\"From today's featured article\"]")).First();
var point = await s.ClickablePointAsync();
pageOne.Mouse.ClickAsync(point.X, point.Y, new ClickOptions());
```

I connect to a CefSharp client inside a WPF application with the port 9123.
The main problem I have is that this doesn't work consistently for me. It failed consistently yesterday, but doesn't fail today, despite no code being altered in between.
