### ISSUE TITLE
not work well on my clients PCS

### ISSUE THREAD

**Issue by mostafakamelomarrslan** [hardkoded/puppeteer-sharp#2039]
i don't know why or how work well on my device and my all pcs clients don't work =>
special => execute js
![Capture](https://user-images.githubusercontent.com/81367531/201348053-86761884-1add-4710-9ca7-cd7f75f7f4e1.PNG)

**Comment by kblok** [comment]
Is that a javascript you re executing on the browser?

**Comment by mostafakamelomarrslan** [comment]
yes sir execute javascript give me error

**Comment by kblok** [comment]
So that's an error in the javascript being executed. It shouldn't be related to puppeteer-sharp. 
The `shadowRoot` property is null.

**Comment by kblok** [comment]
Maybe the target page is detecting you are automating it? 
Still, it is a javascript error.

**Comment by mostafakamelomarrslan** [comment]
no master when i am using application on my device work well ! 
other device puppeteer not work but  selenium work

**Comment by kblok** [comment]
Do you have any code for me to test?

**Comment by mostafakamelomarrslan** [comment]
sure 
{
`                    await page.GoToAsync("chrome://extensions/?id=jmdajahopeopmegamfgcfmpbjhklefdc", WaitUntilNavigation.DOMContentLoaded);
                    await page.EvaluateExpressionAsync(@"document.querySelector('extensions-manager').shadowRoot.querySelector('#viewManager > extensions-detail-view.active').shadowRoot.querySelector('div#container.page-container > div.page-content > div#options-section extensions-toggle-row#allow-incognito').shadowRoot.querySelector('label#label input').click()");
`
}

**Comment by kblok** [comment]
Can you add this before your evaluate?

```
await Page.WaitForFunctionAsync("() => @"document.querySelector('extensions-manager')?.shadowRoot?.querySelector('#viewManager > extensions-detail-view.active')?.shadowRoot?.querySelector('div#container.page-container > div.page-content > div#options-section extensions-toggle-row#allow-incognito')?.shadowRoot?.querySelector('label#label input')");
```

**Comment by mostafakamelomarrslan** [comment]
the error in id extension it's change  always when u change device is there any way to add extension crx not unpacked ?

**Comment by mostafakamelomarrslan** [comment]
![Capture](https://user-images.githubusercontent.com/81367531/201515896-e4af533b-463c-49cc-9a99-cb36cb35d5de.PNG)
what about this

**Comment by mostafakamelomarrslan** [comment]
other error

**Comment by kblok** [comment]
Unrelated to the issue reported on top. Let's create another issue with some steps to reproduce that.
