### ISSUE TITLE
Error in waiting in other Clients PC

### ISSUE THREAD

**Issue by mostafakamelomarrslan** [hardkoded/puppeteer-sharp#2040]
![201515896-e4af533b-463c-49cc-9a99-cb36cb35d5de](https://user-images.githubusercontent.com/81367531/201544871-6aab199e-2545-47a7-bd5c-f400f2893f6f.png)

**Comment by mostafakamelomarrslan** [comment]
when using waitforxpath get this error with my users please help

**Comment by kblok** [comment]
It's hard to triage a screenshot.
