### ISSUE TITLE
Adding function to retrieve ShadowRoot elements

### ISSUE THREAD

**Issue by ksergio39** [hardkoded/puppeteer-sharp#2042]
Would it be possible to add a function to include the ability to locate and retrieve ShadowRoot elements. In JS you would be able to do the following. However I don't see any documentation in puppeteer sharp to allow me to do something similar. Would this even be possible? Or would it make more sense to call a JS script from C#?

document.querySelector("#ShadowRootID").shadowRoot.querySelector("#_SomeIDInTheShadowDom")

**Comment by kblok** [comment]
Puppeteer sharp can pierce the shadow DOM. You can do `page.QuerySelectorAsync("pierce/#_SomeIDInTheShadowDom")`
