### ISSUE TITLE
How to: Use default Chome cookies

### ISSUE THREAD

**Issue by vd3d** [hardkoded/puppeteer-sharp#2044]
Hi,

I'm looking for a way to avoid a login each time I scrap. Why because there is a multi authentication and so it is impossible to login.
So, I wish to use Puppeteer and reuse the existing Chrome cookies.

Is it possible? And if yes, how ? :-P

Thanks for your help

**Comment by kblok** [comment]
You can use the userDataDir option. [This question on SO](https://stackoverflow.com/questions/46908441/how-to-pass-userdatadir-profile-folder-to-puppeteer) might help.
