### ISSUE TITLE
Runtime error when trying to set clipboard permissions

### ISSUE THREAD

**Issue by movsar** [hardkoded/puppeteer-sharp#2052]
### Description

Can't set clipboard permissions.

### Complete minimal example reproducing the issue

```
            await browser.DefaultContext.OverridePermissionsAsync("https://example.com",
                new OverridePermission[] { OverridePermission.ClipboardWrite}
            );
```

### Expected behavior:

To be able to use clipboard in headless mode

### Actual behavior:

_System.AggregateException: 'One or more errors occurred. (Protocol error (Browser.grantPermissions): Unknown permission type: clipboardWrite)'_

Same with ClipboardRead

### Versions

Targeting .NET6, PuppeteerSharp version 8.0

**Comment by amaitland** [comment]
Looks like the `CDP API` has changed, the values for `clipboardWrite` and `clipboardRead` were merged into [clipboardReadWrite](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#type-PermissionType)

Interestingly [puppeteer](https://github.com/puppeteer/puppeteer/blob/842008102f7b7f1d5f95d9cf3e84909c1bd51f81/packages/puppeteer-core/src/api/Browser.ts#L82) has a mapping in place.

**Comment by kblok** [comment]
@amaitland good catch. Do you want to give it a chance and try to fix it?

**Comment by amaitland** [comment]
I'm getting ready to go on holiday, unlikely I'll have time until the new year.

**Comment by shockk73** [comment]
@movsar as temporary fix you can use 

` 
     public static object? GetInstanceField(this object instance, string fieldName)
        {
            BindingFlags bindFlags = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;
            var field = instance.GetType().GetField(fieldName, bindFlags);

            if (field is not { }) throw new InvalidOperationException($"Type '{instance.GetType()}' doesn't contains field '{fieldName}'");

            return field.GetValue(instance);
        }

 public static object? GetInstanceProperty(this object instance, string propertyName)
        {
            BindingFlags bindFlags = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic;
            var property = instance.GetType().GetProperty(propertyName, bindFlags);

            if (property is not { }) throw new InvalidOperationException($"Type '{instance.GetType()}' doesn't contains property '{propertyName}'");

            return property.GetValue(instance);
        }

        public static string? GetId(this IBrowserContext browserContext) => browserContext.GetInstanceProperty("Id") as string;

public static Connection GetConnection(this IBrowserContext browserContext)
        {
            var connectionObj = browserContext.GetInstanceField("_connection");

            if (connectionObj is not { }) throw new NullReferenceException("Connection not defined");

            var connection = connectionObj as Connection;

            if (connection is not { }) throw new InvalidCastException($"Could not cast field '_connection' to type '{typeof(Connection)}' for browsercontext of type '{browserContext.GetType()}'");

            return connection;
        }

public static async Task<JObject> SendAsync(this Connection connection, string method, object? args = default, bool waitForCallback = true)
        {
            var _method = typeof(Connection).GetMethods(BindingFlags.Instance | BindingFlags.NonPublic)
                .Where(x => x.Name == "SendAsync")
                .First(x => !x.ContainsGenericParameters);

            if (_method is not { }) throw new InvalidOperationException($"Type '{typeof(Connection)}' doen't contains nonpublic method with name 'SendAsync'");

            var res = _method.Invoke(connection, new object?[] { method, args, waitForCallback }) as Task<JObject>;

            if (res is not { }) throw new InvalidCastException("Could not cast result of method 'SendAsync' to type 'Task<JObject>'");

            return await res;
        }

  **public static Task OverridePermissionsAsync(this IBrowserContext browserContext, string origin, IEnumerable<string> permissions) => 
            browserContext.GetConnection().SendAsync("Browser.grantPermissions", new
            {
                Origin = origin,
                BrowserContextId = browserContext.GetId(),
                Permissions = permissions.ToArray(),
            });**

`
