### ISSUE TITLE
Full Page screenshot issue

### ISSUE THREAD

**Issue by rspatole** [hardkoded/puppeteer-sharp#2067]
How to take a full page screen shot of the full web page which is having a scroll bar?

**Comment by amaitland** [comment]
What is the issue exactly?

There are plenty of examples in the `xUnit` tests for taking screenshots including full page. https://github.com/hardkoded/puppeteer-sharp/blob/master/lib/PuppeteerSharp.Tests/ScreenshotTests/PageScreenshotTests.cs#L200

**Comment by rspatole** [comment]
It is resolved now, I got the height of scrollbar then set this height to view port then get a full page screen shot.
- [ ] Thank you for your response.

**Comment by rspatole** [comment]
This method -ShouldTakeFullPageScreenshots- will not work if you have a scroll bar in vertical position.
