### ISSUE TITLE
NullReferenceException in Page.AddConsoleMessageAsync

### ISSUE THREAD

**Issue by danports** [hardkoded/puppeteer-sharp#2069]
The exception is thrown when I call Page.WaitForSelectorAsync, but it looks like the actual issue is that something is being logged to the console that PuppeteerSharp can't handle correctly:

```
PuppeteerSharp.TargetClosedException: 'Protocol error(Runtime.callFunctionOn): Target closed. (Page failed to process Runtime.consoleAPICalled. Object reference not set to an instance of an object..    at PuppeteerSharp.Page.<>c.<AddConsoleMessageAsync>b__262_1(IJSHandle i) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 1672
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.String.JoinCore[T](ReadOnlySpan`1 separator, IEnumerable`1 values)
   at System.String.Join[T](String separator, IEnumerable`1 values)
   at PuppeteerSharp.Page.AddConsoleMessageAsync(ConsoleType type, IJSHandle[] values, StackTrace stackTrace) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 1685
   at PuppeteerSharp.Page.Client_MessageReceived(Object sender, MessageEventArgs e) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 1471)'
```

This is reproducible on both PuppeteerSharp v8 and v9, running on .NET 7. Not sure I can share a repro case since the page I'm accessing requires authentication. When I look at the console for the page in question, I see some uncaught TypeErrors, e.g.:

![image](https://user-images.githubusercontent.com/8728855/212758905-52a74832-e9b3-4e0c-94b8-56c1995452ad.png)

**Comment by kblok** [comment]
I can take a look at it if I get some code that can reproduce the issue.

**Comment by danports** [comment]
Understood. My guess is that a page that throws a `TypeError` could be enough to trigger this, but I had already planned to migrate this particular use case away from Puppeteer so I will probably just take that path rather than digging deeper into this issue.

**Comment by amaitland** [comment]
@kblok The `JTokenType.Object` check added in #2025, was there a reason to check the `JToken` type rather than `RemoteObjectType.Object`?

Calling `console.debug(null);`  results in an exception with a callstack similar to this one.

```c#
[SkipBrowserFact(skipFirefox: true)]
public async Task ShouldNotFailForNullArgument()
{
	var consoleTcs = new TaskCompletionSource<string>();

	void EventHandler(object sender, ConsoleEventArgs e)
	{
		consoleTcs.TrySetResult(e.Message.Text);
		Page.Console -= EventHandler;
	}

	Page.Console += EventHandler;

	await Task.WhenAll(
		consoleTcs.Task,
		Page.EvaluateExpressionAsync("console.debug(null);")
	);

	Assert.Equal("JSHandle:null", await consoleTcs.Task);
}
```

Checking `RemoteObject.Type == RemoteObjectType.Object` resolves the exception. Argubily passing `null` to `console.debug` is pointless. Nonetheless it shouldn't crash.,

**Comment by kblok** [comment]
Good catch @amaitland? It looks like you already have a test. Do you want to create a PR for that?

**Comment by danports** [comment]
Does the test fail if you change `console.debug(null)` to something that throws a `TypeError`? I'm getting this exception simply calling `Page.GoToAsync` on other URLs too, and the only common denominator seems to be TypeErrors thrown on the target pages.

**Comment by danports** [comment]
Confirmed that this is a v9 regression so you are probably right about #2025 being the problem commit @amaitland - I thought I had tested this on v8 and it was broken but I was wrong: I retested just now and v8 works fine.

**Comment by amaitland** [comment]
@danports Thanks for confirming. I've created #2070 which should hopefully fix this

**Comment by kblok** [comment]
@amaitland @danports I bumped the version in the PR so we can publish that fix.

**Comment by kblok** [comment]
v9.0.1 shipped

**Comment by danports** [comment]
Awesome, thanks! I'll give v9.0.1 a try.

**Comment by kblok** [comment]
@danports friendly reminder to close the issue if 9.0.1 fixed it :)

**Comment by danports** [comment]
Oops, my bad, I thought our dependency bot would open a PR for the new release but that didn't happen...I'll check out 9.0.1 in the next day or two.

**Comment by danports** [comment]
9.0.1 looks good, thanks!
