### ISSUE TITLE
error in add-ons

### ISSUE THREAD

**Issue by mostafakamelomarrslan** [hardkoded/puppeteer-sharp#2072]
![Capture](https://user-images.githubusercontent.com/81367531/213906511-7e25c925-3c27-41cc-b6dc-31fe34c1f5da.PNG)

**Comment by kblok** [comment]
Do you have any code I can use to reproduce the issue?

**Comment by mostafakamelomarrslan** [comment]
![Capture](https://user-images.githubusercontent.com/81367531/214116705-091661ba-63ec-44c5-92a0-000b6685b0d7.PNG)

**Comment by kblok** [comment]
Please create a new issue with a code **text** I can use.
