### ISSUE TITLE
How to type slow?

### ISSUE THREAD

**Issue by janya171** [hardkoded/puppeteer-sharp#2077]
Hello
I would like to translate this piece of code from puppeteer to puppeteersharp I use in vb.net.
It is actually nowhere written and I need to type signin forms like human not copy and paste so it needs some "delay" or something human type looking mouse events or so..

**CODE which is in puppeteer:**
```
await page.waitForSelector("#identifierId");
await page.type("#identifierId", userid_, { delay: 400 });
```
**When I do this it says "delay" is not declared which in fact is true:**
` Await page.TypeAsync("input[id='identifierId']", userid_, delay:400 )`
```

So what to change in "delay 400" so it works in vb.net using puppeteersharp??
thx

**Comment by antopor** [comment]
Please, refer to documentation for Page.TypeAsync method - https://www.puppeteersharp.com/api/PuppeteerSharp.Page.html#PuppeteerSharp_Page_TypeAsync_System_String_System_String_PuppeteerSharp_Input_TypeOptions_

Looks like you need something like this:
`await page.TypeAsync("input[id='identifierId']", userid_, new TypeOptions {Delay = 400});`
