### ISSUE TITLE
when use PdfAsync, HeaderTemplate occludes content.

### ISSUE THREAD

**Issue by 956159241** [hardkoded/puppeteer-sharp#2103]
### When use PdfAsync, HeaderTemplate occludes content.

E.g.

```csharp
				await page.PdfAsync(@$"{output}", new PdfOptions
				{
					Format = PaperFormat.A4,
					DisplayHeaderFooter = true,
					PrintBackground = true,
					Landscape = true,
					HeaderTemplate = headerTemplate,
					FooterTemplate = footerTemplate
				});
```

### Expected behavior:
HeaderTemplate is in font of content.

### Actual behavior:
HeaderTemplate is on the content.

**Comment by kblok** [comment]
The PDF rendering depends on chromium, and we cannot change it. You can report this issue to [chromium](https://bugs.chromium.org/p/chromium/issues/list).
