### ISSUE TITLE
what's the equivalent function like:   page._client.on

### ISSUE THREAD

**Issue by Zero-Xiong** [hardkoded/puppeteer-sharp#2110]
Please help to translate the function below to C# 

await page._client.on('Page.downloadProgress', ({ state }) => {
    if (state === 'completed') {
      console.log('download completed. File location: ', downloadPath + '/' + fileName);
    }
  });

**Comment by kblok** [comment]
The equivalent would be `Page.Client.MessageReceived` received. There you can check for `MessageID == "Page.downloadProgress"` and parse `MessageData` (it's a JToken) to the object you need.

**Comment by Zero-Xiong** [comment]
> 

Thanks kblok!
