### ISSUE TITLE
The file size downloaded manually is different with Puppeteer-Sharp, Any possible options should be checked?

### ISSUE THREAD

**Issue by Zero-Xiong** [hardkoded/puppeteer-sharp#2115]
I am facing one weird issue.

FYI, I have button 'Download' in form, the button is using for generating Excel 2003 file based on the form search criteria. 

Now the problem is:  the downloaded generated file size is different with manually clicking and Puppeteer-Sharp, are there any options I should pass-in/or check?

**Comment by kblok** [comment]
Did you try headless/headful? Does the file still work?
Puppeteer doesn't do anything with the downloads.

**Comment by Zero-Xiong** [comment]
The most weird thing is:  I tried debug step by step (would be stopped by breakpoint), the downloaded file size is as same as the manual, but if I disable all breakpoint, the file size will be different.

I guess the point would be:  there should have some waiting checking logic or loop checking logic. because debugging step by step may have waiting period (I don't know, just making guess), but without breakpoint, there are no waiting or missing some checking.

For example:

  await downloadBtn.ClickAsync();
  await XXXXX   <----  here may miss some logic checking or waiting point

I dont know how to diagnose the root cause, appreciate for any helping offered.

**Comment by Zero-Xiong** [comment]
I have tried below but none of them is useful

await downloadBtn.ClickAsync();
await Task.Delay(3000);   // or  await page.WaitForTimeoutAsync(3000);

**Comment by Zero-Xiong** [comment]
below are trace log on debugging step by step:


trce: PuppeteerSharp.Connection[0]
      ? Receive {"method":"Page.downloadWillBegin","params":{"frameId":"80C5CB670D11FA3A2756D226C81A41A4","guid":"4338b1f7-9c36-4513-9eaf-d598e7145227","url":"https://XXXXXXXXXX","suggestedFilename":"Orders.xls"},"sessionId":"050FCFE58EF3C0FF0B503CAA503EAABC"}
trce: PuppeteerSharp.Connection[0]
      ? Receive {"method":"Page.downloadProgress","params":{"guid":"4338b1f7-9c36-4513-9eaf-d598e7145227","totalBytes":0,"receivedBytes":0,"state":"inProgress"},"sessionId":"050FCFE58EF3C0FF0B503CAA503EAABC"}
trce: PuppeteerSharp.Connection[0]
      ? Receive {"method":"Page.downloadProgress","params":{"guid":"4338b1f7-9c36-4513-9eaf-d598e7145227","totalBytes":0,"receivedBytes":4899,"state":"inProgress"},"sessionId":"050FCFE58EF3C0FF0B503CAA503EAABC"}
trce: PuppeteerSharp.Connection[0]
      ? Receive {"method":"Page.downloadProgress","params":{"guid":"4338b1f7-9c36-4513-9eaf-d598e7145227","totalBytes":0,"receivedBytes":4899,"state":"inProgress"},"sessionId":"050FCFE58EF3C0FF0B503CAA503EAABC"}
trce: PuppeteerSharp.Connection[0]
      ? Receive {"method":"Page.downloadProgress","params":{"guid":"4338b1f7-9c36-4513-9eaf-d598e7145227","totalBytes":4899,"receivedBytes":4899,"state":"inProgress"},"sessionId":"050FCFE58EF3C0FF0B503CAA503EAABC"}
trce: PuppeteerSharp.Connection[0]
      ? Receive {"method":"Page.downloadProgress","params":{"guid":"4338b1f7-9c36-4513-9eaf-d598e7145227","totalBytes":4899,"receivedBytes":4899,"state":"inProgress"},"sessionId":"050FCFE58EF3C0FF0B503CAA503EAABC"}
trce: PuppeteerSharp.Connection[0]
      ? Receive {"method":"Page.downloadProgress","params":{"guid":"4338b1f7-9c36-4513-9eaf-d598e7145227","totalBytes":4899,"receivedBytes":4899,"state":"completed"},"sessionId":"050FCFE58EF3C0FF0B503CAA503EAABC"}

**Comment by kblok** [comment]
We don't have a native waitForDownload event. You might need to listen to CDP events and wait for the `Page.downloadProgress` with state `complete`.

**Comment by Zero-Xiong** [comment]
Thanks Kblok!

I leave this open for few days in case if somebody knows better practise.

**Comment by Zero-Xiong** [comment]
I changed to HttpClient to post form in order to download the file. I will close this ticket. Thanks all!
