### ISSUE TITLE
Could not determine JSON object type for type PuppeteerSharp.ViewPortOptions. (Parameter 'content')

### ISSUE THREAD

**Issue by EnricoMatassa** [hardkoded/puppeteer-sharp#2199]
## Looking for some help? Get priority support by [sponsoring the project](https://github.com/sponsors/hardkoded)/

**Before you file a bug, have you:**

* Tried upgrading to newest version of PuppeteerSharp, to see if your issue has already been resolved and released?

yes..upgraded

* Checked existing open *and* closed [issues](https://github.com/kblok/puppeteer-sharp/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?

yes...we have not found the same error here or anywhere

* Tried reproducing your problem in a new isolated project?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/search?q=puppeteer-sharp).

### Description
This happens on await Puppeteer.ConnectAsync.  It is an intermittent bug that only happens on our azure instance.  We are unable to reproduce locally. We are unable to find a pattern that causes it.   We are using browserless.io.

The only option we set is for ViewPort sizing.  It never changes.  It is always:

              DefaultViewport = new ViewPortOptions()
                {
                    Height = 2000
                }

### Complete minimal example reproducing the issue
var connectOptions = new ConnectOptions()
{
    BrowserWSEndpoint = _configuration.BrowserLessIOToken.HasValue()
        ? $"{_configuration.BrowserLessIOEndpoint}/?token={*** OUR TOKEN HERE ***}"
        :*** OUR BROWSERLESS ENDPOINT HERE ***,
    DefaultViewport = new ViewPortOptions()
    {
        Height = 2000
    }
};

using (var browser = await Puppeteer.ConnectAsync(connectOptions))
{
    using (var page = await browser.NewPageAsync())
    {
         // logic for our capturing here
    }
}

### Expected behavior:

Puppeteer connects to browserless and we are able to proceed with our capture. 

### Actual behavior:

Crash with error:  Could not determine JSON object type for type PuppeteerSharp.ViewPortOptions. (Parameter 'content')

### Versions

* puppeteer-sharp: 9.1.0
* we are on .NET Core 2.0.

### Additional Information

We are never able to reproduce this locally.  It does work sometimes on our azure instance.  We had tried force restarts on our browserless instance.  We are tried many things but we still see this error too often.  Thanks!

**Comment by kblok** [comment]
Do you have the stack trace?

**Comment by EnricoMatassa** [comment]
@kblok no unfortunately we do not record the entire stack trace on error.  Just the error.Message.  Sorry wish I had that. I can probably work to get it added if that will help.  I just do not understand why this only breaks occasionally.  We just can't see a pattern for when it breaks vs when it works.  Incredibly frustrating...thanks for the help.

**Comment by kblok** [comment]
It's weird. I don't see a connection between `ViewPortOptions` and a `content` parameter. We have some `Content` parameters in `AddTagOptions` and `BoxModel`, but again, it looks unrelated. It will be hard to evaluate this without more info :(

**Comment by EnricoMatassa** [comment]
@kblok I have the full stacktrace and more details.

`
StackTrace exception from ContentImageGeneration.GenerateInternal:    at Newtonsoft.Json.Linq.JContainer.ValidateContent(Object content)

at PuppeteerSharp.ElementHandle.ScreenshotBase64Async(ScreenshotOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/ElementHandle.cs:line 129

at PuppeteerSharp.ElementHandle.ScreenshotDataAsync(ScreenshotOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/ElementHandle.cs:line 104

at PuppeteerSharp.ElementHandle.ScreenshotStreamAsync(ScreenshotOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/ElementHandle.cs:line 75

at VacationBuddy.Core.Services.ViewContentImageGenerationService.GenerateInternal(Guid viewUUID, String authToken, String basePortalUrl) in /home/vsts/work/1/s/src/Project.Core/Services/ViewContentImageGenerationService.cs:line 197`

The line 197 is our code.  It is where I try to capture to a bitmap:

`var image = SKBitmap.Decode(await captureTarget[0].ScreenshotStreamAsync());`

So this always works on our local dev machines but fails in Azure.   Does this help?  I am going to keep researching but I was hoping these details could help.  Thanks!!
