### ISSUE TITLE
macOS, PS 11.0.3 : "Collection was modified; enumeration operation may not execute."

### ISSUE THREAD

**Issue by IT-VBFK** [hardkoded/puppeteer-sharp#2300]
## Looking for some help? Get priority support by [sponsoring the project](https://github.com/sponsors/hardkoded)/

**Before you file a bug, have you:**

* Tried upgrading to newest version of PuppeteerSharp, to see if your issue has already been resolved and released?
* Checked existing open *and* closed [issues](https://github.com/kblok/puppeteer-sharp/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* Tried reproducing your problem in a new isolated project?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/search?q=puppeteer-sharp).

### Description

After upgrading to 11.0.3 I added `BrowserTag.Latest` as parameter for `BrowserFetcher.DownloadAsync()`. This yields into before mentioned exception when running my app: "Collection was modified; enumeration operation may not execute."

### Complete minimal example reproducing the issue

Complete means the code snippet can be copied into a unit test method in a fresh C# project and run.
Minimal means it is stripped from code not related to reproducing the issue.

```csharp
var fetcher = new BrowserFetcher();

InstalledBrowser _installedBrowser = await fetcher.DownloadAsync(BrowserTag.Latest);
```

E.g.

```csharp
// Arrange
var options = new LaunchOptions { /*  */ };
var chromiumRevision = BrowserFetcher.DefaultRevision;
var browser = await Puppeteer.LaunchAsync(options, chromiumRevision);
var page = browser.NewPageAsync();

// Act
...

// Assert
...
```

### Expected behavior:

Downloads the latest version of browser X.

### Actual behavior:

Exception is raised.

### Versions

* Which version of PuppeteerSharp are you using? 
   * 11.0.3
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0. 
   * .NET7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

What's funny: if I omit the `BrowserTag.Latest` and use the parameter-less overload.. it downloads the lates version just fine.

**Comment by kblok** [comment]
Thank you for reporting this!
I will take a look at it.

**Comment by kblok** [comment]
@IT-VBFK v11.0.4 is on the way with the fix.
