### ISSUE TITLE
Encountering a problem when trying to run chrome.exe within my Azure Function path  . "Error during browser operation: An error occurred trying to start process 'C:\home\chrome-win\Win64-1108766\chrome-win\chrome.exe' with working directory 'C:\home\site\wwwroot'. The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail."

### ISSUE THREAD

**Issue by naveenkumar-kiwi** [hardkoded/puppeteer-sharp#2331]
My function where am creating pdf from url

![image](https://github.com/hardkoded/puppeteer-sharp/assets/92914502/f1df8977-25ea-4d30-9729-2bd63882375b)

` public async Task GeneratePdfReportAsync(string pdfData, string fileName, ILogger logger)
 {

     try
     {

         logger.LogInformation("Started PDF generation.");

         //"C:\\Users\\naveen\\AppData\\Local\\Temp\\chrome-win" -- temp path folder in local
         // Create a temporary directory to store Chromium
         string chromiumDownloadPath = Path.Combine(@"C:\home", "chrome-win");
         Directory.CreateDirectory(chromiumDownloadPath);
         logger.LogInformation("Step 2.");
         // Create a BrowserFetcher to download Chromium
         var browserFetcher = new BrowserFetcher(new BrowserFetcherOptions
         {
             Path = chromiumDownloadPath
         });
         logger.LogInformation("Step 3.");
         // Download Chromium
         await browserFetcher.DownloadAsync(BrowserFetcher.DefaultChromiumRevision);

         logger.LogInformation("Step 4.");

         // Launch Puppeteer using the downloaded Chromium executable
         var browser = await Puppeteer.LaunchAsync(new LaunchOptions
         {
             Headless = true,
             ExecutablePath = Path.Combine(chromiumDownloadPath, "Win64-1108766", "chrome-win", "chrome.exe")

         });

         var page = await browser.NewPageAsync();

         string responseMessage = await page.GetContentAsync();
         logger.LogInformation("New page created successfully.");

         string encodedPdfData = WebUtility.UrlEncode(pdfData);

         string url = $"https://htmltopdftemplates.blob.core.windows.net/htmltopdftemplates/report.html?data={pdfData}";
         logger.LogInformation($"Navigating to URL: {url}");

         await page.GoToAsync(url);
         logger.LogInformation("Page navigation successful.");
         await page.EmulateMediaTypeAsync(MediaType.Screen);
         logger.LogInformation("Media type emulation successful.");

         // Generate PDF
         var pdfOptions = new PdfOptions { Format = PaperFormat.A4 };
         var pdfStream = await page.PdfStreamAsync(pdfOptions);
         logger.LogInformation("PDF Stream generated successfully.");

         // Upload PDF to Azure Blob Storage
       

         await browser.CloseAsync();
         logger.LogInformation("Browser closed successfully.");
     }
     catch (Exception ex)
     {
         logger.LogError($"Error during browser operation: {ex.Message}");
         throw;
     }

 }`   after steo 4 logs . am getting issue after this line      

  ```
 // Launch Puppeteer using the downloaded Chromium executable
         var browser = await Puppeteer.LaunchAsync(new LaunchOptions
         {
             Headless = true,
             ExecutablePath = Path.Combine(chromiumDownloadPath, "Win64-1108766", "chrome-win", "chrome.exe")

         });
```
am using .net 7 and pupeeter version was 10.1.4

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] 2417
```

**Comment by kblok** [comment]
Please clean up your issue. It's hard to follow
