### ISSUE TITLE
BrowserFetcher does not contain a definition for DefaultRevision

### ISSUE THREAD

**Issue by rodrigofbm** [hardkoded/puppeteer-sharp#2332]
### Description

[Description of the issue]
I'm trying to use the example from the docs with Blazor on .net 7 but I'm getting an error.
### Complete minimal example reproducing the issue

E.g.

```csharp
 using var browserFetcher = new BrowserFetcher();
 await browserFetcher.DownloadAsync(BrowserFetcher.DefaultRevision);
 var browser = await Puppeteer.LaunchAsync(new LaunchOptions
 {
    Headless = true
 });
 var page = await browser.NewPageAsync();
 await page.GoToAsync("http://www.google.com");
 await page.ScreenshotAsync("test.pdf");
```

### Expected behavior:
Example code from docs works.

### Actual behavior:
Getting `BrowserFetcher does not contain a definition for DefaultRevision`

### Versions

* Which version of PuppeteerSharp are you using? 12.0.0
* Which .NET runtime and version are you targeting? .Net 7

### Additional Information
I've downgraded the version to 10.x but since I'm trying to use this within Blazor project I get a runtime error:
`System.Net.WebClient is not supported on this platform. Use System.Net.Http.HttpClient instead`
I just think that's related to PuppeteerSharp too.

**Comment by 1911trp** [comment]
I think you need to use a BrowserTag enumeration like BrowserTag.Stable now.

**Comment by kblok** [comment]
You can just do

```
await browserFetcher.DownloadAsync();
```

I need to review the WebClient error

**Comment by 1911trp** [comment]
In 10.0.0.0, browserFetcher.DownloadAsync( BrowserFetcher.DefaultChromiumRevision ) will download Win64-1069273 (v 109.0.5412.0) on Windows 7 and Win 2008 r2.

In later versions of PuppeteerSharp 10, 11 and 12, any overload of browserFetcher.DownloadAsync() results in a version greater than 109.0.5412.0 which is not compatible with Windows 7 or 2008 r2.

For our purposes, I reverted to 10.0.0.0.

**Comment by 1911trp** [comment]
I had time to sift through the code for version 12 to get a better understanding of what's happening. This is a fantastic library/solution but the documentation is a bit lacking. Totally understand. It's hard to write code and test and fix bugs AND WRITE DOCUMENTATION.
The latest version of Chrome/Chromium that is supported by Windows 7 / 2008 r2 is 109.0.5414.120. The latest available Chromium version is build "1070054" which resolves to version 109.0.5414.0.
So I'm performing an OS version check to determine if it's Windows 10 or earlier. For earlier versions, I'm using SupportedBrowser.Chromium and build ID string of "1070054" when calling DownloadAsync.
For Windows 10 and above, SupportedBrowser.Chromium and BrowserTag.Latest or SupportedBrowser.Chrome with either the Latest or Stable BrowserTag enumerator.

**Comment by Captain-HeMo** [comment]
Similar situation:

PuppeteerSharp 20.1.2
.NET Framework 4.8.1
Windows 10
VS 2022
VB.NET

`Await browserFetcher.DownloadAsync(browserFetcher.DefaultRevision)`

BrowserFetcher does not contain a definition for DefaultRevision

**Comment by kblok** [comment]
> Similar situation:
> 
> PuppeteerSharp 20.1.2 .NET Framework 4.8.1 Windows 10 VS 2022 VB.NET
> 
> `Await browserFetcher.DownloadAsync(browserFetcher.DefaultRevision)`
> 
> BrowserFetcher does not contain a definition for DefaultRevision

Same answer https://github.com/hardkoded/puppeteer-sharp/issues/2332#issuecomment-1739856962
