### ISSUE TITLE
BrowserContextOptions parameter is missing in CreateIncognitoBrowserContextAsync

### ISSUE THREAD

**Issue by leandroconsiglio** [hardkoded/puppeteer-sharp#2342]
Hi! 

Reading the Puppeteer documentation (https://pptr.dev/api/puppeteer.browser.createincognitobrowsercontext) createIncognitoBrowserContext have an optional parameter BrowserContextOptions, whichs allow to configure a proxy per context without the need to create a new browser instance if you want to change proxy on the fly.

But in the equivalent method CreateIncognitoBrowserContextAsync, it's not possible to pass that optional parameter.

**Comment by kblok** [comment]
Great find. [Upstream change for reference](https://github.com/puppeteer/puppeteer/commit/8e45a1c882207cc36e87be2a917b661eb841c4bf)
