### ISSUE TITLE
[Question] How to enable JS and cookies so the request does not get blocked?

### ISSUE THREAD

**Issue by stefanMinch3v** [hardkoded/puppeteer-sharp#2351]
### Description

Hello,
I'm getting 'Enable JavaScript and cookies to continue' message in the html when I try to grab the data from a specific website that apparently has some security enabled.
Anyone has an idea how to fix it?

E.g.

```csharp
var BaseUrl = "website url";

using var browserFetcher = new BrowserFetcher();
await browserFetcher.DownloadAsync();
await using var browser = await Puppeteer.LaunchAsync(new LaunchOptions { Headless = true });
await using var page = await browser.NewPageAsync();
await page.GoToAsync(BaseUrl);
await page.SetJavaScriptEnabledAsync(true); // enabled
var cookies = await page.GetCookiesAsync();
var cookie = cookies.FirstOrDefault();
await page.SetCookieAsync(new CookieParam // added cookie
{
	Name = cookie?.Name,
	Value = cookie?.Value,
	Domain = cookie?.Domain,
	Expires = cookie?.Expires,
	HttpOnly = cookie?.HttpOnly,
	Path = cookie?.Path,
	SameSite = cookie?.SameSite,
	Secure = cookie?.Secure,
	Session = cookie?.Session,
	Size = cookie?.Size,
	Url = cookie?.Url
});
var html = await page.GetContentAsync();
...
```

### Expected behavior:

To proceed and get the website correct HTML

### Actual behavior:

Enable JavaScript and cookies to continue - shown in the html and cannot get further

### Versions

* Version of Puppeteer - 12.0.0
* Dotnet6

**Comment by kblok** [comment]
Cookies and Javascript are enabled by default. Do you have a public website to reproduce it?

**Comment by stefanMinch3v** [comment]
Yes - https://www.shell.dk/customer-service/priser-pa-benzin-og-diesel.html

**Comment by kblok** [comment]
@stefanMinch3v do you mean this message?
<img width="657" alt="image" src="https://github.com/hardkoded/puppeteer-sharp/assets/2198466/bf581fd8-fbf7-4840-a0ab-0caa258cce88">

**Comment by stefanMinch3v** [comment]
When I run the code from the example above, in the html variable I get long content that has somewhere in the middle of if:
`<noscript>
               <div id="challenge-error-title">
                  <div class="h2">
                     <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                     </span>
                     <span id="challenge-error-text">Enable JavaScript and cookies to continue</span>
                  </div>
               </div>
            </noscript>`
            
  I'm not sure how did you get the one with Cookies pop-up. If i manage to go to that one probably could use the click btn?
  What em I doing wrong?

**Comment by kblok** [comment]
That script is typical. You will find it on many websites. It will show up if javascript is disabled. However having that content in the HMLT doesn't mean that it will be shown to the user.

**Comment by stefanMinch3v** [comment]
Hmm, so I need to navigate to the page => then click OK button and then will have the full page on the HTML response is that it?
With the code I provided I don't even get that Pop-up for cookies, how can I fix that any idea?

**Comment by kblok** [comment]
I got a complete HTML of the URL you provided.
[test.html.zip](https://github.com/hardkoded/puppeteer-sharp/files/13227726/test.html.zip)

**Comment by stefanMinch3v** [comment]
Are you downloading the html result and are you using the same code as mine?

**Comment by kblok** [comment]
I used this 

```
using System;
using System.Linq;
using System.IO;
using System.Threading.Tasks;
using PuppeteerSharp;

namespace PuppeteerSharpPdfDemo
{
    class MainClass
    {
        public static async Task Main(string[] args)
        {
            var options = new LaunchOptions
            {
                Headless = false
            };

            Console.WriteLine("Downloading chromium");

            using var browserFetcher = new BrowserFetcher();
            await browserFetcher.DownloadAsync();

            Console.WriteLine("Navigating google");
            using (var browser = await Puppeteer.LaunchAsync(options))
            using (var page = await browser.NewPageAsync())
            {
                await page.GoToAsync("https://www.shell.dk/customer-service/priser-pa-benzin-og-diesel.html");
                File.WriteAllText("test.html", await page.GetContentAsync());
            }
        }
    }
}
```

**Comment by stefanMinch3v** [comment]
Okay, so you have `Headless = false` and then save to file, my example is the `Headless = true` and do not save to a file. Thanks will try that and see if it works

**Comment by kblok** [comment]
Ohh I see. It seems that website doesn't like headless mode!

**Comment by kblok** [comment]
I see Cloudfare is there. There are many reports about puppeteer issues with cloudfare. [See](https://www.zenrows.com/blog/puppeteer-cloudflare-bypass#using-puppeteer-extra-plugin-stealth).

**Comment by stefanMinch3v** [comment]
Found this repo that has the StealthPlugin enabled - https://github.com/Overmiind/Puppeteer-sharp-extra
