### ISSUE TITLE
How to set the ‘download.default_directory’

### ISSUE THREAD

**Issue by 84819760** [hardkoded/puppeteer-sharp#2368]
I hope to modify the default download directory of the browser, but I don't know how to implement it。

xx.AddUserProfilePreference('download.default_directory','d:\download')
xx.AddUserProfilePreference('savefile.default_directory','d:\download')

**Comment by kblok** [comment]
That's a selenium API. You can solve that in puppeteer by sending a message to the browser telling the download location

```
await page.Client.SendAsync("Page.setDownloadBehavior", new
{
    behavior = "allow",
    downloadPath = _downloadDirectory,
});
```
