### ISSUE TITLE
Do you have any plans for add TouchScreen swipe (move)?

### ISSUE THREAD

**Issue by SleepyF0X** [hardkoded/puppeteer-sharp#2369]
https://github.com/zhgqthomas/puppeteer/commit/9f54be7bd5937c4224e10554b76270ce7357ef8a

**Comment by kblok** [comment]
@SleepyF0X, that code is not official. We only implement features implemented if the [official repo](https://github.com/puppeteer/puppeteer). I would start asking for swipe support there.
