### ISSUE TITLE
Upgrade to 13.0.1 Causes Object Reference Exception for Screenshotting in Page.cs on Line 1296

### ISSUE THREAD

**Issue by codeswithgrace** [hardkoded/puppeteer-sharp#2372]
We recently upgraded our PuppeteerSharp NuGet package from 12.0.0 to 13.0.1 and this caused all of our IPage.ScreenshotDataAsync calls to begin throwing object reference exceptions at line 1296 in Page.cs in the PerformScreenshot() method:

`if (Browser.Launcher.Options.Browser == SupportedBrowser.Firefox)`

I believe **Browser** or **Browser.Launcher** or **Browser.Launcher.Options** is null in this context and is causing the exception.  I tried explicitly setting the browser to Chromium when we instantiate PuppeteerSharp, hoping this would get us passed the exception on line 1296, but I was unsuccessful.

We're using PuppeteerSharp with a .NET8 website.  We have no issues with 12.0.0.

Full exception message:
Object reference not set to an instance of an object.

**Comment by kblok** [comment]
Hey @codeswithgrace, Can you tell me how you are launching the browser?

**Comment by codeswithgrace** [comment]
Thanks for the fast response.  It looks like you already committed a fix, but I'll answer your question anyhow:

We've centralized our PuppeteerSharp usage by creating the following wrapper class:
`public static class PuppeteerService
{
	private static IBrowser _browser = null;
	private static SemaphoreSlim _semaphoreSlim = new SemaphoreSlim(1, 1);

	#region - Public Methods -
		
	public static async Task<PuppeteerResult> RequestPageAsync(PuppeteerRequestArgs args)
	{
		if (!args.ViewportWidth.HasValue)
			args.ViewportWidth = RprConfigurationManager.GetAppSetting<int>("PuppeteerDefaultViewportWidth");
		if (!args.ViewportHeight.HasValue)
			args.ViewportHeight = RprConfigurationManager.GetAppSetting<int>("PuppeteerDefaultViewportHeight");
		if (!args.DeviceScaleFactor.HasValue)
			args.DeviceScaleFactor = RprConfigurationManager.GetAppSetting<double>("PuppeteerDefaultDeviceScaleFactor");

		try
		{
			await _semaphoreSlim.WaitAsync();
			try 
			{
				if (_browser == null)
				{
					var startDateTime = DateTime.UtcNow;
					_browser = await LaunchBrowserAsync(args);
				}
			}
			finally
			{
				_semaphoreSlim.Release();
			}

			var result = new PuppeteerResult();
			result.Browser = await Puppeteer.ConnectAsync(new ConnectOptions { BrowserWSEndpoint = _browser.WebSocketEndpoint, DefaultViewport = new ViewPortOptions { Width = args.ViewportWidth.Value, Height = args.ViewportHeight.Value, DeviceScaleFactor = args.DeviceScaleFactor.Value } });
			result.Page = await result.Browser.NewPageAsync();
			await result.Page.SetCacheEnabledAsync(args.CacheEnabled);
			await result.Page.GoToAsync(args.RequestUrl, new NavigationOptions { Timeout = (int)args.PageLoadTimeout.TotalMilliseconds, WaitUntil = [ args.WaitUntilNavigation ?? WaitUntilNavigation.Networkidle0 ]});
			if (args.ConsoleMessageReceivedTaskCompletionSource != null)
				await args.ConsoleMessageReceivedTaskCompletionSource.Task;
			return result;
		}
		catch (Exception exception)
		{
			// Log Exception to DB
			throw;
		}
	}

	private static async Task<IBrowser> LaunchBrowserAsync(PuppeteerRequestArgs args)
	{
		// Set up launch args.
		var launchArgsText = RprConfigurationManager.GetAppSetting("PuppeteerLaunchArgs");
		var noZygote = RprConfigurationManager.GetAppSetting<bool>("PuppeteerNoZygote");
		if (!args.Headless) launchArgsText = launchArgsText.Replace("headless,", "");
		var launchArgs = launchArgsText.Split(',').Select(a => $"--{a}").ToList();
		if (noZygote && !launchArgs.Contains("--no-zygote"))
			launchArgs.Add("--no-zygote");
		var userDataDirectory = RprConfigurationManager.GetAppSetting("PuppeteerUserDataDirectory");
		var launchOptions = new LaunchOptions
		{
			Headless = args.Headless
		};
		if (launchArgs.Any())
			launchOptions.Args = launchArgs.ToArray();
		if (!string.IsNullOrEmpty(userDataDirectory))
			launchOptions.UserDataDir = userDataDirectory;
		var chromiumInstallPath = RprConfigurationManager.GetAppSetting("PuppeteerChromiumInstallPath");
		var chromiumExecutableName = RprConfigurationManager.GetAppSetting("PuppeteerChromiumExecutableName");
		if (!Directory.Exists(chromiumInstallPath))
			throw new DirectoryNotFoundException(chromiumExecutableName == "chrome.exe" ? 
				$"You must download the latest *stable* version of Chromium from https://chromium.cypress.io/win64/ and extract it to {chromiumInstallPath}" :
				$"You must copy your Edge install files from C:\\Program Files (x86)\\Microsoft\\Edge\\Application and extract them to {chromiumInstallPath}");
		launchOptions.ExecutablePath = $"{chromiumInstallPath}\\{chromiumExecutableName}";

		// Launch new browser instance.
		IBrowser browser = null;
		try
		{
			var startDateTime = DateTime.UtcNow;
			browser = await Puppeteer.LaunchAsync(launchOptions);
			ChromiumStore.Add(browser, args);
			browser.Disconnected += async (sender, e) => await DisposeBrowserAsync();
		}
		catch (Exception exception)
		{
			// Log Exception to DB
			await DisposeBrowserAsync();
			throw;
		}
		return browser;
	}
		
	public static async Task DisposeBrowserAsync()
	{
		try
		{
			ChromiumStore.Remove(_browser);
			if (_browser != null)
			{
				await _browser.DisposeAsync();
				_browser = null;
			}
		}
		catch { }
	}

	#endregion
}

public class PuppeteerResult
{
	public IBrowser Browser { get; set; }

	public IPage Page { get; set; }

	public async Task DisposeAsync()
	{
		await Page?.GoToAsync("about:blank"); // https://github.com/puppeteer/puppeteer/issues/1490
		await Page?.CloseAsync();
		Browser?.Disconnect();
	}
}`

And here's an example call where we screenshot a map to get image bytes:
`PuppeteerResult result = null;
byte[] mapImageBytes;
try
{
	var pageRenderedTaskCompletionSource = new TaskCompletionSource<string>();
	using (var pageRenderedTimeoutCancellationTokenSource = new CancellationTokenSource())
	{
		pageRenderedTimeoutCancellationTokenSource.CancelAfter((int)_htmlToPdfPageRenderTimeout.TotalMilliseconds);
		pageRenderedTimeoutCancellationTokenSource.Token.Register(() => pageRenderedTaskCompletionSource.TrySetCanceled(), useSynchronizationContext: false);
		if (cancellationToken != default)
			cancellationToken.Register(() => pageRenderedTaskCompletionSource.TrySetCanceled(), useSynchronizationContext: false);
		var pageLoadTimeout = TimeSpan.FromSeconds(RprConfigurationManager.GetAppSetting<int>("ReportMapToImagePageLoadTimeoutInSeconds"));
		var args = new PuppeteerRequestArgs
		{
			RequestUrl = mapUrl,
			PageLoadTimeout = pageLoadTimeout,
			WaitUntilNavigation = WaitUntilNavigation.Load,
			ViewportWidth = width,
			ViewportHeight = height,
			CacheEnabled = true,
			DeviceScaleFactor = 1.0,
			ConsoleMessageFilter = "Map is ready...",
			ConsoleMessageReceivedTaskCompletionSource = pageRenderedTaskCompletionSource,
			ConsoleMessageReceivedTimeout = _htmlToPdfPageRenderTimeout
		};
		result = await PuppeteerService.RequestPageAsync(args);

		var screenshotOptions = new ScreenshotOptions
		{
			Quality = RprConfigurationManager.GetAppSetting<int>("ReportGenerationMapScreenshotsJpegQuality"),
			Clip = new Clip { Width = width, Height = height },
			Type = ScreenshotType.Jpeg
		};
					
		mapImageBytes = await result.Page.ScreenshotDataAsync(screenshotOptions);
	}
}
catch (Exception ex)
{
	Logging.Model.Instance.LogError(LoggingCategory, ex, userName);
	mapImageBytes = new byte[0];
}
finally
{
	if (result != null)
		await result.DisposeAsync();
}`

**Comment by kblok** [comment]
Ah you are using `ConnnectAsync`. So my fix should work.

**Comment by kblok** [comment]
@codeswithgrace v13.0.2 is getting cooked.

**Comment by NCLnclNCL** [comment]
> Cảm ơn đã phản ứng nhanh chóng. Có vẻ như bạn đã thực hiện sửa lỗi, nhưng dù sao tôi cũng sẽ trả lời câu hỏi của bạn:
> 
> Chúng tôi đã tập trung việc sử dụng PuppeteerSharp bằng cách tạo lớp trình bao bọc sau:
> 
> ```
> public static class PuppeteerService
> {
> 	private static IBrowser _browser = null;
> 	private static SemaphoreSlim _semaphoreSlim = new SemaphoreSlim(1, 1);
> 		
> 	public static async Task<PuppeteerResult> RequestPageAsync(PuppeteerRequestArgs args)
> 	{
> 		if (!args.ViewportWidth.HasValue)
> 			args.ViewportWidth = RprConfigurationManager.GetAppSetting<int>("PuppeteerDefaultViewportWidth");
> 		if (!args.ViewportHeight.HasValue)
> 			args.ViewportHeight = RprConfigurationManager.GetAppSetting<int>("PuppeteerDefaultViewportHeight");
> 		if (!args.DeviceScaleFactor.HasValue)
> 			args.DeviceScaleFactor = RprConfigurationManager.GetAppSetting<double>("PuppeteerDefaultDeviceScaleFactor");
> 
> 		try
> 		{
> 			await _semaphoreSlim.WaitAsync();
> 			try 
> 			{
> 				if (_browser == null)
> 				{
> 					var startDateTime = DateTime.UtcNow;
> 					_browser = await LaunchBrowserAsync(args);
> 				}
> 			}
> 			finally
> 			{
> 				_semaphoreSlim.Release();
> 			}
> 
> 			var result = new PuppeteerResult();
> 			result.Browser = await Puppeteer.ConnectAsync(new ConnectOptions { BrowserWSEndpoint = _browser.WebSocketEndpoint, DefaultViewport = new ViewPortOptions { Width = args.ViewportWidth.Value, Height = args.ViewportHeight.Value, DeviceScaleFactor = args.DeviceScaleFactor.Value } });
> 			result.Page = await result.Browser.NewPageAsync();
> 			await result.Page.SetCacheEnabledAsync(args.CacheEnabled);
> 			await result.Page.GoToAsync(args.RequestUrl, new NavigationOptions { Timeout = (int)args.PageLoadTimeout.TotalMilliseconds, WaitUntil = [ args.WaitUntilNavigation ?? WaitUntilNavigation.Networkidle0 ]});
> 			if (args.ConsoleMessageReceivedTaskCompletionSource != null)
> 				await args.ConsoleMessageReceivedTaskCompletionSource.Task;
> 			return result;
> 		}
> 		catch (Exception exception)
> 		{
> 			// Log Exception to DB
> 			throw;
> 		}
> 	}
> 
> 	private static async Task<IBrowser> LaunchBrowserAsync(PuppeteerRequestArgs args)
> 	{
> 		// Set up launch args.
> 		var launchArgsText = RprConfigurationManager.GetAppSetting("PuppeteerLaunchArgs");
> 		var noZygote = RprConfigurationManager.GetAppSetting<bool>("PuppeteerNoZygote");
> 		if (!args.Headless) launchArgsText = launchArgsText.Replace("headless,", "");
> 		var launchArgs = launchArgsText.Split(',').Select(a => $"--{a}").ToList();
> 		if (noZygote && !launchArgs.Contains("--no-zygote"))
> 			launchArgs.Add("--no-zygote");
> 		var userDataDirectory = RprConfigurationManager.GetAppSetting("PuppeteerUserDataDirectory");
> 		var launchOptions = new LaunchOptions
> 		{
> 			Headless = args.Headless
> 		};
> 		if (launchArgs.Any())
> 			launchOptions.Args = launchArgs.ToArray();
> 		if (!string.IsNullOrEmpty(userDataDirectory))
> 			launchOptions.UserDataDir = userDataDirectory;
> 		var chromiumInstallPath = RprConfigurationManager.GetAppSetting("PuppeteerChromiumInstallPath");
> 		var chromiumExecutableName = RprConfigurationManager.GetAppSetting("PuppeteerChromiumExecutableName");
> 		if (!Directory.Exists(chromiumInstallPath))
> 			throw new DirectoryNotFoundException(chromiumExecutableName == "chrome.exe" ? 
> 				$"You must download the latest *stable* version of Chromium from https://chromium.cypress.io/win64/ and extract it to {chromiumInstallPath}" :
> 				$"You must copy your Edge install files from C:\\Program Files (x86)\\Microsoft\\Edge\\Application and extract them to {chromiumInstallPath}");
> 		launchOptions.ExecutablePath = $"{chromiumInstallPath}\\{chromiumExecutableName}";
> 
> 		// Launch new browser instance.
> 		IBrowser browser = null;
> 		try
> 		{
> 			var startDateTime = DateTime.UtcNow;
> 			browser = await Puppeteer.LaunchAsync(launchOptions);
> 			ChromiumStore.Add(browser, args);
> 			browser.Disconnected += async (sender, e) => await DisposeBrowserAsync();
> 		}
> 		catch (Exception exception)
> 		{
> 			// Log Exception to DB
> 			await DisposeBrowserAsync();
> 			throw;
> 		}
> 		return browser;
> 	}
> 		
> 	public static async Task DisposeBrowserAsync()
> 	{
> 		try
> 		{
> 			ChromiumStore.Remove(_browser);
> 			if (_browser != null)
> 			{
> 				await _browser.DisposeAsync();
> 				_browser = null;
> 			}
> 		}
> 		catch { }
> 	}
> }
> 
> public class PuppeteerResult
> {
> 	public IBrowser Browser { get; set; }
> 
> 	public IPage Page { get; set; }
> 
> 	public async Task DisposeAsync()
> 	{
> 		await Page?.GoToAsync("about:blank"); // https://github.com/puppeteer/puppeteer/issues/1490
> 		await Page?.CloseAsync();
> 		Browser?.Disconnect();
> 	}
> }
> ```
> 
> Và đây là một lệnh gọi ví dụ trong đó chúng tôi chụp ảnh màn hình bản đồ để lấy byte hình ảnh:
> 
> ```
> PuppeteerResult result = null;
> byte[] mapImageBytes;
> try
> {
> 	var pageRenderedTaskCompletionSource = new TaskCompletionSource<string>();
> 	using (var pageRenderedTimeoutCancellationTokenSource = new CancellationTokenSource())
> 	{
> 		pageRenderedTimeoutCancellationTokenSource.CancelAfter((int)_htmlToPdfPageRenderTimeout.TotalMilliseconds);
> 		pageRenderedTimeoutCancellationTokenSource.Token.Register(() => pageRenderedTaskCompletionSource.TrySetCanceled(), useSynchronizationContext: false);
> 		if (cancellationToken != default)
> 			cancellationToken.Register(() => pageRenderedTaskCompletionSource.TrySetCanceled(), useSynchronizationContext: false);
> 		var pageLoadTimeout = TimeSpan.FromSeconds(RprConfigurationManager.GetAppSetting<int>("ReportMapToImagePageLoadTimeoutInSeconds"));
> 		var args = new PuppeteerRequestArgs
> 		{
> 			RequestUrl = mapUrl,
> 			PageLoadTimeout = pageLoadTimeout,
> 			WaitUntilNavigation = WaitUntilNavigation.Load,
> 			ViewportWidth = width,
> 			ViewportHeight = height,
> 			CacheEnabled = true,
> 			DeviceScaleFactor = 1.0,
> 			ConsoleMessageFilter = "Map is ready...",
> 			ConsoleMessageReceivedTaskCompletionSource = pageRenderedTaskCompletionSource,
> 			ConsoleMessageReceivedTimeout = _htmlToPdfPageRenderTimeout
> 		};
> 		result = await PuppeteerService.RequestPageAsync(args);
> 
> 		var screenshotOptions = new ScreenshotOptions
> 		{
> 			Quality = RprConfigurationManager.GetAppSetting<int>("ReportGenerationMapScreenshotsJpegQuality"),
> 			Clip = new Clip { Width = width, Height = height },
> 			Type = ScreenshotType.Jpeg
> 		};
> 					
> 		mapImageBytes = await result.Page.ScreenshotDataAsync(screenshotOptions);
> 	}
> }
> catch (Exception ex)
> {
> 	Logging.Model.Instance.LogError(LoggingCategory, ex, userName);
> 	mapImageBytes = new byte[0];
> }
> finally
> {
> 	if (result != null)
> 		await result.DisposeAsync();
> }
> ```
I want to ask what effect --no-zygote has
