### ISSUE TITLE
Protocol error (Emulation.setDeviceMetricsOverride) when calling NewPageAsync with Browserless.io

### ISSUE THREAD

**Issue by kirk-marple** [hardkoded/puppeteer-sharp#2391]
## Looking for some help? Get priority support by [sponsoring the project](https://github.com/sponsors/hardkoded)/

**Before you file a bug, have you:**

* Tried upgrading to newest version of PuppeteerSharp, to see if your issue has already been resolved and released?
* Checked existing open *and* closed [issues](https://github.com/kblok/puppeteer-sharp/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* Tried reproducing your problem in a new isolated project?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/search?q=puppeteer-sharp).

### Description

First time trying out PuppeteerSharp with Browserless.io.  Can't see any similar errors in the Github issues.

Calling NewPageAsync on IBrowser throws an exception complaining about the screen orientation angle.

> Failed to deserialize params.screenOrientation.angle - BINDINGS: mandatory field missing at position 93

```csharp
                var options = new ConnectOptions()
                {
                    BrowserWSEndpoint = $"wss://{settings.Api}?token={settings.Key}",
                };

                var browser = await Puppeteer.ConnectAsync(options); // this succeeds, and I can see I'm connected to a Chromium browser

                var page = await browser.NewPageAsync(); // this call throws the exception below
```

### Expected behavior:

New page to be created correctly.

### Actual behavior:

Protocol error (Emulation.setDeviceMetricsOverride): Invalid parameters Failed to deserialize params.screenOrientation.angle - BINDINGS: mandatory field missing at position 93
   at PuppeteerSharp.CDPSession.<SendAsync>d__35.MoveNext()
   at PuppeteerSharp.EmulationManager.<EmulateViewportAsync>d__4.MoveNext()
   at PuppeteerSharp.Page.<SetViewportAsync>d__192.MoveNext()
   at PuppeteerSharp.Page.<CreateAsync>d__245.MoveNext()
   at PuppeteerSharp.Page.<CreateAsync>d__245.MoveNext()
   at PuppeteerSharp.PageTarget.<PageAsync>d__8.MoveNext()
   at PuppeteerSharp.Browser.<CreatePageInContextAsync>d__85.MoveNext()
   at Graphlit.Frameworks.Knowledge.Services.PuppeteerHelpers.<OpenAsync>d__1.MoveNext() in C:\Projects\Graphlit\Graphlit Platform\src\Graphlit.Frameworks.Knowledge.Services\PuppeteerHelpers.cs:line 40

### Versions

* Which version of PuppeteerSharp are you using?

13.0.2

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.

.NET 6

**Comment by kblok** [comment]
@kirk-marple do you know what Chrome version is being used by browserless?

**Comment by kirk-marple** [comment]
> @kirk-marple do you know what Chrome version is being used by browserless? It's quite weird. We are always passing `params.screenOrientation.angle`.

I believe it's Chromium rather than Chrome, but not sure what version. I'm using the default Browserless.io (free account) API for now.

Is there anything in Puppeteer which would show the version, after I connect?

BTW, I just tried this with Microsoft.Playwright and it actually works as expected.

**Comment by kblok** [comment]
Would you mind sending the BrowserWSEndpoint to my email?

**Comment by kblok** [comment]
@kirk-marple I just created a browserless account and it worked for me.

**Comment by kirk-marple** [comment]
That's interesting, I was just using chrome.browserless.io as the endpoint.  Maybe they were having issues or something.

TBH, I moved over to Microsoft.Playwright, and it's working fine.  I only need it for HTML capture and screenshots.  

We can close this for now, and if I do get back to using PuppeteerSharp, I'll try this out again in future.

Appreciate the support!
