### ISSUE TITLE
Extra whitespace following tables in pdf

### ISSUE THREAD

**Issue by penarthur** [hardkoded/puppeteer-sharp#2410]
I am switching from an existing online conversion tool and have the pdf generation working but I am getting additional blank spaces after the table containing divs which I don't see when viewing my html in any live browser or in the old conversion tool - I've attached the html and the resulting pdf - any advice?

screenshot of how it should look: ![image](https://github.com/hardkoded/puppeteer-sharp/assets/42841989/08b0888a-782d-49b4-b238-6921f3da4dc7)
html : [M100526_b (2).zip](https://github.com/hardkoded/puppeteer-sharp/files/14038033/M100526_b.2.zip)
zip : [M100526_b.pdf](https://github.com/hardkoded/puppeteer-sharp/files/14038039/M100526_b.pdf)

**Comment by kblok** [comment]
Do you get that if you Print to PDF using Chrome?

**Comment by penarthur** [comment]
Sort of - Some sections do and some don't - pdf attached here - the first 4 appear as expected and the last few actually seem to start a new page ...
[Uploading Residential Mortgage AIP.pdf…]()
