### ISSUE TITLE
Blank Pages and Missing Content

### ISSUE THREAD

**Issue by mrdo23** [hardkoded/puppeteer-sharp#2438]
Hi there,

Not strictly a bug, most likely a config issue but I have tried posting in discussions:

https://github.com/hardkoded/puppeteer-sharp/discussions/2409

And on SO:

https://stackoverflow.com/questions/77868276/puppeteer-sharp-missing-content-and-blank-pages

I am running some code to take an HTML string, fetch some external CSS files and then save the formatted output as a PDF.
Unfortunately, I regularly receive incomplete output or blank pages, despite the same raw HTML being passed to puppeteer-sharp.
As per various SO posts, I have added 'WaitUntilNavigation.Networkidle0' and 'WaitForSelectorAsync' code to see if that helps but the problem persists.

Can someone suggest any tweaks that might resolve the issue?

As you can see, I have added an html element to the html and am waiting for that to be rendered (#lastelement) but suspect it may be related to the external css.

```
using (Browser browser = await Puppeteer.LaunchAsync(launchOptions))
            {
                using (var page = await browser.NewPageAsync())
                {

                    await page.SetContentAsync(pageHTML, new NavigationOptions { WaitUntil = new[] { WaitUntilNavigation.Networkidle0 } });

                    // pull in main css from site for formatting
                    AddTagOptions css = new AddTagOptions() { Url = "https://MYURL.COM/main.css" };
                    await page.AddStyleTagAsync(css);
                    // pull in font-awesome css from site for formatting - linking to our own copy doesn't seem to work
                    AddTagOptions cssFA = new AddTagOptions() { Url = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" };
                    await page.AddStyleTagAsync(cssFA);


                    await page.AddStyleTagAsync(new AddTagOptions { Content = inlineCSS });

                    await page.GetContentAsync();

                    await page.WaitForSelectorAsync("#lastelement");

                    var file = await page.PdfDataAsync(pdfOptions);

                    var fileName = "result.pdf";

                    return new FileContentResult(file, "application/pdf")
                    {
                        FileDownloadName = fileName
                    };
                }
            }
```

**Comment by kblok** [comment]
Let's keep the conversation in the discussion :)
