### ISSUE TITLE
Obsolete documentation page?

### ISSUE THREAD

**Issue by ferenc-a** [hardkoded/puppeteer-sharp#2477]
There's these two files:
1. https://github.com/hardkoded/puppeteer-sharp/blob/master/docfx_project/examples/LodCDP.md
2. https://github.com/hardkoded/puppeteer-sharp/blob/master/docfx_project/examples/LogCDPCommunication.md

The first one seems to be an obsolete version of the second, judging by its history: https://github.com/hardkoded/puppeteer-sharp/commits/master/docfx_project/examples/LodCDP.md

#1871 renamed it and #1893 seems to have accidentaly recreated it.

**Comment by kblok** [comment]
Thank you for reporting it @ferenc-a!

**Comment by kblok** [comment]
@ferenc-a did you find [LodCDP.md](https://github.com/hardkoded/puppeteer-sharp/blob/master/docfx_project/examples/LodCDP.md) in some link?

**Comment by ferenc-a** [comment]
No. I think I was searching the repo for "logging" as a first step to figuring it out, and it came up first: https://github.com/search?q=repo%3Ahardkoded%2Fpuppeteer-sharp+logging+-path%3A*.cs&type=code.
