### ISSUE TITLE
Error event not raised when page crashes

### ISSUE THREAD

**Issue by Madajevas** [hardkoded/puppeteer-sharp#2494]
### Description

* I am starting browser like `var browser = Puppeteer.LaunchAsync(new LaunchOptions { Headless = true);`
* Creating a page `var page = browser.NewPageAsync()`
* Hooking on error event: `page.Error += (e, a) => System.Diagnostics.Debugger.Break();`
* Navigating to page that has memory leak and in crashed the page. JS to crash:
  ```
  <script type="text/javascript">
      var a = [...Array(2 ** 32 - 1)];
  </script>
  ```

Page does crash, however error (PageError too) event is never raised. Am I missing something?

### Versions
Observed on .NET8 and PuppeteerSharp 14.1.0 (have not tried any older version).

**Comment by Madajevas** [comment]
Even your sample does not raise the event... Full html file I use:
```html
<html>
 <head>
  <title>Crash it</title>
 </head>
 <body>
  <script type="text/javascript">
    var a = [...Array(2 ** 32 - 1)];
  </script>
 </body>
</html>
```

**Comment by kblok** [comment]
I used pretty much the same HTML

```
<html>
<head>
    <title>Crash</title>
</head>
<body>
  <script type="text/javascript">
    var a = [...Array(2 ** 32 - 1)];
</script>
    <h1>Crash</h1>
    <p>Crash</p>
</body>
</html>
```

**Comment by Madajevas** [comment]
It must be something with my local chrome installation. Tried executing the same inside docker container and it worked as expected.
