### ISSUE TITLE
SetContentAsync is slower in version 15.0/15.1

### ISSUE THREAD

**Issue by nowakpaw** [hardkoded/puppeteer-sharp#2513]
Hi. We just moved to the newest version (15.0 and 15.1).
We have noticed that page.SetContentAsync is now much slower than on 14.1 (previously less than one second, now almost 2 seconds).
What might be the cause of that?

We are using .NET 8.

**Comment by nowakpaw** [comment]
Thanks for reply. We are trying few combinations of puppeteer-sharp / chrome versions. I'll keep You updated.

**Comment by nowakpaw** [comment]
We tested 13.0.2, 14.1, 15.0 and 15.1 with chrome versions: 120.0.6099.71, 122.0.6261.128 and 123.0.6312.58. We got the best performance on pairs: 13.0.2 - 120.0.6099.71, 14.1 - 120.0.6099.71. Unfortunately, we don't know why exactly, but we suspect Chrome/Chromium changes. I think we can close this issue, as long it's ok for You.

**Comment by kblok** [comment]
@nowakpaw v15 also introduced the new headless mode by default. You can try using `HeadlessMode = HeadlessMode.Shell` instead of `Headless = false`.

Let's close the issue. But we can keep the conversation with the issue closed till we find something to work on.
