### ISSUE TITLE
Strange behavior of ScreenshotAsync under load.

### ISSUE THREAD

**Issue by Slepoyi** [hardkoded/puppeteer-sharp#2575]
### Description
I decided to use puppeteer to take screenshots of web pages. 

I created an image generating service, wrapped the puppeteer browser up with a singleton (browser pool) and exposed this method through a minimal api endpoint.

I began with some basic load testing using nbomber. After test finished I found out that there are less images in the output directory then there should be. I added logging to screenshot generation method to see which step fails and I found it. For some traces I could only see logs about successfull setContent completeion but nothing more was in the log. Eg:

> 2024-03-28 17:37:47.057 +03:00 [WRN] Trace id: 0HN2F6I4GU6QQ:00000001: setContent time 48,7593
> //no screenshot time and global time for trace 0HN2F6I4GU6QQ:00000001 was written into the log

That means that ScreenShotAsync hangs forever. I don't see any other errors in logs. The application itself works fine though, it responses to another requests like nothing happened.

Is that a browser which cannot handle like a bit more than 30 opened pages, screenshots queue issues or something else?

### Complete minimal example reproducing the issue

Img service:

```csharp

public interface IBrowserPool
{
    Task<IBrowser?> GetLaunchedBrowserAsync();
}

public class BrowserPool : IBrowserPool
{
    private readonly ILogger _logger;
    private readonly ResourceLockerStorage _lockerStorage; //trick with semaphore to await inside the lock

    private IBrowser? _browser;

public BrowserPool(
    ILogger<BrowserPool> logger,
    ResourceLockerStorage lockerStorage)
{
    _logger = logger;
    _lockerStorage = lockerStorage;
}

public async Task<IBrowser?> GetLaunchedBrowserAsync()
{
    if (_browser is null)
    {
        var key = $"{nameof(BrowserPool)}:{nameof(GetLaunchedBrowserAsync)}";
        var locker = _lockerStorage.GetOrCreateLocker(key);
        if (!await locker.WaitAsync(10_000))
        {
            _logger.LogError("{method}. Locker timeout expired", nameof(GetLaunchedBrowserAsync));
            return null;
        }

        try
        {
            _browser ??= await DownloadAndLaunchBrowserAsync();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "{method}. Exception while starting browser", nameof(GetLaunchedBrowserAsync));
        }
        finally
        {
            locker.Release();
        }
    }

    return _browser;
}
}

public interface IImageGenService
{
    Task GenerateImageFileAsync(string filePath, string pageContent);
}
public class ImageGenService : IImageGenService
{
    public async Task GenerateImageFileAsync(string filePath, string pageContent)
    {
        var globalTimer = Stopwatch.StartNew();
        
        var browser = await _browserPool.GetLaunchedBrowserAsync();

        using var page = await browser.NewPageAsync();
        await page.SetContentAsync(pageContent, new NavigationOptions { Timeout = 10000 }); 
        _logger.LogWarning($"Trace id: {_httpContextAccessor.HttpContext.TraceIdentifier}: setContent time {globalTimer.Elapsed.TotalMilliseconds}");
        await page.ScreenshotAsync(filePath);
        _logger.LogWarning($"Trace id: {_httpContextAccessor.HttpContext.TraceIdentifier}: screenshot time {globalTimer.Elapsed.TotalMilliseconds}");
        await page.CloseAsync();
        _logger.LogWarning($"Trace id: {_httpContextAccessor.HttpContext.TraceIdentifier}: global time {globalTimer.Elapsed.TotalMilliseconds}");
    }
}

public static class ImgGenEndpoints
{
    public static void MapImgGenEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("api/gen/").WithTags("ImgGen").AllowAnonymous();

        group.MapPost("/", async ([FromBody]GenImgRequest request, IImageGenService svc) =>
        {
            await svc.GenerateImageFileAsync(request.FilePath, request.Content);
        });
    }
}

public class GenImgRequest
{
    public string FilePath { get; set; }
    public string Content { get; set; }
}
```

bomber code:

```csharp
using var httpClient = new HttpClient();

var content = @"
<html>
<body>
    <h1>Test</h1>
</body>
</html>
";
var url = $"http://localhost/api/gen/genImg/";

var scenario = Scenario.Create("hello_world_scenario", async context =>
{
    var req = new
    {
        FilePath = $"C:\\Temp\\spam\\{Guid.NewGuid()}.jpg",
        Content = content
    };

    var request = Http.CreateRequest("POST", url)
                        .WithBody(JsonContent.Create(req));

    var response = await Http.Send(httpClient, request);

    return response;
})
    .WithoutWarmUp()
    .WithLoadSimulations(
    Simulation.Inject(rate: 10,
                      interval: TimeSpan.FromSeconds(1),
                      during: TimeSpan.FromSeconds(30)));

NBomberRunner
    .RegisterScenarios(scenario)
    .WithWorkerPlugins(new HttpMetricsPlugin(new[] { HttpVersion.Version1 }))
    .Run();

```

### Expected behavior:

End up with _n_ files in output dir, where _n_ - total amount of requests sent by load testing program.

### Actual behavior:

End up with less than _n_ files in output dir

### Versions

* Which version of PuppeteerSharp are you using?
15.1.0

* Which .NET runtime and version are you targeting?
.NET8

**Comment by kblok** [comment]
First of all, you have to remember that you are automating a real chrome browser. 30 tabs is a lot! I tend to use 5.
On the other hand, the screenshot logic has a queue. So you can't take 30 screenshots at the same time; they will go one by one.
I would try reducing the number of open tabs.

**Comment by Slepoyi** [comment]
@kblok ty for fast reply!
Tried different approaches with pooling puppeteer resources (browsers and pages) but had no luck with that. This morning I decided to start from the very beginning. I launched load testing for one browser and switched to different task. Once I came back, I found the following messages in log:

> 2024-04-01 09:50:57.077 +03:00 [WRN] Trace id: 0HN2I2VMS0DIJ:00000001: setContent time 32,8601
> 2024-04-01 09:50:57.634 +03:00 [WRN] Trace id: 0HN2I2VMS0DIK:00000001: setContent time 29,6494
> 2024-04-01 09:50:58.135 +03:00 [WRN] Trace id: 0HN2I2VMS0DIL:00000001: setContent time 45,8854
> 2024-04-01 09:53:31.746 +03:00 [ERR] An unhandled exception has occurred while executing the request.
> System.TimeoutException: Timeout of 180000 ms exceeded
>    at PuppeteerSharp.Helpers.TaskHelper.WithTimeout[T](Task`1 task, TimeSpan timeout, Func`2 exceptionFactory) in Documents\git\puppeteer-sharp\lib\PuppeteerSharp\Helpers\TaskHelper.cs:line 180
>    at PuppeteerSharp.Cdp.CdpCDPSession.SendAsync(String method, Object args, Boolean waitForCallback, CommandOptions options) in Documents\git\puppeteer-sharp\lib\PuppeteerSharp\Cdp\CdpCDPSession.cs:line 112
>    at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args, CommandOptions options) in Documents\git\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 44
>    at PuppeteerSharp.Page.PerformScreenshot(ScreenshotType type, ScreenshotOptions options, ILogger logger, String trace) in Documents\git\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 1469
>    at PuppeteerSharp.Page.PerformScreenshot(ScreenshotType type, ScreenshotOptions options, ILogger logger, String trace) in Documents\git\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 1481
>    at PuppeteerSharp.Helpers.TaskQueue.Enqueue[T](Func`1 taskGenerator) in Documents\git\puppeteer-sharp\lib\PuppeteerSharp\Helpers\TaskQueue.cs:line 51
>    at PuppeteerSharp.Page.ScreenshotDataAsync(ScreenshotOptions options, ILogger logger, String trace) in Documents\git\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 770
>    at PuppeteerSharp.Page.ScreenshotAsync(String file, ScreenshotOptions options, ILogger logger, String trace) in Documents\git\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 705
>    at TestService.BL.ImgGen.GenerateImageFileAsync(String filePath, String pageContent) in Documents\git\dev\TestService\ImageGen\ImageService.cs:line 103
>    at TestService.Endpoints.ImgGenEndpoints.<>c.<<MapImgGenEndpoints>b__0_1>d.MoveNext() in Documents\git\dev\TestService\ImageGen\Endpoints\ImgGenEndpoints.cs:line 21
> --- End of stack trace from previous location ---
> 024-04-01 09:53:32.047 +03:00 [WRN] Trace id: 0HN2I2VMS0DH0:00000002: screenshot time 180493,3356
> 2024-04-01 09:53:32.056 +03:00 [WRN] Trace id: 0HN2I2VMS0DH0:00000002: global time 180502,1869
> 2024-04-01 09:53:32.142 +03:00 [WRN] Trace id: 0HN2I2VMS0DH2:00000001: screenshot time 179347,8951

As far as I understood, one process hangs dead and nothing will work until this exact process is disposed. This means that screenshot queue worker can't process incoming tasks?

**Comment by Slepoyi** [comment]
@kblok reducing the number of opened tabs sounds ok, but what if the application would be bombed with 10 rps? Even if I create a pool of opened tabs, I need to create the queue of screenshot requests which will be processe with some background worker which will wait until som page from the pool will be free to use. And there's already the screenshot queue in the library itself. So I there is a queue over a queue which sound weird to me.

**Comment by kblok** [comment]
@Slepoyi did you test it in headful mode? to see how the browser behaves?

**Comment by kblok** [comment]
@Slepoyi I don't know if it will help with multiple open tabs, but we have a `BurstMode` in the `ScreenshotOptions` that bypasses all the extra calls and makes a call to `Page.captureScreenshot`.

**Comment by Slepoyi** [comment]
The issue is absolutely reproducable on js version of puppeteer.

**Comment by Slepoyi** [comment]
Seems as it's browser related stuff. The only solution I came up with was adding retry policy.
