### ISSUE TITLE
ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory

### ISSUE THREAD

**Issue by Kiril1512** [hardkoded/puppeteer-sharp#2580]
### Description

Hello, we updated PuppeteerSharp from 14.1.0 to 15.1.0 and we no longer can launch the browser, throwing:
> PuppeteerSharp.ProcessException: Failed to launch browser! [0402/165106.392572:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)

### Complete minimal example reproducing the issue

We are launching the browser like:

```c#
private static async Task<IBrowser> GetAndLaunchOsMatchingBrowser()
{
    var browserFetcher = new BrowserFetcher();

    await browserFetcher.DownloadAsync();

    var launchOptions = new LaunchOptions
    {
        Args = new[] { "--no-sandbox", "--disable-setuid-sandbox" },
        Headless = true
    };

    return await Puppeteer.LaunchAsync(launchOptions);
}
```

And then register the browser in the container:

```c#
var browser = GetAndLaunchOsMatchingBrowser().GetAwaiter().GetResult();

builder.RegisterInstance(browser).As<IBrowser>().SingleInstance();
```

### Expected behavior:

Launching browser successfully like in 14.1.

### Actual behavior:

The browser did not start with the following log:
> 2024-04-02 17:51:06 Unhandled exception. PuppeteerSharp.ProcessException: Failed to launch browser! [0402/165106.392572:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)

### Versions

Upgraded from 14.1 to 15.1 on .NET 8.

### Additional Information

Service runtime: mcr.microsoft.com/dotnet/aspnet:8.0
We also install the following dependencies in order to run the browser:
```yaml
RUN apt-get update && apt-get install -y xorg openbox libnss3 libasound2
```

**Comment by kblok** [comment]
Can you try replacing `Headless = true` with `HeadlessMode = HeadlessMode.Shell`?

**Comment by Kiril1512** [comment]
> Can you try replacing `Headless = true` with `HeadlessMode = HeadlessMode.Shell`?

Yes it works updating the HeadlessMode like:
```c#
var launchOptions = new LaunchOptions
{
    Args = new[] { "--no-sandbox", "--disable-setuid-sandbox" },
    HeadlessMode = HeadlessMode.Shell
};
```

**Comment by kblok** [comment]
@Kiril1512 ok. So it's the browser then. Could you try downloading `123.0.6312.86`?

**Comment by Kiril1512** [comment]
> @Kiril1512 ok. So it's the browser then. Could you try downloading `123.0.6312.86`?

Using `await browserFetcher.DownloadAsync("123.0.6312.86");` I cannot even launch:
> Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/app/Chrome/Linux-123.0.6312.58/chrome-linux64/chrome' with working directory '/app'. No such file or directory

**Comment by kblok** [comment]
@Kiril1512 the recipe to run a custom revision is like this:

```
var revision = await browserFetcher.DownloadAsync("123.0.6312.86");
options.ExecutablePath = revision.GetExecutablePath();
```

Where `options` is the `LaunchOptions` you will pass to `LaunchAsync`.

**Comment by Kiril1512** [comment]
> @Kiril1512 the recipe to run a custom revision is like this:
> 
> ```
> var revision = await browserFetcher.DownloadAsync("123.0.6312.86");
> options.ExecutablePath = revision.GetExecutablePath();
> ```
> 
> Where `options` is the `LaunchOptions` you will pass to `LaunchAsync`.

@kblok sorry for that, I did not see that it was starting the wrong version in the log... I updated the executablePath and indeed it is working with that Chrome version with Headless as true:

```c#
private static async Task<IBrowser> GetAndLaunchOsMatchingBrowser()
{
    var browserFetcher = new BrowserFetcher();

    var revision = await browserFetcher.DownloadAsync("123.0.6312.86");

    var launchOptions = new LaunchOptions
    {
        Args = new[] { "--no-sandbox", "--disable-setuid-sandbox" },
        Headless = true,
        ExecutablePath = revision.GetExecutablePath()
    };

    return await Puppeteer.LaunchAsync(launchOptions);
}
```

**Comment by kblok** [comment]
Awesome then. Puppeteer updated the version a few days ago. I didn't know if it was that important. It seems it is :)

I'm cooking a new version for you right now.

**Comment by Kiril1512** [comment]
Amazing, thank you @kblok !

**Comment by kblok** [comment]
@Kiril1512 v16 is out! It has some tiny breaking changes. I hope it won't affect you.

**Comment by Kiril1512** [comment]
@kblok everething looks good with v16! Thank you!
