### ISSUE TITLE
Problem generating bookmarks/outlines

### ISSUE THREAD

**Issue by Acrylios** [hardkoded/puppeteer-sharp#2594]
Is there something I need to do on my end or should it work automatically?

Currently I have version 15.1.0 in my project and there are no bookmarks generated when looking in acrobat reader or chrome.

**Comment by kblok** [comment]
Did you set `Outline` to true?

**Comment by Acrylios** [comment]
Yeah I did. I have the following set as my PdfOptions

`new PdfOptions
                        {
                            Format = PaperFormat.A4,
                            DisplayHeaderFooter = true,
                            Landscape = landscape,
                            PageRanges = string.Empty,
                            PrintBackground = true,
                            MarginOptions = new MarginOptions
                            {
                                Top = "60px",
                                Right = "40px",
                                Bottom = "60px",
                                Left = "40px"
                            },
                            HeaderTemplate = header,
                            FooterTemplate = footer,
                            Outline = true
                        }`

**Comment by kblok** [comment]
I think you might need to report that on [chromiumbugs](https://issues.chromium.org/issues?q=status:open). We only send those properties to the browser.
