### ISSUE TITLE
Method not found / IJsHandle ExecutionContext

### ISSUE THREAD

**Issue by jaybee82** [hardkoded/puppeteer-sharp#2631]
### Description

While launch browser, an exception got raised:
Method not found: 'PuppeteerSharp.IExecutionContext PuppeteerSharp.IJSHandle.get_ExecutionContext()

### Complete minimal example reproducing the issue

var mainHtmlContent = await GetMainTemplateContentAsync(templateViewModel);

await new BrowserFetcher().DownloadAsync();

var launchOptions = new LaunchOptions
{
    Timeout = 50000
};
await using var browser = await Puppeteer.LaunchAsync(launchOptions); <- throws Exception

await using var page = await browser.NewPageAsync();
await page.SetContentAsync(mainHtmlContent);
...

### Expected behavior:

Create browser instance without issues

### Actual behavior:

Exception got raised, method not found.

### Versions

See exception with versions 13.0.0 to 17.0.0. Version 12.0.0 is working fine
Targeting .Net 8

### Additional Information

-

**Comment by kblok** [comment]
@jaybee82 can you share the stack trace?
