### ISSUE TITLE
How to watch or active for more than 1 tab in one chrome instance

### ISSUE THREAD

**Issue by wisamidris7** [hardkoded/puppeteer-sharp#2641]
Are there any solution for active cause some websites or 80% requires a active tab and puppeter does not have that so are there a solution i have this code

```c#
var page = await chatBrowser.NewPageAsync();
page.ExportToExternalWindow(); // I think this is cool name
```

Okay why cause more than one instance chrome instances is harmful for cpu and memory and more than tab in one chrome instance is better and as i said there are a feature in chrome it's this

https://github.com/hardkoded/puppeteer-sharp/assets/104096256/9c5997ad-9a74-4441-9012-6b5b0e1628be

And thanks!

**Comment by kblok** [comment]
Unfortunately I don't see a [CDP](https://chromedevtools.github.io/devtools-protocol/) to accomplish that. Sorry.
