### ISSUE TITLE
Improve docfx_project/examples/ReuseChrome.md

### ISSUE THREAD

**Issue by KyleC69** [hardkoded/puppeteer-sharp#2645]
In the provided example the BrowserFetcher is instantiated using the using clause. In version 18.0 of PuppeteerSharp that class no longer implements IDisposable. This is the code used. IDE:VisualCode v.189.1

      ` var downloadPath = "/home/apollo/Apps/Browser/Chromium";
        var bo = new BrowserFetcherOptions { Path = downloadPath };
        using var browserFetcher = new BrowserFetcher(bo);
        var browser = await browserFetcher.DownloadAsync();`

**Comment by kblok** [comment]
Thank you for reporting this @KyleC69!
