### ISSUE TITLE
Problems with frames in frames

### ISSUE THREAD

**Issue by 400ochkov** [hardkoded/puppeteer-sharp#2656]
Hello, I faced issue with frames, if website has frames which nested in another frames puppeeteersharp cant handle it.
I use code like

` foreach (IFrame frame in page.Frames){Console.WriteLine("frame "+ frame.Url);}`

and see only 2 frames when website has 6 frames each of them located in previous frame
Also I tried foreach (var childFrame in frame.ChildFrames) {} but doesnt help
I think it happened due to CORS

ps I work with antidetect browser, connect via ws

**Comment by kblok** [comment]
I was going through open issues, and I found this ticket was still open. Sorry about that. Do you still need help with this?

**Comment by 400ochkov** [comment]
As I remember prroblem exist after this fix but I haven't faced it on my projects which I develop by now, If I faced it again I let you know
