### ISSUE TITLE
fix: correct quality condition judgement

### ISSUE THREAD

**Issue by kblok** [hardkoded/puppeteer-sharp#2679]
[Original issue](https://www.github.com/puppeteer/puppeteer/issues/12725)

**Comment by jnyrup** [comment]
We don't have that issue in master
https://github.com/hardkoded/puppeteer-sharp/blob/eca16403b86f464f9182afae1b3bf2e4500950c1/lib/PuppeteerSharp/Page.cs#L490

as you didn't include that bug 😉 
https://github.com/hardkoded/puppeteer-sharp/pull/64/files#diff-931710f8aed996816251dcccbb05bca895c235368902afb19acd36be83ce5c02R427

**Comment by kblok** [comment]
Even better @jnyrup 😅
