### ISSUE TITLE
CookieSourceScheme Enum Missing StringEnumConverter JsonConverter

### ISSUE THREAD

**Issue by olegfridman** [hardkoded/puppeteer-sharp#2692]
### Description
When trying to set cookies that were originally captured from a page, the `SetCookieAsync` method throws an exception:

>Protocol error (Network.setCookies): Invalid parameters Failed to deserialize params.cookies.sourceScheme - BINDINGS: string value expected at position 450

Code:
```csharp
var cookieParams = await page.GetCookiesAsync();
await page.SetCookieAsync(cookieParams);
```

### Cause:

The `CookieSourceScheme` enum is missing `[JsonConverter(typeof(StringEnumConverter))]`.

This is set on other enums used in `CookieParam` like `CookiePriority`.

### Versions

* PuppeteerSharp 18.0.4
* .NET Framework 8

### Workaround
Not ideal, but as pointed out in [2648](https://github.com/hardkoded/puppeteer-sharp/issues/2648#issuecomment-2134442546), you can create a new `CookieParam` before calling `SetCookieAsync`:

```csharp
await page.SetCookieAsync(config.CookieParams.Select(cookie => new CookieParam()
{
    Url = cookie.Url,
    Domain = cookie.Domain,
    Name = cookie.Name,
    Value = cookie.Value,
    HttpOnly = cookie.HttpOnly,
    Secure = cookie.Secure,
    Path = cookie.Path,
    SameSite = cookie.SameSite,
    Expires = cookie.Expires,
    Size = cookie.Size,
    Session = cookie.Session,
    Priority = cookie.Priority
}).ToArray());
```

**Comment by kblok** [comment]
@olegfridman v18.0.5 is cooking with the fix :)
