### ISSUE TITLE
page.PdfDataAsync() gives timeout in Chromium v127 and above using Puppeteer v18

### ISSUE THREAD

**Issue by dssmith** [hardkoded/puppeteer-sharp#2718]
### Description

**We have this simple c# code to start browser, load html into page, then create PDF, when we point to different versions of Chromium i.e 124 vs 127 and above we seem to be getting Timeout of 180000 ms exceeded using later versions, as if it doesn't generate the PDF:**

### Complete minimal example reproducing the issue

var executablePath = @"[PATH TO CHROMIUM]\chrome.exe"; **//Switch between Chromium versions here**
var htmlFilePath = @"file:///[PATH TO HTML]";

var brwLaunchOptions = new LaunchOptions
{
	Headless = true,
	Args = new[] { "--headless=new" },
	ExecutablePath = executablePath
};

IBrowser Browser = await PuppeteerSharp.Puppeteer.LaunchAsync(brwLaunchOptions);

var pages = await Browser?.PagesAsync()!;

Console.WriteLine($"Current Open browser pages: [{pages.Length}], Html Path:{htmlFilePath}");

var page = await Browser.NewPageAsync();

// Set the dimensions of the PDF page and defaults
var options = new PdfOptions
{
	Format = PaperFormat.A4,
	Landscape = false,
	PrintBackground = true,
	PreferCSSPageSize = false,
	MarginOptions = new MarginOptions
	{
		Top = "0px",
		Right = "0px",
		Bottom = "0px",
		Left = "0px"
	},
	DisplayHeaderFooter = false, //assume no header or footer
	HeaderTemplate = "<div/>",   
	FooterTemplate = "<div/>"
};

await page.SetViewportAsync(new ViewPortOptions()
{
	Width = (int)options.Format.Width,
	Height = (int)options.Format.Height,
	DeviceScaleFactor = 1
});

await page.EmulateMediaTypeAsync(MediaType.Print);

await page.GoToAsync(htmlFilePath);

var pdfByteArray = await page.PdfDataAsync(options); **//We Get Timeout of 180000 ms exceeded when using v133**

File.WriteAllBytes(@"c:\temp\PdfSample.pdf",pdfByteArray);

await page.CloseAsync();

### Expected behavior:

We expect the html file to load, and then return byte[] when calling page.PdfDataAsync()

### Actual behavior:

We get a **Timeout of 180000 ms exceeded** result when using Chromium v127 and above

### Versions

Puppeteersharp 18.0.5
.NET 8.0
Chromium v124 and up

**Comment by kblok** [comment]
Can you try PuppeteerSharp 18.1.0-beta1, installing the browser using `BrowserFetcher`?

**Comment by dssmith** [comment]
> Can you try PuppeteerSharp 18.1.0-beta1, installing the browser using `BrowserFetcher`?

Hi @kblok , We have tried the new beta version, but still no success, we download the browsers using this method, and return the executing path:

```
public static async Task<string> DownloadBrowser(string buildId)
{
	var brwFetcherOptions = new BrowserFetcherOptions()
	{
		Browser = SupportedBrowser.Chromium,
		Path = @"C:\Temp\IIAB\Browser\"
	};
	var brwFetcher = new BrowserFetcher(brwFetcherOptions);
	
	await brwFetcher.DownloadAsync(buildId);
	
	var installs = brwFetcher.GetInstalledBrowsers();
	var chromium = installs.Where(x => x.Browser == SupportedBrowser.Chromium && x.BuildId == buildId).First();
	return chromium.GetExecutablePath();

}

```
We have downloaded a few versions of Chromium to test , and found that the method seems to have stopped working somewhere in Chromium versions after 124 - here is some of the versions we tried with the build id that was downloaded:

**BUILD   : VERSION**
1240089 : 122.0.6199.0
1259956 : 123.0.6300.0
1269966 : 124.0.6345.0
1270659 : 124.0.6349.0
1289936 : 126.0.6429.0 --> FAILS FROM HERE
1290958 : 126.0.6435.0
1300066 : 126.0.6478.0
1310065 : 127.0.6521.0
1327298 : 128.0.6597.0
1337231 : 129.0.6639.0

**Comment by dssmith** [comment]
Hi @kblok , from what I can see it seems that Chrome is working, but not Chromium - not sure if this will help at all?

**Comment by kblok** [comment]
Chrome/Chromium now requires some extra permissions on windows, [see](https://pptr.dev/troubleshooting#chrome-reports-sandbox-errors-on-windows).

PuppeteerSharp 18.1.0-beta1 is using a new `setup.exe` file which is part of the `Chrome for testing` download.
But chromium doesn' have that. [See my conversation upstream](https://github.com/puppeteer/puppeteer/pull/12430#issuecomment-2271141537).

It's weird to hear that you are getting the same on Linux. Can you try Chrome for testing in that docker image?

**Comment by SailAwayWine** [comment]
Apologies, if this isn't helpful, but having the same issue on Windows Server.  I didn't fiddle with Chrome versions, but rolling back to 18.0.5 resolved.   Version 18.1 doesn't work on a Windows Server using a regular user account, but on Windows 11 using an admin account it works fine, so I can't isolate on my development machine.

Here is the exception trace:

System.TimeoutException: Timeout of 180000 ms exceeded
   at PuppeteerSharp.Helpers.TaskHelper.WithTimeout[T](Task`1 task, TimeSpan timeout, Func`2 exceptionFactory) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Helpers/TaskHelper.cs:line 185
   at PuppeteerSharp.Cdp.CdpCDPSession.SendAsync(String method, Object args, Boolean waitForCallback, CommandOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Cdp/CdpCDPSession.cs:line 112
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args, CommandOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/CDPSession.cs:line 44
   at PuppeteerSharp.Cdp.CdpPage.PdfInternalAsync(String file, PdfOptions options) in /home/runner/work/puppeteer-sharp/puppeteer-sharp/lib/PuppeteerSharp/Cdp/CdpPage.cs:line 830

Here is the relevant code in VB
```
Sub Main()
      Dim opts As New BrowserFetcherOptions With {.Path = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)}
      With New BrowserFetcher(opts)
        .DownloadAsync().Wait(60000) 
        PuppeteerExecutablePath = .GetExecutablePath(BrowserData.Chrome.DefaultBuildId)
      End With
End Sub

Async Function Foo() as Task
    Using Chromium As IBrowser = Await Puppeteer.LaunchAsync(New LaunchOptions With {.Headless = True, .ExecutablePath = PuppeteerExecutablePath})
      Using CPage As IPage = Await Chromium.NewPageAsync
        Await CPage.SetViewportAsync(New ViewPortOptions With {.Width = 396, .Height = 559})
        Await CPage.SetCacheEnabledAsync(False)
        Await CPage.SetContentAsync(Ticket.ToString)
        Return Await CPage.PdfDataAsync(New PdfOptions With
                             {.MarginOptions = New Media.MarginOptions With {.Top = "45px", .Left = "19px", .Right = "19px"},
                             .Format = Media.PaperFormat.A6})

      End Using
    End Using
End Function
```

**Comment by kblok** [comment]
Folding into #2753

**Comment by plaisted** [comment]
Was this incorrectly closed? It doesn't seem to be related to the linked PR.

I am seeing this same timeout when generating large PDFs from sites but not small ones so it's an actual timeout, not some misconfiguration. This is also on Linux.

Looking at this library vs. puppeteer it appears that `PdfOptions` has a missing timeout option so I don't see a way to increase it.

**Comment by kblok** [comment]
@plaisted, your case looks like something to look at. Please create a ticket with some code I can run to reproduce that.
The `180000ms` timeout is A LOT. You don't want to increase that. But you can increase that timeout globally using [LaunchOptions.ProtocolTimeout](https://www.puppeteersharp.com/api/PuppeteerSharp.LaunchOptions.html#PuppeteerSharp_LaunchOptions_ProtocolTimeout).

**Comment by plaisted** [comment]
I walked through the code and did find the ProtocolTimeout and increasing that resolved my issue. I didn't realize this was something specific to the csharp implementation so thought was a missing property from something being sent over CDP. Three minutes may be a lot in some scenarios, here the resulting PDFs were thousands of pages so the duration is expected.
