### ISSUE TITLE
WaitForSelectorAsync() fails to wait more than 180000ms

### ISSUE THREAD

**Issue by ravriel** [hardkoded/puppeteer-sharp#2719]
### Description

If Page.WaitForSelectorAsync() is given a timeout of more than 180000ms, it will still timeout after 180000ms.

Thanks for a great project!

### Complete minimal example reproducing the issue

```csharp
var options = new LaunchOptions { };
using (var browser = await Puppeteer.LaunchAsync(options))
{
    using (var page = await browser.NewPageAsync())
    {
        await page.GoToAsync("https://example.org");

       // This will fails after 180000ms with:
        await page.WaitForSelectorAsync("no-such-selector", new WaitForSelectorOptions { Timeout = 300000 });
    }
}
```
### Expected behavior:

Expected timeout after the specified timeout (300000ms)

### Actual behavior:

Timeout after 180000ms
PuppeteerSharp.WaitTaskTimeoutException: Waiting for selector `no-such-selector` failed: Timeout of 180000 ms exceeded
  ---> System.TimeoutException: Timeout of 180000 ms exceeded

### Versions

* Which version of PuppeteerSharp are you using? 18.0.5
* Which .NET runtime and version are you targeting? .NET 8

**Comment by kblok** [comment]
Hey @ravriel those 180000ms are a safety net in the connection to prevent hangs.
You can increase that by setting a larger number to `ProtocolTimeout` property in the `LaunchOptions`.

**Comment by ravriel** [comment]
Thanks! 
Verified increasing `ProtocolTimeout` increases timeout.
