### ISSUE TITLE
PuppeteerSharp.NavigationException - Navigating frame was detached

### ISSUE THREAD

**Issue by 400ochkov** [hardkoded/puppeteer-sharp#2751]
Hello, I use PuppeteerSharp 19.0.1 and recently I started to encounter this issue. I just navigate to url and sometimes it happened (sometimes not). I dont understand why it happened, may be it is possible to explain or fix it?

**Comment by kblok** [comment]
I'm afraid it will be hard to fix it without a way to reproduce it.
Feel free to create a new issue with the steps to reproduce it.
