### ISSUE TITLE
PDF Issues

### ISSUE THREAD

**Issue by kblok** [hardkoded/puppeteer-sharp#2753]
### Description

This issue will be used to help users setup chrome in the cloud.

**Comment by cpGiesen** [comment]
Hello,
I like to reopen this issue.
https://github.com/hardkoded/puppeteer-sharp/issues/2718
The problem ist still there.
We use Version 20.0.0
The only workaround we can use ist:
            string executablePath = @$"{AppContext.BaseDirectory}\ChromeHeadlessShell\Win64-128.0.6613.119\chrome-headless-shell-win64\chrome-headless-shell.exe";

**Comment by kblok** [comment]
@cpGiesen did you take a look at [this](https://www.puppeteersharp.com/docs/IssuesGeneratingPdfFiles.html)?
