### ISSUE TITLE
v18.0.5 broke Firefox pref files

### ISSUE THREAD

**Issue by ferenc-a** [hardkoded/puppeteer-sharp#2772]
I relied on PuppeteerSharp not creating Firefox pref files and creating them manually before launching Firefox. This broke when I updated to [v18.0.5](https://github.com/hardkoded/puppeteer-sharp/releases/tag/v18.0.5). I tracked it down, and it was caused by this [this line](https://github.com/hardkoded/puppeteer-sharp/pull/2707/commits/7cc0f9ce0d829598dda5d9d8e2084e47078c5d48#diff-3798bc4acf42e924d6095cfb3e285b87b6824b30edc6ebadcd78e45f11befec0R127) (` Firefox.CreateProfile(`) going out of the conditional. I'd need either:
- An option to opt out from PuppeteerSharp creating these files so that I can go back to the old behaviour.
- More granular pref file support, so that I can use PuppeteerSharp to set up both my user.js and prefs.js files separately, and override PuppeteerSharps default values, like with `IgnoredDefaultArgs`

**Comment by kblok** [comment]
I think it's related to https://github.com/hardkoded/puppeteer-sharp/issues/2737. 
I'll put that next on my list :)
Closing in favor of #2737

**Comment by kblok** [comment]
@ferenc-a do you want to test 20.0.1-beta1 before I merge it?

**Comment by ferenc-a** [comment]
That'd nice, thanks! I'll take a look at it today, I have the repo cloned anyway.
It's this PR right? https://github.com/hardkoded/puppeteer-sharp/pull/2773
I looked at the code, but I'm not sure about the usage. Is it just that providing a UserDataDir now doesn't overwrite prefs, no changes needed on my end?

**Comment by kblok** [comment]
I just saw what you need. This PR is backing up your old prefs and restoring them when puppeteer closes the browser.
You have `options.ExtraPrefsFirefox` that will be merged in the `user.js` file with puppeteer's defaults. Will that help?

**Comment by ferenc-a** [comment]
I don't think so. I need to set up both prefs.js and user.js, entirely with my own prefs. Which I'd be happy to do with PuppeteerSharp too. But looking at the current implementation, it looks like prefs.js is alway overridden to be empty. I also don't see how I'd delete or override the values that get applied by GetDefaultPreferences and GetPreferences.

**Comment by kblok** [comment]
@ferenc-a what's the setting that we're putting there that's breaking your scenario. Maybe with the right use-case we can request that change in puppeteer.
I won't add any feature that it's not in puppeteer.

**Comment by ferenc-a** [comment]
I have tens of custom prefs, and don't really want to start investigating which one breaks the launch. Even if the launch doesn't break, I need all of them overriding Puppeteer defaults, persisting and not be deleted on startup. That is my use case, not any individual pref.
