### ISSUE TITLE
[Bug]: PuppeteerSharp.ProcessException: Timed out after 30000 ms while trying to connect to Base!\n   at PuppeteerSharp.States.ProcessStartingState.StartCoreAsync(LauncherBase p)

### ISSUE THREAD

**Issue by bangyanli-webjet** [hardkoded/puppeteer-sharp#2777]
### Description

Firefox version larger than 129.0

### Complete minimal example reproducing the issue

```csharp
                var firefoxPath = "/usr/bin/firefox";
                var fireFoxCreateProfileArgs = $"-CreateProfile {firefoxProfileName} -headless";
                ProcessStartInfo startInfo = new ProcessStartInfo() { FileName = firefoxPath, Arguments = fireFoxCreateProfileArgs };
                Process proc = new Process() { StartInfo = startInfo, };
                proc.Start();
                
              var launchOptions = new LaunchOptions
            {
                Headless = true,
                Browser = SupportedBrowser.Firefox,
                LogProcess = false,
                DumpIO = false,
                Devtools = false,
                UserDataDir = "/app/",
                Args = new string[] { "-new-instance" , "-P", $"\"{firefoxProfileName}\"" } //new instance with new profile
            };
            
            await using var browser = await Puppeteer.LaunchAsync(launchOptions);
```

### Expected behavior:

Puppeteer should be launched successfully

### Actual behavior:

throw exception "PuppeteerSharp.ProcessException : Timed out after 30000 ms while trying to connect to Base!"

### Versions

16.0.0

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
* .NET  Core 6.0

**Comment by kblok** [comment]
Unfortunately, until we implement webdriver Bidi. The Firefox version is pinned to 129.

**Comment by michael-freidgeim-webjet** [comment]
> Unfortunately, until we implement webdriver Bidi. The Firefox version is pinned to 129.

@kblok Do you have an issue that shows a progress of your work with webdriver Bidi?
I’ve only found https://github.com/hardkoded/puppeteer-sharp/discussions/2872#discussioncomment-11984440
