### ISSUE TITLE
Generating corrupt PDF output

### ISSUE THREAD

**Issue by tacoWanneeJama** [hardkoded/puppeteer-sharp#2778]
### Description

The output of a simple content is unreadable by Acrobat reader

### Complete minimal example reproducing the issue

[https://github.com/Alexander-JM-0224/PdfServer.git](url)

### Expected behavior:

A pdf document that can be successfully opened by Acrobat reader

### Actual behavior:

Errormessage of Adobe Acrobat reader: 
![image](https://github.com/user-attachments/assets/42e6b16e-9586-48d7-b542-c19d0443764e)

### Versions

.Net 8, PuppeteerSharp 17.0.0

### Additional Information

With the latest version of PuppeteerSharp the same problem occurs

**Comment by kblok** [comment]
Is that happening with any website?

**Comment by tacoWanneeJama** [comment]
We also tried with our company website, with the same error.
We als got this problem when we transformed a Blazor component to HTML, and put that through Puppeteer. In this situation it sometime creates a readable PDF and sometimes with the same error.

**Comment by kblok** [comment]
I think this is something to report to [Chromium bugs](https://issues.chromium.org/issues). We rely on the browser's ability to generate the PDF. If you can create an isolated script in Puppeteer (I can help you with that) and reproduce it, we can report it.

It would also be great to have the error in English. It will be easier to google and also search in chromium bugs.

**Comment by tacoWanneeJama** [comment]
> I think this is something to report to [Chromium bugs](https://issues.chromium.org/issues). We rely on the browser's ability to generate the PDF. If you can create an isolated script in Puppeteer (I can help you with that) and reproduce it, we can report it.
> 
> It would also be great to have the error in English. It will be easier to google and also search in chromium bugs.

The github project is not isolated enough?

**Comment by kblok** [comment]
> > I think this is something to report to [Chromium bugs](https://issues.chromium.org/issues). We rely on the browser's ability to generate the PDF. If you can create an isolated script in Puppeteer (I can help you with that) and reproduce it, we can report it.
> > It would also be great to have the error in English. It will be easier to google and also search in chromium bugs.
> 
> The github project is not isolated enough?

What do you mean?

**Comment by tacoWanneeJama** [comment]
[https://github.com/hardkoded/puppeteer-sharp/issues/url](url)

**Comment by tacoWanneeJama** [comment]
[[https://github.com/Alexander-JM-0224/PdfServer.git](https://github.com/hardkoded/puppeteer-sharp/issues/url)](url)

**Comment by kblok** [comment]
> [[https://github.com/Alexander-JM-0224/PdfServer.git](https://github.com/hardkoded/puppeteer-sharp/issues/url)](url)

Again, I think this is something to report in chromium bugs.
