### ISSUE TITLE
ClickAsync Timeout

### ISSUE THREAD

**Issue by merco** [hardkoded/puppeteer-sharp#2779]
I've a page with 

page.ClickAsync("#__button12" );

The script runs ok but it takes very long time to complete.
So i'm getting this error:

![immagine](https://github.com/user-attachments/assets/f45c746a-65c9-4c6a-bdc9-53df53b1165a)

Is there a way to avoid timeout?

**Comment by merco** [comment]
in headful mode runs without problems

**Comment by merco** [comment]
Other error in headless mode

![immagine](https://github.com/user-attachments/assets/5cabb3a7-f6dc-4c0a-8b0c-19daf0f43e22)

**Comment by kblok** [comment]
> Other error in headless mode
> 
> ![immagine](https://private-user-images.githubusercontent.com/1032335/366887267-5cabb3a7-f6dc-4c0a-8b0c-19daf0f43e22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDcxMzUsIm5iZiI6MTcyNjE0NjgzNSwicGF0aCI6Ii8xMDMyMzM1LzM2Njg4NzI2Ny01Y2FiYjNhNy1mNmRjLTRjMGEtOGIwYy0xOWRhZjBmNDNlMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMTMxMzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWE3MjIxZjNiODhjYjMwM2U5MTU5MjQ4N2I3ZWUzMDJmNGNhZjM2OWQxODIyOWExY2ZjN2U2MThhYzQxNDdkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LEIj6Y5eQYmi_VgG720S5ztm_mXAvLi80bw5O-n7hls)

It looks like an error on a Console event listener you have?

**Comment by merco** [comment]
_It looks like an error on a Console event listener you have?_ 

I'm using always the same input and yes I have a Page_Console event handler but why sometimes runs ok and sometimes not? Even with the same input?

**Comment by kblok** [comment]
Can you also check if, by removing the event, the click stops getting stuck? Maybe is the listener that's breaking the flow.

**Comment by merco** [comment]
Oh yes I have list and dict
.. how can avoid events not in same time?

```
void Page_Console(object? sender, ConsoleEventArgs e)
{
     if (e.Message.Type == ConsoleType.Log)
    {
        if (e.Message.Text.StartsWith("scene._scene.traverse.end"))
        {
            structMode = false;
            return;
       }

        if (structMode)
        {
            if (rootNode==null)
            {
                rootNode= new NodeObj();
                rootNode = Newtonsoft.Json.JsonConvert.DeserializeObject<NodeObj>(e.Message.Text);
                lastNode= rootNode; 
            } else
            {
                NodeObj thisNode = Newtonsoft.Json.JsonConvert.DeserializeObject<NodeObj>(e.Message.Text);
                NodeObj pNode = NodeList[thisNode.ParentId];
                pNode.Items.Add(thisNode);
                lastNode = thisNode;

            }

            if (MeshList.ContainsKey(lastNode.Id))
            {
                lastNode.Mesh= MeshList[lastNode.Id];
            }
            JSObjectIndex = JSObjectIndex + 1;
            Console.WriteLine("Traversing scene " + JSObjectIndex.ToString() + "/" + JSObjectCount.ToString());
            PushNode(lastNode);
            return;
        }

        if (e.Message.Text.StartsWith("Processing file") && e.Message.Text.Contains("finished"))
        {
            loaded3D = true;
            return;
        }
        if (e.Message.Text.StartsWith("scene._scene.traverse.start"))
        {
            structMode = true;
            JSObjectCount = System.Convert.ToInt64( e.Message.Text.Replace("scene._scene.traverse.start:", ""));
            return;

        }


        if (e.Message.Text.StartsWith("{\"AAXX\":\"C@MER@\""))
        {
            CameraObj deserializedCam = Newtonsoft.Json.JsonConvert.DeserializeObject<CameraObj>(e.Message.Text);
            CameraList.Add(deserializedCam);
            Console.WriteLine("Lettura Camera " + deserializedCam.Name);
        }
        if (e.Message.Text.StartsWith("{\"AAXX\":\"ME$H\""))
        {
    

            MeshObj deserializedProduct = Newtonsoft.Json.JsonConvert.DeserializeObject<MeshObj>(e.Message.Text);
            MeshList.Add(deserializedProduct.Id,deserializedProduct);
            Console.WriteLine("Lettura Mesh " + deserializedProduct.PROG);

        }

    }


}
```

**Comment by kblok** [comment]
> .. how can avoid events not in same time?

You can't trust the order in which the browser sends messages.

**Comment by merco** [comment]
Same code in debug IDE (VS2022) runs wothout errors

**Comment by merco** [comment]
How can I increase this timeout ?

![immagine](https://github.com/user-attachments/assets/125ec274-a016-4414-81cf-0ac8a0578740)
