### ISSUE TITLE
Chrome 129 headless Error

### ISSUE THREAD

**Issue by magdev2022** [hardkoded/puppeteer-sharp#2782]
Today, I updated the Chrome browser to the latest version (129).
After the update, running Chrome in headless mode produces an unusual result: a blank white window appears, matching the size of the browser.
![image](https://github.com/user-attachments/assets/5dd7d305-e830-409a-97c3-9af5f517bc53)

**Comment by kblok** [comment]
We don't have support for 129 yet. Upstream change in puppeteer might come soon.

**Comment by magdev2022** [comment]
I tested on chrome128 and chrome130. there was no problem. I think chromium(129) has a problem.

**Comment by vmeganathan81** [comment]
Do you know how to fix this issue interim?

**Comment by kblok** [comment]
So you are using your installed browser rather than the one downloaded by puppeteer right?

**Comment by vmeganathan81** [comment]
Yes we are using installed browser

**Comment by kblok** [comment]
I tried to reproduce that. But I'm not getting that on Chrome 129.0.6668.60 on MacOS.

**Comment by kblok** [comment]
It seems this was reported on Selenium [here](https://github.com/SeleniumHQ/selenium/issues/14544). It was also reported on chromium bugs [here](https://issues.chromium.org/issues/367755364).

One potential, an ugly, workaround is to add this command line argument `--window-position=-2400,-2400`.

**Comment by kblok** [comment]
It is also reported that you could replace `Headless = false` with `HeadlessMode = HeadlessMode.Shell`.

**Comment by jaydeep009** [comment]
> It is also reported that you could replace `Headless = false` with `HeadlessMode = HeadlessMode.Shell`.

That is not correct way, since that will point to old headless mode which is going to be out of support from chrome soon.
By default parameters, i.e new headless we are getting this white screen.

**Comment by kblok** [comment]
> > It is also reported that you could replace `Headless = false` with `HeadlessMode = HeadlessMode.Shell`.
> 
> That is not correct way, since that will point to old headless mode which is going to be out of support from chrome soon. By default parameters, i.e new headless we are getting this white screen.

Ok so you'll need to wait till the chromium team fixes the bug.

**Comment by CaCTuCaTu4ECKuu** [comment]
Can confirm that current build as of 26 Oct 2024 have this issue
I'm running next code

```
var browserFetcher = new BrowserFetcher();
await browserFetcher.DownloadAsync()
    .ConfigureAwait(false);

var launchOptions = new LaunchOptions()
{
    Args = new string[]
    {
        "--no-sandbox"
    },
    Headless = true
};
browser = await Puppeteer.LaunchAsync(launchOptions).ConfigureAwait(false);
```
Fetching loads `Chrome/129.0.6668.100`

* Windows 11 23H2 (22631.4317)
* net6.0

Waiting for new PuppeteerSharp version?
