### ISSUE TITLE
Puppeteer fails to launch chromium without internet access

### ISSUE THREAD

**Issue by AshIzat** [hardkoded/puppeteer-sharp#2800]
### Description

Puppeteer makes an external web request to get the build id of chromium. this fails in an enviroment where the requested url isn't accessible.

### Complete minimal example reproducing the issue

```csharp
var options = new LaunchOptions { ExecutablePath = executablePath, Browser = SupportedBrowser.Chromium };
var browser = await Puppeteer.LaunchAsync(options); // throws if unable to access internet
```

### Expected behavior:

Since the code only uses this build id to get the executable path, setting the path in the options should should skip this request and allow puppeteer to work with chromium without external internet access. Chrome does not require the same remote web request.

### Actual behavior:
Puppeteer tries to access the remote url and throws an exception

### Versions

* Pupeteer version: master
* dotnet version: dotnet 8.0

**Comment by kblok** [comment]
v20.0.3 published
