### ISSUE TITLE
WaitTaskTimeoutException: Waiting failed: 30000ms exceeded   

### ISSUE THREAD

**Issue by oriches** [hardkoded/puppeteer-sharp#2803]
Hi, I am using Plotly.NET.ImageExport version 6.1.0 which has a dependency on PuppeteerSharp (>= 18.0.0) and even if I upgrade to the lastest PuppeteerSharp I am seeing the follow exception.

I have also tried setting the Timeout in PuppeteerSharpRendererOptions.navigationOptions to zero.

PuppeteerSharpRendererOptions.navigationOptions.Timeout = 0;

Any ideas if I can disable this Timeout in PuppeteerSharp.Realm.WaitForExpressionAsync? 

Exception:

WaitTaskTimeoutException: Waiting failed: 30000ms exceeded
PuppeteerSharp.Realm.WaitForExpressionAsync(string, PuppeteerSharp.WaitForFunctionOptions)

**Comment by kblok** [comment]
I'm afraid I will need more info. What's the website? What's the expression you're waiting for?

**Comment by oriches** [comment]
![image001](https://github.com/user-attachments/assets/40efb343-213e-4895-866a-596d681431b1)

**Comment by kblok** [comment]
That's not quite helpful. Did you ask in Plotly.NET.ImageExport?

**Comment by oriches** [comment]
Will do, thanks for the help
