### ISSUE TITLE
Make sure zero-width screenshots don't hang

### ISSUE THREAD

**Issue by kblok** [hardkoded/puppeteer-sharp#668]
https://github.com/kblok/puppeteer/pull/12/commits/c644a3bbd3ee9722705a5a672a09828b9b90651b

**Comment by bdurrani** [comment]
I'll take a stab at this one

**Comment by kblok** [comment]
Go for it @bdurrani

**Comment by bdurrani** [comment]
I'm getting a TargetClosedException with the following test

```
        public async Task ShouldNotHangWithZeroWidthHeightElement()
        {
            try
            {
            await Page.SetContentAsync(@"<div style='width: 0; height: 0'></div>");
            var elementHandle = await Page.QuerySelectorAsync("div");
            var screenshot = await elementHandle.ScreenshotDataAsync();
            Assert.NotNull(screenshot); 
            }
            catch(TargetClosedException ex)
            {
                ex.ToString();
            }
        }

```
The specific error is

`Message: PuppeteerSharp.TargetClosedException : Protocol error(Page.captureScreenshot): Target closed.`


I'm using Windows 10. I get the exception if either width or height are 0. 
Any thoughts on how to proceed?
According to[ this issue](https://github.com/GoogleChrome/puppeteer/issues/2672), looks like this is a known issue for linux

**Comment by kblok** [comment]
@bdurrani push your PR so we can take a look.

**Comment by bdurrani** [comment]
@kblok done!
