### ISSUE TITLE
add docs for migrating from selenium to puppeteersharp

### ISSUE THREAD

**Issue by Meir017** [hardkoded/puppeteer-sharp#719]
- [ ] A sample of the PageObjectModel design using puppeteersharp
- [ ] IWebElement equivalent using puppeteer

**Comment by speiu18** [comment]
This would be a very useful thing to have! Can't wait for it!

**Comment by kgar** [comment]
I currently work with someone who uses selenium for their automated testing while I use PuppeteerSharp for web scraping. Can I help in some way?
