### ISSUE TITLE
Add samples to the CI build

### ISSUE THREAD

**Issue by kblok** [hardkoded/puppeteer-sharp#734]
We need to build the samples as part of the CI so we can be sure that those samples won't be outdated.

I would also move the Demo project as part of the samples projects as "How to generate PDFs"

We need to find a way to build that solution using the code in that branch instead of the Nuget package. Maybe using the package generated as a local source?

**Comment by Meir017** [comment]
Or we can reference puppeteersharp as a project reference instead of a package reference

**Comment by kblok** [comment]
@Meir017 I can buy that. The downside of that is that a user would need to download the entire repo to run those samples. Thoughts @bdurrani?

**Comment by Meir017** [comment]
That's how the aspnet team do it https://github.com/aspnet/Mvc/blob/release/2.2/samples/MvcSandbox/MvcSandbox.csproj

**Comment by kblok** [comment]
@Meir017 that's the kind of answer I like to read :)

**Comment by bdurrani** [comment]
Personally I would prefer these examples to be standalone. So if someone wanted they could zip up the samples folder and get things up and running without the rest of the repo

**Comment by kblok** [comment]
Our current Demo project has 2 solutions, one using a package and another with a reference only for the CI.
I think if we add our bin as a local package source we can have only one project that will work both for the CI and both standalone.

The other thing is the versioning. We(I) tend to forget to update the demo project so that package reference tends to be outdated.

**Comment by Meir017** [comment]
or instead of using a package reference we can add a [`dependencies.props`](https://github.com/aspnet/Mvc/blob/release/2.2/build/dependencies.props) file and import it from all of the sample csproj file and then write something like this:
`any csproj file`:
```xml
<Import Project="../dependencies.props" />
<PackageReference Include="PuppeteerSharp" Version="$(PuppeteerSharpPackageVersion)" />
```
