### ISSUE TITLE
Drag and drop doesn't work

### ISSUE THREAD

**Issue by ffMathy** [hardkoded/puppeteer-sharp#933]
The following code does not work for dragging and dropping:

```
	await _page.Mouse.MoveAsync(140, 140);
	await _page.Mouse.DownAsync();

	await _page.Mouse.MoveAsync(140, 380,
		new MoveOptions() {
			Steps = 100
		});
	await _page.Mouse.UpAsync();
```

Attached is the page that I am doing this on.

Note that the events actually do fire, but the final `#result` label does not contain the proper drop event text that is present when dragging/dropping in the browser.

[drag.zip](https://github.com/kblok/puppeteer-sharp/files/2898187/drag.zip)

**Comment by kblok** [comment]
I think we need to wait from Puppeteer on this one https://github.com/GoogleChrome/puppeteer/issues/1376

**Comment by ffMathy** [comment]
@kblok this was fixed in https://github.com/puppeteer/puppeteer/pull/7150.

Any chance to make it into Puppeteer Sharp?

**Comment by kblok** [comment]
I created this issue a few days ago https://github.com/hardkoded/puppeteer-sharp/issues/1744

I plan to try to catch pptr again. PRs and/or sponsorships are welcome.
